///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTD1MODEL_H__
#define __SIPPTUTD1MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>



//The full-frame buffers
extern UInt8 DDR_DATA SippTutD1Model_dmaIn0_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutD1Model_dmaOut1_buffer[ 256 * 256 * 1 ]ALIGNED(8);
	
///

typedef struct SippTutD1Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut1;
	SippFilter *scale05BilinHV2;

} SippTutD1Model;

void readSippTutD1ModelInput(SippTutD1Model *pPl);
void writeSippTutD1ModelOutput(SippTutD1Model *pPl);

void buildSippTutD1Model(SippTutD1Model *pPl);
void configSippTutD1Model(SippTutD1Model *pPl);


#endif