///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "sippTutD1Model.h"

#include <include/sippHwDefs.h>
#include <filters/scale05bilinHV/scale05BilinHV.h>


//The full-frame buffers
UInt8      DDR_DATA SippTutD1Model_dmaIn0_buffer[512      * 512     * 1  ]ALIGNED(8);
UInt8      DDR_DATA SippTutD1Model_dmaOut1_buffer[256      * 256     * 1  ]ALIGNED(8);
	
///
void readSippTutD1ModelInput(SippTutD1Model *pPl)
{
   sippRdFileU8((UInt8*)SippTutD1Model_dmaIn0_buffer,512        * 512     * 1 * sizeof(UInt8),"../../../../../../../resources/lena_512x512_luma.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeSippTutD1ModelOutput(SippTutD1Model *pPl)
{
   sippWrFileU8((UInt8*)SippTutD1Model_dmaOut1_buffer,256        * 256     * 1 * sizeof(UInt8),"output.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildSippTutD1Model(SippTutD1Model *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->scale05BilinHV2 =  sippCreateFilter(pPl->pl, SIPP_RESIZE, 256,    256,    N_PL(1),  SZ(UInt8), 0,                  SVU_SYM(svuScl05BilinHV),     0);
   pPl->dmaOut1         =  sippCreateFilter(pPl->pl, 0x00,       256,    256,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->scale05BilinHV2, pPl->dmaIn0,        2,2                 );
   sippLinkFilter(pPl->dmaOut1,       pPl->scale05BilinHV2, 1,1                 );
	
}

  
void configSippTutD1Model(SippTutD1Model *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   DmaParam            *dmaOut1Cfg         = (DmaParam         *)pPl->dmaOut1->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   dmaIn0Cfg->ddrAddr   = (UInt32)&SippTutD1Model_dmaIn0_buffer;
   dmaOut1Cfg->ddrAddr  = (UInt32)&SippTutD1Model_dmaOut1_buffer;
  
  
}
