///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "testHwLumaDns.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt8      DDR_DATA TestHwLumaDns_dmaIn0_buffer[SIPP_HW_LUM_DNS_BUFFER_WIDTH* SIPP_HW_LUM_DNS_BUFFER_HEIGHT* SIPP_HW_LUM_DNS_BUFFER_NUM_PLANES]ALIGNED(8);
UInt8      DDR_DATA TestHwLumaDns_dmaOut0_buffer[SIPP_HW_LUM_DNS_BUFFER_WIDTH* SIPP_HW_LUM_DNS_BUFFER_HEIGHT* SIPP_HW_LUM_DNS_BUFFER_NUM_PLANES]ALIGNED(8);
	
///
void readTestHwLumaDnsInput(TestHwLumaDns *pPl)
{
   sippRdFileU8((UInt8*)TestHwLumaDns_dmaIn0_buffer,SIPP_HW_LUM_DNS_BUFFER_WIDTH * SIPP_HW_LUM_DNS_BUFFER_HEIGHT * SIPP_HW_LUM_DNS_BUFFER_NUM_PLANES* sizeof(UInt8),"../../../../../../../resources/OCT_384x290_I_Y_dns_luma_8bpp.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeTestHwLumaDnsOutput(TestHwLumaDns *pPl)
{
   sippWrFileU8((UInt8*)TestHwLumaDns_dmaOut0_buffer,SIPP_HW_LUM_DNS_BUFFER_WIDTH * SIPP_HW_LUM_DNS_BUFFER_HEIGHT * SIPP_HW_LUM_DNS_BUFFER_NUM_PLANES* sizeof(UInt8),"output.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildTestHwLumaDns(TestHwLumaDns *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 0, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_LUM_DNS_BUFFER_WIDTH, SIPP_HW_LUM_DNS_BUFFER_HEIGHT, N_PL(SIPP_HW_LUM_DNS_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->ydnsMa2x5x0     =  sippCreateFilter(pPl->pl, 0x0,        SIPP_HW_LUM_DNS_BUFFER_WIDTH, SIPP_HW_LUM_DNS_BUFFER_HEIGHT, N_PL(SIPP_HW_LUM_DNS_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_LUMA_ID,       0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_LUM_DNS_BUFFER_WIDTH, SIPP_HW_LUM_DNS_BUFFER_HEIGHT, N_PL(SIPP_HW_LUM_DNS_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->ydnsMa2x5x0,   pPl->dmaIn0,        11,11               );
   sippLinkFilter(pPl->dmaOut0,       pPl->ydnsMa2x5x0,   1,1                 );
	
}

  
void configTestHwLumaDns(TestHwLumaDns *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   YDnsParam           *ydnsMa2x5x0Cfg     = (YDnsParam        *)pPl->ydnsMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   ydnsMa2x5x0Cfg->cfg=     0x01084005;
   ydnsMa2x5x0Cfg->gaussLut[0]=0x9abddeef;
   ydnsMa2x5x0Cfg->gaussLut[1]=0x12234578;
   ydnsMa2x5x0Cfg->gaussLut[2]=0x0;
   ydnsMa2x5x0Cfg->gaussLut[3]=0x0;
   ydnsMa2x5x0Cfg->f2=      0;
   ydnsMa2x5x0Cfg->gammaLut[0]=0x665a4900;
   ydnsMa2x5x0Cfg->gammaLut[1]=0x837d776f;
   ydnsMa2x5x0Cfg->gammaLut[2]=0xa8890089;
   ydnsMa2x5x0Cfg->gammaLut[3]=0xeadecfbe;
   ydnsMa2x5x0Cfg->gammaLut[4]=0x1000fff5;
   ydnsMa2x5x0Cfg->distCfg= (u32)distLUT;
   ydnsMa2x5x0Cfg->distOffsets=X_OFFSET | (Y_OFFSET << 16);
   ydnsMa2x5x0Cfg->fullFrmDim= FULL_IMAGE_WIDTH | (FULL_IMAGE_HEIGHT << 16);
   dmaIn0Cfg->ddrAddr   = (UInt32)&TestHwLumaDns_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwLumaDns_dmaOut0_buffer;
  
  
}
