///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTC3MODEL_H__
#define __SIPPTUTC3MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "sippMat.h"


//The full-frame buffers
extern UInt8 DDR_DATA SippTutC3Model_dmaIn0_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutC3Model_dmaOut1_buffer[ 512 * 512 * 1 ]ALIGNED(8);
	
///

typedef struct SippTutC3Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut1;
	SippFilter *erode5x52;
	SippFilter *dilate5x53;

} SippTutC3Model;

void readSippTutC3ModelInput(SippTutC3Model *pPl);
void writeSippTutC3ModelOutput(SippTutC3Model *pPl);

void buildSippTutC3Model(SippTutC3Model *pPl);
void configSippTutC3Model(SippTutC3Model *pPl);


#endif