///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "sippTutA3Model.h"

#include <include/sippHwDefs.h>
#include <filters/conv5x5/conv5x5.h>


//The full-frame buffers
UInt8      DDR_DATA SippTutA3Model_dmaIn0_buffer[512      * 512     * 1  ]ALIGNED(8);
UInt8      DDR_DATA SippTutA3Model_dmaOut1_buffer[512      * 512     * 1  ]ALIGNED(8);
	
///
void readSippTutA3ModelInput(SippTutA3Model *pPl)
{
   sippRdFileU8((UInt8*)SippTutA3Model_dmaIn0_buffer,512        * 512     * 1 * sizeof(UInt8),"../../../../../../../resources/lena_512x512_luma.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeSippTutA3ModelOutput(SippTutA3Model *pPl)
{
   sippWrFileU8((UInt8*)SippTutA3Model_dmaOut1_buffer,512        * 512     * 1 * sizeof(UInt8),"output.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildSippTutA3Model(SippTutA3Model *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->conv5x52        =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SZ(Conv5x5Param),   SVU_SYM(svuConv5x5),          0);
   pPl->dmaOut1         =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->conv5x52,      pPl->dmaIn0,        5,5                 );
   sippLinkFilter(pPl->dmaOut1,       pPl->conv5x52,      1,1                 );
	
}

UInt16 conv5x52Cfg_cMat[25];
  
void configSippTutA3Model(SippTutA3Model *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   Conv5x5Param        *conv5x52Cfg        = (Conv5x5Param     *)pPl->conv5x52->params;
   DmaParam            *dmaOut1Cfg         = (DmaParam         *)pPl->dmaOut1->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   conv5x52Cfg->cMat=       conv5x52Cfg_cMat;
   conv5x52Cfg->cMat[0]=    0x0000;
   conv5x52Cfg->cMat[1]=     0x0000;
   conv5x52Cfg->cMat[2]=     0x0000;
   conv5x52Cfg->cMat[3]=     0x0000;
   conv5x52Cfg->cMat[4]=     0x0000;
   conv5x52Cfg->cMat[5]=     0x0000;
   conv5x52Cfg->cMat[6]=     0x0000;
   conv5x52Cfg->cMat[7]=     0x3C00;
   conv5x52Cfg->cMat[8]=     0x0000;
   conv5x52Cfg->cMat[9]=     0x0000;
   conv5x52Cfg->cMat[10]=    0x0000;
   conv5x52Cfg->cMat[11]=    0x3C00;
   conv5x52Cfg->cMat[12]=    0xC400;
   conv5x52Cfg->cMat[13]=    0x3C00;
   conv5x52Cfg->cMat[14]=    0x0000;
   conv5x52Cfg->cMat[15]=    0x0000;
   conv5x52Cfg->cMat[16]=    0x0000;
   conv5x52Cfg->cMat[17]=    0x3C00;
   conv5x52Cfg->cMat[18]=    0x0000;
   conv5x52Cfg->cMat[19]=    0x0000;
   conv5x52Cfg->cMat[20]=    0x0000;
   conv5x52Cfg->cMat[21]=    0x0000;
   conv5x52Cfg->cMat[22]=    0x0000;
   conv5x52Cfg->cMat[23]=    0x0000;
   conv5x52Cfg->cMat[24]=    0x0000 ;
   dmaIn0Cfg->ddrAddr   = (UInt32)&SippTutA3Model_dmaIn0_buffer;
   dmaOut1Cfg->ddrAddr  = (UInt32)&SippTutA3Model_dmaOut1_buffer;
  
  
}
