/* usbpump_proto_vsc2.h	Tue Aug 11 2015 12:59:39 chwon */

/*

Module:  usbpump_proto_vsc2.h

Function:
	Definition of the VSC protocol

Version:
	V3.15c	Tue Aug 11 2015 12:59:39 chwon	Edit level 2

Copyright notice:
	This file copyright (C) 2013, 2015 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	ChaeHee Won, MCCI Corporation	March 2013

Revision history:
   3.11c  Fri Mar 22 2013 13:46:22 chwon
	16968: Module created.

   3.15c  Tue Aug 11 2015 12:59:40  chwon
	19385: Fix type cloaking for USBPUMP_PROTO_VSC2_ENUM_NAME.

*/

#ifndef _USBPUMP_PROTO_VSC2_H_	/* prevent multiple includes */
#define _USBPUMP_PROTO_VSC2_H_

#ifndef _USBPUMP_PROTO_VSC2_TYPES_H_
# include "usbpump_proto_vsc2_types.h"
#endif

#ifndef _USBPROTOINIT_H_
# include "usbprotoinit.h"
#endif

#ifndef _USBPUMPOBJECTNAME_H_
# include "usbpumpobjectname.h"
#endif

#ifndef _USBUUID_H_
# include "usbuuid.h"
#endif

/****************************************************************************\
|
|	VSC protocol object
|
\****************************************************************************/

/* vsc protocol object tag */
#define	__TMS_USBPUMP_PROTO_VSC2_TAG	__TMS_UHIL_MEMTAG('V', 's', 'c', '2')

/*
|| this expands to something like "vsc2.fn.mcci.com"
|| remember, you'll normally match on "vsc2.*.fn.mcci.com", or even
|| "vsc2.*.fn.*"
*/
#define	__TMS_USBPUMP_PROTO_VSC2_NAME(tag)	\
	__TMS_USBPUMP_OBJECT_NAME_FN("vsc2", tag)

#define	__TMS_USBPUMP_PROTO_VSC2_ENUM_NAME	\
	__TMS_USBPUMP_PROTO_VSC2_NAME("*")

/* VSC protocol GUID initialization macro */
#define	__TMS_USBPUMP_PROTO_VSC2_GUID_INIT()			\
	__TMS_USBUUID_INIT(0xd695c4cb, 0x9549, 0x4ef0,		\
		0x82, 0xdb, 0x9f, 0xf4, 0x07, 0x87, 0x8e, 0x19)


/****************************************************************************\
|
|	API functions
|
\****************************************************************************/

__TMS_BEGIN_DECLS

extern __TMS_CONST __TMS_USBGUID	gk_UsbPumpProtoVsc2_Guid;

__TMS_USBPUMP_PROTOCOL_CREATE_FN	UsbPumpProtoVsc2_Create;
__TMS_USBPUMP_PROTOCOL_PROBE_FN		UsbPumpProtoVsc2_Probe;

__TMS_CONST __TMS_TEXT *
UsbPumpProtoVsc2_GetEventName(
	__TMS_USBPUMP_PROTO_VSC2_EVENT		/* EventCode */
	);

__TMS_CONST __TMS_TEXT *
UsbPumpProtoVsc2_GetStatusName(
	__TMS_USBPUMP_PROTO_VSC2_STATUS	/* StatusCode */
	);

__TMS_END_DECLS


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_PROTO_VSC2_TAG	\
   __TMS_USBPUMP_PROTO_VSC2_TAG
# define USBPUMP_PROTO_VSC2_NAME(tag)	\
   __TMS_USBPUMP_PROTO_VSC2_NAME(tag)
# define USBPUMP_PROTO_VSC2_ENUM_NAME	\
   __TMS_USBPUMP_PROTO_VSC2_ENUM_NAME
# define USBPUMP_PROTO_VSC2_GUID_INIT()	\
   __TMS_USBPUMP_PROTO_VSC2_GUID_INIT()
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpump_proto_vsc2.h ****/
#endif /* _USBPUMP_PROTO_VSC2_H_ */
