#Activate the flag that disables the default debug mode build because of larger code sections. Code section is larger on ma2480
BUILD_WITH_CODE_SIZE_OPTIMIZATION=yes
include ../blis_test.mk
CCOPT += -DTEST_SYRK
