///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "sippTutA1Model.h"

#include <include/sippHwDefs.h>
#include <filters/conv5x5/conv5x5.h>


//The full-frame buffers
UInt8      DDR_DATA SippTutA1Model_dmaIn0_buffer[512      * 512     * 1  ]ALIGNED(8);
UInt8      DDR_DATA SippTutA1Model_dmaOut0_buffer[512      * 512     * 1  ]ALIGNED(8);
	
///
void readSippTutA1ModelInput(SippTutA1Model *pPl)
{
   sippRdFileU8((UInt8*)SippTutA1Model_dmaIn0_buffer,512        * 512     * 1 * sizeof(UInt8),"../../../../../../../resources/lena_512x512_luma.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeSippTutA1ModelOutput(SippTutA1Model *pPl)
{
   sippWrFileU8((UInt8*)SippTutA1Model_dmaOut0_buffer,512        * 512     * 1 * sizeof(UInt8),"output.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildSippTutA1Model(SippTutA1Model *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->conv5x50        =  sippCreateFilter(pPl->pl, 0x0,        512,    512,    N_PL(1),  SZ(UInt8), SZ(Conv5x5Param),   SVU_SYM(svuConv5x5),          0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->conv5x50,      pPl->dmaIn0,        5,5                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->conv5x50,      1,1                 );
	
}

UInt16 conv5x50Cfg_cMat[25];
  
void configSippTutA1Model(SippTutA1Model *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   Conv5x5Param        *conv5x50Cfg        = (Conv5x5Param     *)pPl->conv5x50->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   conv5x50Cfg->cMat=       conv5x50Cfg_cMat;
   conv5x50Cfg->cMat[0]=    0x291f;
   conv5x50Cfg->cMat[1]=     0x291f;
   conv5x50Cfg->cMat[2]=     0x291f;
   conv5x50Cfg->cMat[3]=     0x291f;
   conv5x50Cfg->cMat[4]=     0x291f;
   conv5x50Cfg->cMat[5]=    0x291f;
   conv5x50Cfg->cMat[6]=     0x291f;
   conv5x50Cfg->cMat[7]=     0x291f;
   conv5x50Cfg->cMat[8]=     0x291f;
   conv5x50Cfg->cMat[9]=     0x291f;
   conv5x50Cfg->cMat[10]=   0x291f;
   conv5x50Cfg->cMat[11]=    0x291f;
   conv5x50Cfg->cMat[12]=    0x291f;
   conv5x50Cfg->cMat[13]=    0x291f;
   conv5x50Cfg->cMat[14]=    0x291f;
   conv5x50Cfg->cMat[15]=   0x291f;
   conv5x50Cfg->cMat[16]=    0x291f;
   conv5x50Cfg->cMat[17]=    0x291f;
   conv5x50Cfg->cMat[18]=    0x291f;
   conv5x50Cfg->cMat[19]=    0x291f;
   conv5x50Cfg->cMat[20]=   0x291f;
   conv5x50Cfg->cMat[21]=    0x291f;
   conv5x50Cfg->cMat[22]=    0x291f;
   conv5x50Cfg->cMat[23]=    0x291f;
   conv5x50Cfg->cMat[24]=    0x291f;
   dmaIn0Cfg->ddrAddr   = (UInt32)&SippTutA1Model_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&SippTutA1Model_dmaOut0_buffer;
  
  
}
