///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTA1MODEL_H__
#define __SIPPTUTA1MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>



//The full-frame buffers
extern UInt8 DDR_DATA SippTutA1Model_dmaIn0_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutA1Model_dmaOut0_buffer[ 512 * 512 * 1 ]ALIGNED(8);
	
///

typedef struct SippTutA1Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *conv5x50;
	SippFilter *dmaOut0;

} SippTutA1Model;

void readSippTutA1ModelInput(SippTutA1Model *pPl);
void writeSippTutA1ModelOutput(SippTutA1Model *pPl);

void buildSippTutA1Model(SippTutA1Model *pPl);
void configSippTutA1Model(SippTutA1Model *pPl);


#endif