///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __TESTHWCONV_H__
#define __TESTHWCONV_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "testHwConvSetup.h"


//The full-frame buffers
extern UInt8 DDR_DATA TestHwConv_dmaIn0_buffer[ SIPP_HW_CONV_BUFFER_WIDTH * SIPP_HW_CONV_BUFFER_HEIGHT * SIPP_HW_CONV_BUFFER_NUM_PLANES ]ALIGNED(8);
extern UInt8 DDR_DATA TestHwConv_dmaOut0_buffer[ SIPP_HW_CONV_BUFFER_WIDTH * SIPP_HW_CONV_BUFFER_HEIGHT * SIPP_HW_CONV_BUFFER_NUM_PLANES ]ALIGNED(8);
	
///

typedef struct TestHwConv
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut0;
	SippFilter *convolutionMa2x5x0;

} TestHwConv;

void readTestHwConvInput(TestHwConv *pPl);
void writeTestHwConvOutput(TestHwConv *pPl);

void buildTestHwConv(TestHwConv *pPl);
void configTestHwConv(TestHwConv *pPl);


#endif