/* mscatapi.h	Wed Jun 19 2013 18:04:50 chwon */

/*

Module:  mscatapi.h

Function:
	Atapi subclass protocl definitions, structures, and API

Version:
	V3.11b	Wed Jun 19 2013 18:04:50 chwon	Edit level 25

Copyright notice:
	This file copyright (C) 2001-2010, 2013 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	Chris Sawran, MCCI Corporation	July 2001

Revision history:
   1.00a  Fri Jul  6 2001 00:00:01  cds
	Module created.

   1.79b  7 Aug 2002  tmm
	Clean up formatting.

   1.79b  Fri Oct 18 2002 12:00:00  maw
   	Major overview during update for IOCTL-interface

   1.87a  Thu Nov 27 2003 10:25:00 maw
   	Comments updated

   1.87b  Tue Mar 16 2004 14:39:26  chwon
   	Fixed NO_MEDIA sense code.

   1.87b  Tue March 23 2004 14:45:00  maw
   	Merged changes in 1.86.1 into main branch:
   	- 1.86.1  Sun Nov 30 2003 00:37:08  tmm Comments updated.
   	- 1.87b  Tue March 23 2004 14:45:00 maw Added Load parameter to
   	                                        MscSubClassI_Atapi_EdgeLoadOrEject

   1.87b  Thu Mar 25 2004 15:08:02  chwon
	Bug 1234: Correct NO_MEDIA sense code; 0x02, 0x3a, 0x00 is correct.

   1.89b  Mon Aug 16 2004 14:31:24 maw
   	Bug 1246: Add Prevent-Allow-Media-Removal state variable in context block

   1.89b  Tue Aug 31 2004 13:38:02 maw
   	Bug 1299: Add fWriteProtect media property in context block,
   	          updated MscSubClassI_Atapi_SetCurrentMedium parameter list

   1.89b  Wed Sep 15 2004 14:45:23  maw
   	Divided UPROTO_MSCSUBCLASS_ATAPI structure into
   	UPROTO_MSCSUBCLASS_ATAPI and UPROTO_MSCSUBCLASS_ATAPI_LUN
   	Changed input parameter UPROTO_MSCSUBCLASS_ATAPI to
   	UPROTO_MSCSUBCLASS_ATAPI_LUN on several functions

   1.89b  Wed Oct 13 2004 11:59:48 maw
   	Removed LUN parameter from MscSubClassI_Atapi_EdgeResetDevice()

   1.93b  Wed Oct 26 2005 10:01:50  chwon
   	Added UPROTO_MSCSUBCLASS_ATAPI_SENSE_LUN_NOT_READY sense code.

   1.93b  Tue Nov 1 2005 14:45:23 ohjs
   	Added supporting TransparentMode Edge functions.
	MscSubClassI_Atapi_Edge_ClientCommand()
	MscSubClassI_Atapi_Edge_ClientSendDone()
	MscSubClassI_Atapi_Edge_ClientReceiveDone()

   1.97e  Sat Sep 02 2006 10:18:32  chwon
	Add data-in-stuff feature enable flag

   1.97k  Mon Jan 14 2008 09:51:14  ctpeng
	3577: Add CDROM related ATAPI commands.
	Generate unclaoked name using unclaok-defs.sh

   1.97k  Fri May 09 2008 11:33:37  chwon
	3735: reorganize UBUFQE to allow 32-bit sizes -- remove ual_pBuf,
	ual_nBuf, ual_ProcessedBytes.

   1.97k  Wed May 21 2008 11:49:54  chwon
	6099: add ua_fProcessCustomCommand and vendor command support function.

   1.97k  Wed Dec 10 2008 15:17:27  luxw
	7126: Add MscSubClassI_Atapi_CustomSendData, 
	MscSubClassI_Atapi_Edge_CustomSendDone,
	MscSubClassI_Atapi_CustomReceiveData and 
	MscSubClassI_Atapi_Edge_CustomReceiveDone

   2.01a  Mon Mar 09 2009 13:34:33  ctpeng
   	7119: Add the following 2 page codes for CDROM support:
   	UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_TIMEOUT_PROTECT_PAGE_CODE
	UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CAP_MECH_STATUS_PAGE_CODE
	
   2.01a  Wed Apr 08 2009 10:07:22 ctpeng	
	7119: Add the following functions, sense and mode page.
	MscSubClassI_Atapi_ProcessModeSelect
	MscSubClassI_Atapi_ProcessMechanismStatus
	MscSubClassI_Atapi_ProcessReadDiscInfo
	UPROTO_MSCSUBCLASS_ATAPI_SENSE_MEDIA_REMOVAL_PREVENTED   
	UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_PAGE_CODE

   2.01a  Wed Apr 22 2009 16:25:34 ctpeng	  
	7119: Modify parameters for MscSubClassI_Atapi_ProcessInquiry and
	add UPROTO_MSCSUBCLASS_ATAPI_SENSE_NO_MEDIA_TRAYOUT &
	UPROTO_MSCSUBCLASS_ATAPI_SENSE_NO_MEDIA_TRAYCLOSED.

   3.01c  Thu Sep 09 2010 11:00:35 ctpeng
     	11120: Add function MscSubClassI_Atapi_EdgeLoadOrEjectEx().	
	
   3.11b  Thu May 16 2013 13:43:53  chwon
	17202: Add ua_nLunEnabled in the UPROTO_MSCSUBCLASS_ATAPI.

   3.11b  Wed Jun 12 2013 16:14:17  chwon
	16739: 17346: Add event flags in the UPROTO_MSCSUBCLASS_ATAPI_LUN.

   3.11b  Wed Jun 19 2013 18:04:50  chwon
	17397: Add UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MODE_SENSE_6 code and
	add fModeSense10 parameter for MscSubClassI_Atapi_ProcessModeSense().

*/

#ifndef _MSCATAPI_H_			/* prevent multiple includes */
#define _MSCATAPI_H_

#ifndef _USBPROTOINIT_H_
# include "usbprotoinit.h"
#endif

#ifndef _USBIOCTL_STORAGE_H_
# include "usbioctl_storage.h"
#endif

#ifndef _PROTOMSC_H_
# include "protomsc.h"
#endif

/****************************************************************************\
|
|	Forward type declarations.
|
\****************************************************************************/

__TMS_TYPE_DEF_STRUCT(UPROTO_MSCSUBCLASS_ATAPI_LUN);
__TMS_TYPE_DEF_STRUCT(UPROTO_MSCSUBCLASS_ATAPI);
__TMS_TYPE_DEF_STRUCT(UPROTO_MSCSUBCLASS_ATAPI_LUN_CONFIG);
__TMS_TYPE_DEF_STRUCT(UPROTO_MSCSUBCLASS_ATAPI_CONFIG);
__TMS_TYPE_DEF(UPROTO_MSCSUBCLASS_ATAPI_SENSE, __TMS_UINT32);


/****************************************************************************\
|
|	ATAPI protocol Opcodes
|
\****************************************************************************/

/* all atapi op-codes as defined by the MMC-2 spec */
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_BLANK				0xA1
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_CLOSE_TRACK			0x5B
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_ERASE_10				0x2C
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_FORMAT_UNIT			0x04
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_GET_CONFIGURATION			0x46
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_GET_EVENT_STATUS_NOTIFICATION	0x4A
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_GET_PERFORMANCE			0xAC
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_INQUIRY				0x12
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_LOAD_UNLOAD_MEDIUM		0xA6
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MECHANISM_STATUS			0xBD
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MODE_SELECT_10			0x55
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MODE_SENSE_10			0x5A
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MODE_SENSE_6			0x1A
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PAUSE_RESUME			0x4B
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_AUDIO_10			0x45
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_AUDIO_12			0xA5
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_AUDIO_MSF			0x47
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_CD				0xBC
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PREVENT_ALLOW_MEDIUM_REMOVAL	0x1E
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_10				0x28
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_12				0xA8
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_BUFFER			0x3C
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_BUFFER_CAPACITY		0x5C
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_CD				0xBE
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_CD_MSF			0xB9
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_CAPACITY			0x25
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_DISC_INFORMATION		0x51
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_DVD_STRUCTURE		0xAD
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_FORMAT_CAPACITIES		0x23
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_HEADER			0x44
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_MASTER_CUE			0x59
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_SUB_CHANNEL			0x42
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_TOC				0x43
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_TRACK_INFORMATION		0x52
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_RELEASE_10			0x57
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_REPAIR_TRACK			0x58
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_REPORT_KEY			0xA4
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_REQUEST_SENSE			0x03
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_RESERVE_10			0x56
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_RESERVE_TRACK			0x53
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SCAN				0xBA
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEEK_10				0x2B
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_CUE_SHEET			0x5D
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_DVD_STRUCTURE		0xAD
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_EVENT			0xA2
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_KEY				0xA3
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_OPC_INFORMATION		0x54
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SET_CD_SPEED			0xBB
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SET_READ_AHEAD			0xA7
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SET_STREAMING			0xB6
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_START_STOP_UNIT			0x1B
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_STOP_PLAY_SCAN			0x4E
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SYNCHRONIZE_CACHE			0x35
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_TEST_UNIT_READY			0x00
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_VERIFY_10				0x2F
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_10				0x2A
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_12				0xAA
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_VERIFY			0x2E
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_BUFFER			0x3B


/****************************************************************************\
|
|	Sense codes
|
\***********************************************************************
||a convienient way to store sense-codes in a 32-bit value
|| Most error codes only require a Sense code and an Additional
|| Sense Code to relay all necessary info.  The Additional
|| Sense Code Qualifier allows for an extra bit of info to
|| describe the state of the device.  However, the Request
|| Sense command itself usually sends back a table of
|| 18 bytes.  Rather than store the whole table, just
|| store the 3 relevant bytes.
*/
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(Sense, Asc, Ascq)	\
		((__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE) (((Sense) << 16)|((Asc)<<8)|((Ascq))))
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_KEY(SenseCode)		\
		((__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE) (((SenseCode) >> 16) &0xff))
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ASC(SenseCode)		\
		((__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE) (((SenseCode) >> 8)  &0xff))
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ASCQ(SenseCode)		\
		((__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE)  ((SenseCode)        &0xff))

/*
|| here are some pre-defined Sense codes that can be used
|| by block devices.
*/
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_NONE		\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x00, 0x00, 0x00)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_LUN_NOT_READY	\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x02, 0x04, 0x00)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_NO_MEDIA		\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x02, 0x3A, 0x00)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_NO_MEDIA_TRAYCLOSED	\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x02, 0x3A, 0x01)	
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_NO_MEDIA_TRAYOUT	\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x02, 0x3A, 0x02)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_WRITE_ERROR	\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x03, 0x03, 0x00)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_READ_ERROR		\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x03, 0x11, 0x00)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_OPCODE	\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x05, 0x20, 0x00)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_ADDRESS	\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x05, 0x21, 0x00)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_CDB_FIELD	\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x05, 0x24, 0x00)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_BAD_LUN		\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x05, 0x25, 0x00)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_REQUEST	\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x05, 0x26, 0x00)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_MEDIA_REMOVAL_PREVENTED	\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x05, 0x53, 0x02)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_MEDIA_CHANGE	\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x06, 0x28, 0x00)
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_POR_DETECTED	\
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(0x06, 0x29, 0x00)


/****************************************************************************\
|
|	Mode page codes
|
\****************************************************************************/

/* mode pages */

/* Mode Page Sizes */
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_HEADER_SIZE				0x08
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_6_PAGE_HEADER_SIZE				0x04

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RW_ERR_RECOVERY_PAGE_CODE		0x01
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RW_ERR_RECOVERY_PAGE_SIZE		0x0a

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_DISCONNECT_RECONNECT_PAGE_CODE		0x02
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_DISCONNECT_RECONNECT_PAGE_SIZE		0x0e

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FORMAT_DEVICE_PAGE_CODE		0x03
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FORMAT_DEVICE_PAGE_SIZE		0x16

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RIGID_DISK_GEOMETRY_PAGE_CODE		0x04
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RIGID_DISK_GEOMETRY_PAGE_SIZE		0x16

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FLEXIBLE_DISK_PAGE_CODE		0x05
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FLEXIBLE_DISK_PAGE_SIZE		0x1e

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_VERIFY_ERROR_RECOVERY_PAGE_CODE	0x07
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_VERIFY_ERROR_RECOVERY_PAGE_SIZE	0x0a

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CACHING_PAGE_CODE			0x08
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CACHING_PAGE_SIZE			0x12

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CONTROL_PAGE_CODE			0x0a
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CONTROL_PAGE_SIZE			0x0a

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_MEDIUM_TYPES_SUPPORTED_PAGE_CODE	0x0b
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_MEDIUM_TYPES_SUPPORTED_PAGE_SIZE	0x06

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_NOTCH_AND_PARTITION_PAGE_CODE		0x0c
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_NOTCH_AND_PARTITION_PAGE_SIZE		0x16

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_0D_PAGE_CODE		0x0d
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_0D_PAGE_SIZE		0x0a

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_XOR_CONTROL_PAGE_CODE			0x10
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_XOR_CONTROL_PAGE_SIZE			0x16

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_PAGE_CODE		0x1a
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_PAGE_SIZE		0x0a

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_INFORMATIONAL_EXCEPTIONS_PAGE_CODE	0x1c
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_INFORMATIONAL_EXCEPTIONS_PAGE_SIZE	0x0a

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_TIMEOUT_PROTECT_PAGE_CODE		0x1D
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_TIMEOUT_PROTECT_PAGE_SIZE		0x08

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CAP_MECH_STATUS_PAGE_CODE		0x2A
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CAP_MECH_STATUS_PAGE_SIZE		0x18

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_MASK_PAGE				0x3f
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_ALL_PAGE_CODE				0x3f

#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_ALL_PAGE_SIZE	( \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_HEADER_SIZE				+ \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RW_ERR_RECOVERY_PAGE_SIZE		+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_DISCONNECT_RECONNECT_PAGE_SIZE		+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FORMAT_DEVICE_PAGE_SIZE		+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RIGID_DISK_GEOMETRY_PAGE_SIZE		+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FLEXIBLE_DISK_PAGE_SIZE		+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_VERIFY_ERROR_RECOVERY_PAGE_SIZE	+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CACHING_PAGE_SIZE			+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CONTROL_PAGE_SIZE			+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_MEDIUM_TYPES_SUPPORTED_PAGE_SIZE	+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_NOTCH_AND_PARTITION_PAGE_SIZE		+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_0D_PAGE_SIZE		+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_XOR_CONTROL_PAGE_SIZE			+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_INFORMATIONAL_EXCEPTIONS_PAGE_SIZE	+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_TIMEOUT_PROTECT_PAGE_SIZE		+ 2 + \
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CAP_MECH_STATUS_PAGE_SIZE		)


/****************************************************************************\
|
|	Inquiry attributes
|
\****************************************************************************/

/* inquiry attributes */
#define	__TMS_UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_DIRECT_ACCESS	0x00
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_SEQUENTIAL_ACCESS	0x01
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_WRITE_ONCE		0x04
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_CDROM		0x05

/* size of various string fields */
#define __TMS_UPROTO_MSCSUBCLASS_ATAPI_VENDOR_ID_LENGTH			8
#define	__TMS_UPROTO_MSCSUBCLASS_ATAPI_PRODUCT_ID_LENGTH		16
#define	__TMS_UPROTO_MSCSUBCLASS_ATAPI_VERSION_STRING_LENGTH		4


/****************************************************************************\
|
|	The instance data.
|
\****************************************************************************/


/* the protocol structure to maintain atapi-specific state information */
struct __TMS_STRUCTNAME(UPROTO_MSCSUBCLASS_ATAPI)
	{
	/*
	|| Each object begins with a header, inlcuding a tag and a size.
	*/
	__TMS_USBPUMP_OBJECT_HEADER		ua_Header;

	/*
	|| Each subclass instance can (normally) be opened by an OS-specific
	|| driver.  This is where we put the info about the client
	|| If the object pointer is NULL, then we have no client object.
	*/
	__TMS_USBPUMP_OBJECT_HEADER *		ua_pClientObject;
	__TMS_VOID *				ua_pClientContext;

	/*
	|| For convenience: a pointer to our parent UDEVICE and UINTERFACE
	*/
	__TMS_UDEVICE *				ua_pDevice;
	__TMS_UINTERFACE *			ua_pIfc;

	/* the mass storage class */
	__TMS_UPROTO_MSCBOT *			ua_pMsc;

	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	ua_pLun;	/* Array of LUN's */
	__TMS_BYTES				ua_nLun;
	__TMS_BYTES				ua_nLunEnabled;

	__TMS_BOOL				ua_fEnableDataInStuff;

	__TMS_BOOL	/* 6099 */		ua_fProcessCustomCommand;
	};

/* the protocol structure to maintain atapi-specific state information */
struct __TMS_STRUCTNAME(UPROTO_MSCSUBCLASS_ATAPI_LUN)
	{
	__TMS_UPROTO_MSCSUBCLASS_ATAPI *	ual_pAtapi;	/* Pointer back to parent */

	/*
	|| Here the storage device parameters are specified.
	*/
	__TMS_UINT8				ual_DeviceType;
	__TMS_BOOL				ual_fRemovableMedium;	/* is this device removable */

	/*
	|| Vendor, product and version strings
	*/
	__TMS_TEXT				ual_VendorId[__TMS_UPROTO_MSCSUBCLASS_ATAPI_VENDOR_ID_LENGTH];
	__TMS_TEXT				ual_ProductId[__TMS_UPROTO_MSCSUBCLASS_ATAPI_PRODUCT_ID_LENGTH];
	__TMS_TEXT				ual_Version[__TMS_UPROTO_MSCSUBCLASS_ATAPI_VERSION_STRING_LENGTH];

	/*
	|| Here the client media parameters are specified.
	*/
	__TMS_BOOL				ual_fPresent;		/* is this device present */
	__TMS_BYTES				ual_nLba;		/* number of LBA's on current media */
	__TMS_BYTES				ual_LbaSize;		/* size in bytes of each LBA */

	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE	ual_Status;		/* current status (sense) */
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE	ual_Error;		/* response to Request Sense, if arrives */
	__TMS_BYTES				ual_NextLba;		/* read/write state params */
	__TMS_BYTES				ual_LbaCount;		/* read/write state params */
	__TMS_BYTES				ual_nBytes;		/* expected number of bytes to read/write */

	__TMS_BOOL				ual_fPreventRemoval;	/* is removal prohibited */
	__TMS_BOOL				ual_fWriteProtected;

	__TMS_BOOL				ual_fEnableTransparentMode;

	__TMS_UINT				ual_fEventEjectRequest: 1;
	__TMS_UINT				ual_fEventNewMedia: 1;
	__TMS_UINT				ual_fEventMediaRemoval: 1;
	__TMS_UINT				ual_fEventMediaChanged: 1;
	};

#define	__TMS_UPROTO_MSCSUBCLASS_ATAPI_from_UPROTO_MSCBOTSUBCLASS(p) \
	((UPROTO_MSCSUBCLASS_ATAPI *) (&(p)->MscSubClassHdr))

/* this expands to something like UHIL_MEMTAG('M', 's', 'A', 'T') */
#define	__TMS_UPROTO_MSCSUBCLASS_ATAPI_TAG	UPROTO_MSCBOTSUBCLASS_TAG('A', 'T')

/* this expands to something like storage.atapi.bot.msc.fn.mcci.com */
/* remember, you'll normally match on "storage.*.fn.mcci.com", or even "storage.*.fn.*" */
#define	__TMS_UPROTO_MSCSUBCLASS_ATAPI_NAME	UPROTO_MSCBOTSUBCLASS_NAME("atapi")


/****************************************************************************\
|
|	Function Declarations
|
\****************************************************************************/

__TMS_BEGIN_DECLS

__TMS_USBPUMP_PROTOCOL_CREATE_FN MscSubClass_Atapi_ProtocolCreate;

__TMS_BOOL
MscSubClass_Atapi_Attach(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI *,
	__TMS_UDEVICE *,
	__TMS_UINTERFACE *,
	__TMS_CONST __TMS_UPROTO_MSCSUBCLASS_ATAPI_CONFIG *
	);

/*
|| ATAPI Opcode Command Processing Routines.
*/
__TMS_VOID
MscSubClassI_Atapi_ProcessInquiry(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT8 				EVPD,
	__TMS_UINT8 				PageCode,	
	__TMS_UINT16 				AllocationLength
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessModeSense(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT8				Control,
	__TMS_UINT8				Page,
	__TMS_UINT16				AllocationLength,
	__TMS_BOOL				fModeSense10
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessModeSelect(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT8				PfSp,
	__TMS_UINT16				AllocationLength
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessRead(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_BYTES 				Lba,
	__TMS_BYTES 				LbaCount
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessReadCapacity(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessRequestSense(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT8				 AllocationLength
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessTestUnitReady(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessUnsupported(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessVerify(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT8 				Flags,
	__TMS_BYTES 				Lba,
	__TMS_BYTES 				LbaCount
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessWrite(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_BYTES 				Lba,
	__TMS_BYTES 				LbaCount
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessFormatUnit(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessPreventAllowMediumRemoval(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT8 				PreventCode
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessStartStopUnit(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT8 				immed,
	__TMS_UINT8 				flags
	);

__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE
MscSubClassI_Atapi_Sense(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI *,
	__TMS_USBPUMP_STORAGE_STATUS		Status
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessReadTOC(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,	
	__TMS_UINT8				MSF,
	__TMS_UINT8				Format,
	__TMS_UINT8				TrackNumber,
	__TMS_UINT16				AllocationLength
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessGetConfiguration(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT8				RT,
	__TMS_UINT16				StartingFeatureNumber,
	__TMS_UINT16				AllocationLength
	);

__TMS_VOID
MscSubClassI_Atapi_ProcessGetEventStatusNotification(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT8				IMMED,
	__TMS_UINT8				ClassRequest,
	__TMS_UINT16				AllocationLength
	);

__TMS_VOID 
MscSubClassI_Atapi_ProcessMechanismStatus(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT16				AllocationLength
	);

__TMS_VOID 
MscSubClassI_Atapi_ProcessReadDiscInfo(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT16				AllocationLength
	);

/*
|| Edge interface functions
*/
__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE
MscSubClassI_Atapi_EdgeGetStatus(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *
	);

__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE
MscSubClassI_Atapi_EdgeLoadOrEject(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_BOOL
	);

__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE
MscSubClassI_Atapi_EdgeLoadOrEjectEx(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_UINT8,
	__TMS_BOOL,
	__TMS_BOOL,
	__TMS_BOOL,
	__TMS_BOOL *
	);

__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE
MscSubClassI_Atapi_EdgePreventRemoval(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_BOOL
	);

__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE
MscSubClassI_Atapi_EdgeResetDevice(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI *
	);

__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE
MscSubClassI_Atapi_EdgeRead(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_BYTES				Lba,
	__TMS_BYTES				LbaCount
	);

__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE
MscSubClassI_Atapi_EdgeReadDone(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_VOID *				pBuf,
	__TMS_BYTES				nBytes
	);

__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE
MscSubClassI_Atapi_EdgeWrite(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_BYTES				Lba,
	__TMS_BYTES				LbaCount
	);

__TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE
MscSubClassI_Atapi_EdgeWriteData(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_VOID *				pBuf,
	__TMS_BYTES				nBytes
	);

__TMS_BOOL
MscSubClassI_Atapi_Edge_ClientCommand(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_VOID *				pCbwBuf,
	__TMS_BYTES				nCbwBuf
	);

__TMS_BOOL
MscSubClassI_Atapi_Edge_ClientSendDone(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_VOID *				pBuf,
	__TMS_BYTES				nBuf
	);

__TMS_BOOL
MscSubClassI_Atapi_Edge_ClientReceiveDone(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_VOID *				pBuf,
	__TMS_BYTES				nBuf
	);

__TMS_BOOL
MscSubClassI_Atapi_Edge_CustomCommand(		/* 6099 */
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_VOID *				pCbwcbBuffer,
	__TMS_BYTES				nCbwcbBuffer
	);

/*
|| the IOCTL function we export
*/
__TMS_USBPUMP_OBJECT_IOCTL_FN		MscSubClassI_Atapi_Ioctl;

/*
|| IOCTL handlers
*/
__TMS_USBPUMP_IOCTL_RESULT MscSubClassI_Atapi_QueueReadData(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_VOID *,
	__TMS_BYTES
	);

__TMS_USBPUMP_IOCTL_RESULT MscSubClassI_Atapi_QueueWriteData(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_VOID *,
	__TMS_BYTES
	);

__TMS_VOID MscSubClassI_Atapi_WriteDone(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *,
	__TMS_USBPUMP_STORAGE_STATUS
	);

__TMS_VOID MscSubClassI_Atapi_SetCurrentMedium(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_BOOL				fPresent,
	__TMS_BOOL				fWriteProtected,
	__TMS_BYTES				nLba,
	__TMS_BYTES				LbaSize
	);

__TMS_VOID MscSubClassI_Atapi_SetDeviceProperties(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_USBPUMP_STORAGE_DEVICE_TYPE	DeviceType,
	__TMS_BOOL				fRemovable,
	__TMS_CONST __TMS_TEXT *		pVendorId,
	__TMS_CONST __TMS_TEXT *		pProductId,
	__TMS_CONST __TMS_TEXT *		pVersion
	);

__TMS_BOOL MscSubClassI_Atapi_ClientSetMode(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_BOOL				fEnableTransparentMode
	);

__TMS_USBPUMP_IOCTL_RESULT MscSubClassI_Atapi_ClientSendData(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_VOID *				pBuf,
	__TMS_BYTES				nBuf
	);

__TMS_USBPUMP_IOCTL_RESULT MscSubClassI_Atapi_ClientReceiveData(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_VOID *				pBuf,
	__TMS_BYTES				nBuf
	);

__TMS_USBPUMP_IOCTL_RESULT MscSubClassI_Atapi_ClientSendStatus(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_UINT8				CswStatus,
	__TMS_USBPUMP_STORAGE_STATUS		StorageStatus
	);

__TMS_USBPUMP_IOCTL_RESULT MscSubClassI_Atapi_ClientGetInquiryData(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_VOID *				pBuf,
	__TMS_BYTES				nBuf,
	__TMS_BYTES*				pWriteCount
	);

__TMS_USBPUMP_IOCTL_RESULT
MscSubClassI_Atapi_CustomSendStatus(		/* 6099 */
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_UINT8				bCswStatus,
	__TMS_USBPUMP_STORAGE_STATUS		StorageStatus
	);

__TMS_USBPUMP_IOCTL_RESULT 
MscSubClassI_Atapi_CustomSendData(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_VOID *				pBuf,
	__TMS_BYTES				nBuf
	);
	
__TMS_BOOL
MscSubClassI_Atapi_Edge_CustomSendDone(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_VOID *				pBuf,
	__TMS_BYTES				nBuf
	);

__TMS_USBPUMP_IOCTL_RESULT 
MscSubClassI_Atapi_CustomReceiveData(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_VOID *				pBuf,
	__TMS_BYTES				nBuf
	);

__TMS_BOOL
MscSubClassI_Atapi_Edge_CustomReceiveDone(
	__TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun,
	__TMS_VOID *				pBuf,
	__TMS_BYTES				nBuf
	);
			
__TMS_UINT8 **
MscSubClassI_Atapi_GetModePage(
    __TMS_UPROTO_MSCSUBCLASS_ATAPI_LUN *	pLun
    );
			
__TMS_END_DECLS


/****************************************************************************\
|
|	Uncloaked Names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_BLANK	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_BLANK
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_CLOSE_TRACK	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_CLOSE_TRACK
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_ERASE_10	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_ERASE_10
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_FORMAT_UNIT	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_FORMAT_UNIT
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_GET_CONFIGURATION	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_GET_CONFIGURATION
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_GET_EVENT_STATUS_NOTIFICATION	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_GET_EVENT_STATUS_NOTIFICATION
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_GET_PERFORMANCE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_GET_PERFORMANCE
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_INQUIRY	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_INQUIRY
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_LOAD_UNLOAD_MEDIUM	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_LOAD_UNLOAD_MEDIUM
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MECHANISM_STATUS	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MECHANISM_STATUS
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MODE_SELECT_10	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MODE_SELECT_10
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MODE_SENSE_10	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MODE_SENSE_10
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MODE_SENSE_6	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_MODE_SENSE_6
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PAUSE_RESUME	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PAUSE_RESUME
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_AUDIO_10	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_AUDIO_10
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_AUDIO_12	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_AUDIO_12
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_AUDIO_MSF	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_AUDIO_MSF
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_CD	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PLAY_CD
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PREVENT_ALLOW_MEDIUM_REMOVAL	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_PREVENT_ALLOW_MEDIUM_REMOVAL
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_10	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_10
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_12	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_12
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_BUFFER	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_BUFFER
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_BUFFER_CAPACITY	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_BUFFER_CAPACITY
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_CD	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_CD
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_CD_MSF	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_CD_MSF
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_CAPACITY	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_CAPACITY
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_DISC_INFORMATION	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_DISC_INFORMATION
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_DVD_STRUCTURE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_DVD_STRUCTURE
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_FORMAT_CAPACITIES	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_FORMAT_CAPACITIES
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_HEADER	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_HEADER
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_MASTER_CUE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_MASTER_CUE
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_SUB_CHANNEL	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_SUB_CHANNEL
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_TOC	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_TOC
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_TRACK_INFORMATION	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_READ_TRACK_INFORMATION
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_RELEASE_10	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_RELEASE_10
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_REPAIR_TRACK	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_REPAIR_TRACK
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_REPORT_KEY	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_REPORT_KEY
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_REQUEST_SENSE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_REQUEST_SENSE
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_RESERVE_10	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_RESERVE_10
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_RESERVE_TRACK	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_RESERVE_TRACK
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SCAN	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SCAN
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEEK_10	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEEK_10
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_CUE_SHEET	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_CUE_SHEET
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_DVD_STRUCTURE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_DVD_STRUCTURE
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_EVENT	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_EVENT
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_KEY	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_KEY
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_OPC_INFORMATION	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SEND_OPC_INFORMATION
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SET_CD_SPEED	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SET_CD_SPEED
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SET_READ_AHEAD	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SET_READ_AHEAD
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SET_STREAMING	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SET_STREAMING
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_START_STOP_UNIT	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_START_STOP_UNIT
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_STOP_PLAY_SCAN	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_STOP_PLAY_SCAN
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SYNCHRONIZE_CACHE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_SYNCHRONIZE_CACHE
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_TEST_UNIT_READY	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_TEST_UNIT_READY
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_VERIFY_10	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_VERIFY_10
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_10	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_10
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_12	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_12
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_VERIFY	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_VERIFY
# define UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_BUFFER	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_OPCODE_WRITE_BUFFER
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(Sense, Asc, Ascq)	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_CODE(Sense, Asc, Ascq)
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_KEY(SenseCode)	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_KEY(SenseCode)
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_ASC(SenseCode)	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ASC(SenseCode)
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_ASCQ(SenseCode)	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ASCQ(SenseCode)
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_NONE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_NONE
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_LUN_NOT_READY	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_LUN_NOT_READY
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_NO_MEDIA	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_NO_MEDIA
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_NO_MEDIA_TRAYCLOSED	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_NO_MEDIA_TRAYCLOSED
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_NO_MEDIA_TRAYOUT	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_NO_MEDIA_TRAYOUT
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_WRITE_ERROR	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_WRITE_ERROR
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_READ_ERROR	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_READ_ERROR
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_OPCODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_OPCODE
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_ADDRESS	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_ADDRESS
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_CDB_FIELD	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_CDB_FIELD
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_BAD_LUN	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_BAD_LUN
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_REQUEST	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_ILLEGAL_REQUEST
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_MEDIA_REMOVAL_PREVENTED	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_MEDIA_REMOVAL_PREVENTED
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_MEDIA_CHANGE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_MEDIA_CHANGE
# define UPROTO_MSCSUBCLASS_ATAPI_SENSE_POR_DETECTED	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_SENSE_POR_DETECTED
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_HEADER_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_HEADER_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_6_PAGE_HEADER_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_6_PAGE_HEADER_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RW_ERR_RECOVERY_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RW_ERR_RECOVERY_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RW_ERR_RECOVERY_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RW_ERR_RECOVERY_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_DISCONNECT_RECONNECT_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_DISCONNECT_RECONNECT_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_DISCONNECT_RECONNECT_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_DISCONNECT_RECONNECT_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FORMAT_DEVICE_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FORMAT_DEVICE_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FORMAT_DEVICE_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FORMAT_DEVICE_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RIGID_DISK_GEOMETRY_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RIGID_DISK_GEOMETRY_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RIGID_DISK_GEOMETRY_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_RIGID_DISK_GEOMETRY_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FLEXIBLE_DISK_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FLEXIBLE_DISK_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FLEXIBLE_DISK_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_FLEXIBLE_DISK_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_VERIFY_ERROR_RECOVERY_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_VERIFY_ERROR_RECOVERY_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_VERIFY_ERROR_RECOVERY_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_VERIFY_ERROR_RECOVERY_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CACHING_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CACHING_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CACHING_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CACHING_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CONTROL_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CONTROL_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CONTROL_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CONTROL_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_MEDIUM_TYPES_SUPPORTED_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_MEDIUM_TYPES_SUPPORTED_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_MEDIUM_TYPES_SUPPORTED_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_MEDIUM_TYPES_SUPPORTED_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_NOTCH_AND_PARTITION_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_NOTCH_AND_PARTITION_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_NOTCH_AND_PARTITION_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_NOTCH_AND_PARTITION_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_0D_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_0D_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_0D_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_0D_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_XOR_CONTROL_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_XOR_CONTROL_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_XOR_CONTROL_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_XOR_CONTROL_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_POWER_CONDITION_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_INFORMATIONAL_EXCEPTIONS_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_INFORMATIONAL_EXCEPTIONS_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_INFORMATIONAL_EXCEPTIONS_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_INFORMATIONAL_EXCEPTIONS_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_TIMEOUT_PROTECT_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_TIMEOUT_PROTECT_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_TIMEOUT_PROTECT_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_TIMEOUT_PROTECT_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CAP_MECH_STATUS_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CAP_MECH_STATUS_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CAP_MECH_STATUS_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_CAP_MECH_STATUS_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_MASK_PAGE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_PAGE_MASK_PAGE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_ALL_PAGE_CODE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_ALL_PAGE_CODE
# define UPROTO_MSCSUBCLASS_ATAPI_MODE_ALL_PAGE_SIZE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_MODE_ALL_PAGE_SIZE
# define UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_DIRECT_ACCESS	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_DIRECT_ACCESS
# define UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_SEQUENTIAL_ACCESS	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_SEQUENTIAL_ACCESS
# define UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_WRITE_ONCE	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_WRITE_ONCE
# define UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_CDROM	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_DEVICE_TYPE_CDROM
# define UPROTO_MSCSUBCLASS_ATAPI_VENDOR_ID_LENGTH	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_VENDOR_ID_LENGTH
# define UPROTO_MSCSUBCLASS_ATAPI_PRODUCT_ID_LENGTH	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_PRODUCT_ID_LENGTH
# define UPROTO_MSCSUBCLASS_ATAPI_VERSION_STRING_LENGTH	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_VERSION_STRING_LENGTH
# define UPROTO_MSCSUBCLASS_ATAPI_from_UPROTO_MSCBOTSUBCLASS(p)	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_from_UPROTO_MSCBOTSUBCLASS(p)
# define UPROTO_MSCSUBCLASS_ATAPI_TAG	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_TAG
# define UPROTO_MSCSUBCLASS_ATAPI_NAME	\
   __TMS_UPROTO_MSCSUBCLASS_ATAPI_NAME
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of mscatapi.h ****/
#endif /* _MSCATAPI_H_ */
