/* usbpump_usbdi_class_msd_config.h	Wed Mar 22 2017 10:52:31 chwon */

/*

Module:  usbpump_usbdi_class_msd_config.h

Function:
	Definition of the USBDI Msd driver configuration

Version:
	V3.19b	Wed Mar 22 2017 10:52:31 chwon	Edit level 3

Copyright notice:
	This file copyright (C) 2013, 2017 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	ChaeHee Won, MCCI Corporation	August 2013

Revision history:
   3.11d  Thu Aug 15 2013 11:43:17 chwon
	9010: Module created.

   3.13b  Mon Oct 06 2014 10:01:52  chwon
	18568: Fix typo -- gk_UsbPumpUsbdiClassMsd_ConfigDefault.

   3.19b  Wed Mar 22 2017 10:52:31  chwon
	20428: 20503: Add request timeout and fDoNotSendTurIfNotRemovable
	in the MSD config.

*/

#ifndef _USBPUMP_USBDI_CLASS_MSD_CONFIG_H_	/* prevent multiple includes */
#define _USBPUMP_USBDI_CLASS_MSD_CONFIG_H_

#ifndef _USBPUMP_USBDI_CLASS_MSD_TYPES_H_
# include "usbpump_usbdi_class_msd_types.h"
#endif

/****************************************************************************\
|
|	The USBDI Msd Class Driver Configuration
|
\****************************************************************************/

struct __TMS_STRUCTNAME(USBPUMP_USBDI_CLASS_MSD_CONFIG)
	{
	__TMS_UINT32			MagicBegin;

	/*
	|| Number of maximum sessions -- it should include OpenSession and
	|| OpenFunction session.
	*/
	__TMS_UINT			MaxSession;
	__TMS_UINT16			DeviceRequestTimeout;
	__TMS_UINT16			MscBotRequestTimeout;
	__TMS_BOOL			fDoNotSendTurIfNotRemovable;

	__TMS_UINT32			MagicEnd;
	};


#ifndef	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_DEVICE_REQUEST_TIMEOUT /* PARAM */
# define __TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_DEVICE_REQUEST_TIMEOUT	(5000)
#endif

#ifndef	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MSCBOT_REQUEST_TIMEOUT /* PARAM */
# define __TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MSCBOT_REQUEST_TIMEOUT	(5000)
#endif

#define	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MAGIC_BEGIN		\
	__TMS_UHIL_MEMTAG('<', 'm', 's', 'd')

#define	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MAGIC_END			\
	__TMS_UHIL_MEMTAG('>', 'm', 's', 'd')

#define	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_INIT_V2(			\
	a_MaxSession,							\
	a_DeviceRequestTimeout,						\
	a_MscBotRequestTimeout,						\
	a_fDoNotSendTurIfNotRemovable					\
	)								\
	{								\
	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MAGIC_BEGIN,		\
	(a_MaxSession),							\
	(a_DeviceRequestTimeout),					\
	(a_MscBotRequestTimeout),					\
	(a_fDoNotSendTurIfNotRemovable),				\
	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MAGIC_END			\
	}

#define	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_INIT_V1(			\
	a_MaxSession							\
	)								\
	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_INIT_V2(			\
	a_MaxSession,							\
	/* V2: DeviceRequestTimeout */					\
	    __TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_DEVICE_REQUEST_TIMEOUT,\
	/* V2: MscBotRequestTimeout */					\
	    __TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MSCBOT_REQUEST_TIMEOUT,\
	/* V2: fDoNotSendTurIfNotRemovable */ __TMS_FALSE		\
	)

#define	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_SETUP_V2(			\
	a_pConfig,							\
	a_MaxSession,							\
	a_DeviceRequestTimeout,						\
	a_MscBotRequestTimeout,						\
	a_fDoNotSendTurIfNotRemovable					\
	)								\
    do	{								\
	(a_pConfig)->MagicBegin =					\
		__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MAGIC_BEGIN;	\
	(a_pConfig)->MaxSession = a_MaxSession;				\
	(a_pConfig)->DeviceRequestTimeout = a_DeviceRequestTimeout;	\
	(a_pConfig)->MscBotRequestTimeout = a_MscBotRequestTimeout;	\
	(a_pConfig)->fDoNotSendTurIfNotRemovable =			\
		a_fDoNotSendTurIfNotRemovable;				\
	(a_pConfig)->MagicEnd =						\
		__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MAGIC_END;		\
	} while (0)

#define	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_SETUP_V1(			\
	a_pConfig,							\
	a_MaxSession							\
	)								\
	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_SETUP_V2(			\
	a_pConfig,							\
	a_MaxSession,							\
	/* V2: DeviceRequestTimeout */					\
	    __TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_DEVICE_REQUEST_TIMEOUT,\
	/* V2: MscBotRequestTimeout */					\
	    __TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MSCBOT_REQUEST_TIMEOUT,\
	/* V2: fDoNotSendTurIfNotRemovable */ __TMS_FALSE		\
	)


/****************************************************************************\
|
|	Default linkage
|
\****************************************************************************/

__TMS_BEGIN_DECLS

extern __TMS_CONST __TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG
gk_UsbPumpUsbdiClassMsd_ConfigDefault;

__TMS_END_DECLS


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_USBDI_CLASS_MSD_CONFIG_DEVICE_REQUEST_TIMEOUT	\
   __TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_DEVICE_REQUEST_TIMEOUT
# define USBPUMP_USBDI_CLASS_MSD_CONFIG_MSCBOT_REQUEST_TIMEOUT	\
   __TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MSCBOT_REQUEST_TIMEOUT
# define USBPUMP_USBDI_CLASS_MSD_CONFIG_MAGIC_BEGIN	\
   __TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MAGIC_BEGIN
# define USBPUMP_USBDI_CLASS_MSD_CONFIG_MAGIC_END	\
   __TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_MAGIC_END
# define USBPUMP_USBDI_CLASS_MSD_CONFIG_INIT_V2(			\
	a_MaxSession,							\
	a_DeviceRequestTimeout,						\
	a_MscBotRequestTimeout,						\
	a_fDoNotSendTurIfNotRemovable					\
	)	\
	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_INIT_V2(			\
	a_MaxSession,							\
	a_DeviceRequestTimeout,						\
	a_MscBotRequestTimeout,						\
	a_fDoNotSendTurIfNotRemovable					\
	)
# define USBPUMP_USBDI_CLASS_MSD_CONFIG_INIT_V1(			\
	a_MaxSession							\
	)	\
	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_INIT_V1(			\
	a_MaxSession							\
	)
# define USBPUMP_USBDI_CLASS_MSD_CONFIG_SETUP_V2(			\
	a_pConfig,							\
	a_MaxSession,							\
	a_DeviceRequestTimeout,						\
	a_MscBotRequestTimeout,						\
	a_fDoNotSendTurIfNotRemovable					\
	)	\
	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_SETUP_V2(			\
	a_pConfig,							\
	a_MaxSession,							\
	a_DeviceRequestTimeout,						\
	a_MscBotRequestTimeout,						\
	a_fDoNotSendTurIfNotRemovable					\
	)
# define USBPUMP_USBDI_CLASS_MSD_CONFIG_SETUP_V1(			\
	a_pConfig,							\
	a_MaxSession							\
	)	\
	__TMS_USBPUMP_USBDI_CLASS_MSD_CONFIG_SETUP_V1(			\
	a_pConfig,							\
	a_MaxSession							\
	)
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpump_usbdi_class_msd_config.h ****/
#endif /* _USBPUMP_USBDI_CLASS_MSD_CONFIG_H_ */
