/* =============================================================================
* Copyright (c) 2013-2014 MM Solutions AD
* All rights reserved. Property of MM Solutions AD.
*
* This source code may not be used against the terms and conditions stipulated
* in the licensing agreement under which it has been supplied, or without the
* written permission of MM Solutions. Rights to use, copy, modify, and
* distribute or disclose this source code and its documentation are granted only
* through signed licensing agreement, provided that this copyright notice
* appears in all copies, modifications, and distributions and subject to the
* following conditions:
* THIS SOURCE CODE AND ACCOMPANYING DOCUMENTATION, IS PROVIDED AS IS, WITHOUT
* WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. MM SOLUTIONS SPECIFICALLY DISCLAIMS
* ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
* MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN
* NO EVENT SHALL MM SOLUTIONS BE LIABLE TO ANY PARTY FOR ANY CLAIM, DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
* PROFITS, OR OTHER LIABILITY, ARISING OUT OF THE USE OF OR IN CONNECTION WITH
* THIS SOURCE CODE AND ITS DOCUMENTATION.
* =========================================================================== */
/**
* @file camera3_metadata_struct.h
*
* @author ( MM Solutions AD )
*
*/
/* -----------------------------------------------------------------------------
*!
*! Revision History
*! ===================================
*! 05-Nov-2013 : Author ( MM Solutions AD )
*! Created
* =========================================================================== */

#ifndef _GUZZI_CAMERA3_METADATA_STRUCT_H
#define _GUZZI_CAMERA3_METADATA_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <osal/osal_stdtypes.h>

/*
 * ****************************************************************************
 * * controls
 * ****************************************************************************
 */
#define GUZZI_CAMERA3_CONTROLS_COLOR_CORRECTION_GAINS_DIM_MAX_SIZE_1 4
#define GUZZI_CAMERA3_CONTROLS_COLOR_CORRECTION_TRANSFORM_DIM_MAX_SIZE_1 3
#define GUZZI_CAMERA3_CONTROLS_COLOR_CORRECTION_TRANSFORM_DIM_MAX_SIZE_2 3
#define GUZZI_CAMERA3_CONTROLS_CONTROL_AE_REGIONS_DIM_MAX_SIZE_1 5
#define GUZZI_CAMERA3_CONTROLS_CONTROL_AE_REGIONS_DIM_MAX_SIZE_2 9 /* TODO: area_count */
#define GUZZI_CAMERA3_CONTROLS_CONTROL_AE_TARGET_FPS_RANGE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_CONTROLS_CONTROL_AF_REGIONS_DIM_MAX_SIZE_1 5
#define GUZZI_CAMERA3_CONTROLS_CONTROL_AF_REGIONS_DIM_MAX_SIZE_2 9 /* TODO: area_count */
#define GUZZI_CAMERA3_CONTROLS_CONTROL_AWB_REGIONS_DIM_MAX_SIZE_1 5
#define GUZZI_CAMERA3_CONTROLS_CONTROL_AWB_REGIONS_DIM_MAX_SIZE_2 9 /* TODO: area_count */
#define GUZZI_CAMERA3_CONTROLS_JPEG_GPS_COORDINATES_DIM_MAX_SIZE_1 3
#define GUZZI_CAMERA3_CONTROLS_JPEG_THUMBNAIL_SIZE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_CONTROLS_REQUEST_INPUT_STREAMS_DIM_MAX_SIZE_1 1 /* TODO: n */
#define GUZZI_CAMERA3_CONTROLS_REQUEST_OUTPUT_STREAMS_DIM_MAX_SIZE_1 4 /* TODO: n */
#define GUZZI_CAMERA3_CONTROLS_SCALER_CROP_REGION_DIM_MAX_SIZE_1 4
#define GUZZI_CAMERA3_CONTROLS_TONEMAP_CURVE_BLUE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_CONTROLS_TONEMAP_CURVE_BLUE_DIM_MAX_SIZE_2 128 /* TODO: n */
#define GUZZI_CAMERA3_CONTROLS_TONEMAP_CURVE_GREEN_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_CONTROLS_TONEMAP_CURVE_GREEN_DIM_MAX_SIZE_2 128 /* TODO: n */
#define GUZZI_CAMERA3_CONTROLS_TONEMAP_CURVE_RED_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_CONTROLS_TONEMAP_CURVE_RED_DIM_MAX_SIZE_2 128 /* TODO: n */

/*
 * ****************************************************************************
 * * dynamic
 * ****************************************************************************
 */
#define GUZZI_CAMERA3_DYNAMIC_COLOR_CORRECTION_GAINS_DIM_MAX_SIZE_1 4
#define GUZZI_CAMERA3_DYNAMIC_COLOR_CORRECTION_TRANSFORM_DIM_MAX_SIZE_1 3
#define GUZZI_CAMERA3_DYNAMIC_COLOR_CORRECTION_TRANSFORM_DIM_MAX_SIZE_2 3
#define GUZZI_CAMERA3_DYNAMIC_CONTROL_AE_REGIONS_DIM_MAX_SIZE_1 5
#define GUZZI_CAMERA3_DYNAMIC_CONTROL_AE_REGIONS_DIM_MAX_SIZE_2 9 /* TODO: area_count */
#define GUZZI_CAMERA3_DYNAMIC_CONTROL_AF_REGIONS_DIM_MAX_SIZE_1 5
#define GUZZI_CAMERA3_DYNAMIC_CONTROL_AF_REGIONS_DIM_MAX_SIZE_2 9 /* TODO: area_count */
#define GUZZI_CAMERA3_DYNAMIC_CONTROL_AWB_REGIONS_DIM_MAX_SIZE_1 5
#define GUZZI_CAMERA3_DYNAMIC_CONTROL_AWB_REGIONS_DIM_MAX_SIZE_2 9 /* TODO: area_count */
#define GUZZI_CAMERA3_DYNAMIC_JPEG_GPS_COORDINATES_DIM_MAX_SIZE_1 3
#define GUZZI_CAMERA3_DYNAMIC_JPEG_THUMBNAIL_SIZE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_DYNAMIC_LENS_FOCUS_RANGE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_DYNAMIC_REQUEST_OUTPUT_STREAMS_DIM_MAX_SIZE_1 4 /* TODO: n */
#define GUZZI_CAMERA3_DYNAMIC_SCALER_CROP_REGION_DIM_MAX_SIZE_1 4
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_FACE_IDS_DIM_MAX_SIZE_1 10 /* TODO: n */
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_FACE_LANDMARKS_DIM_MAX_SIZE_1 6
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_FACE_LANDMARKS_DIM_MAX_SIZE_2 10 /* TODO: n */
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_FACE_RECTANGLES_DIM_MAX_SIZE_1 4
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_FACE_RECTANGLES_DIM_MAX_SIZE_2 10 /* TODO: n */
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_FACE_SCORES_DIM_MAX_SIZE_1 10 /* TODO: n */
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_HISTOGRAM_DIM_MAX_SIZE_1 3
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_HISTOGRAM_DIM_MAX_SIZE_2 64 /* TODO: n */
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_LENS_SHADING_MAP_DIM_MAX_SIZE_1 4
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_LENS_SHADING_MAP_DIM_MAX_SIZE_2 64 /* TODO: m */
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_LENS_SHADING_MAP_DIM_MAX_SIZE_3 64 /* TODO: n */
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_PREDICTED_COLOR_GAINS_DIM_MAX_SIZE_1 4
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_PREDICTED_COLOR_TRANSFORM_DIM_MAX_SIZE_1 3
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_PREDICTED_COLOR_TRANSFORM_DIM_MAX_SIZE_2 3
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_SHARPNESS_MAP_DIM_MAX_SIZE_1 3
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_SHARPNESS_MAP_DIM_MAX_SIZE_2 32 /* TODO: m */
#define GUZZI_CAMERA3_DYNAMIC_STATISTICS_SHARPNESS_MAP_DIM_MAX_SIZE_3 32 /* TODO: n */
#define GUZZI_CAMERA3_DYNAMIC_TONEMAP_CURVE_BLUE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_DYNAMIC_TONEMAP_CURVE_BLUE_DIM_MAX_SIZE_2 128 /* TODO: n */
#define GUZZI_CAMERA3_DYNAMIC_TONEMAP_CURVE_GREEN_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_DYNAMIC_TONEMAP_CURVE_GREEN_DIM_MAX_SIZE_2 128 /* TODO: n */
#define GUZZI_CAMERA3_DYNAMIC_TONEMAP_CURVE_RED_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_DYNAMIC_TONEMAP_CURVE_RED_DIM_MAX_SIZE_2 128 /* TODO: n */

/*
 * ****************************************************************************
 * * static
 * ****************************************************************************
 */
#define GUZZI_CAMERA3_STATIC_CONTROL_AE_AVAILABLE_ANTIBANDING_MODES_DIM_MAX_SIZE_1 4 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_CONTROL_AE_AVAILABLE_MODES_DIM_MAX_SIZE_1 5 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES_DIM_MAX_SIZE_2 5 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_CONTROL_AE_COMPENSATION_RANGE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_CONTROL_AF_AVAILABLE_MODES_DIM_MAX_SIZE_1 6 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_CONTROL_AVAILABLE_EFFECTS_DIM_MAX_SIZE_1 9 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_CONTROL_AVAILABLE_SCENE_MODES_DIM_MAX_SIZE_1 17 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_CONTROL_AVAILABLE_VIDEO_STABILIZATION_MODES_DIM_MAX_SIZE_1 2 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_CONTROL_AWB_AVAILABLE_MODES_DIM_MAX_SIZE_1 9 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_CONTROL_SCENE_MODE_OVERRIDES_DIM_MAX_SIZE_1 3
#define GUZZI_CAMERA3_STATIC_CONTROL_SCENE_MODE_OVERRIDES_DIM_MAX_SIZE_2 17 /* TODO: length(availableSceneModes) */
#define GUZZI_CAMERA3_STATIC_HOT_PIXEL_INFO_MAP_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_HOT_PIXEL_INFO_MAP_DIM_MAX_SIZE_2 30 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_JPEG_AVAILABLE_THUMBNAIL_SIZES_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_JPEG_AVAILABLE_THUMBNAIL_SIZES_DIM_MAX_SIZE_2 5 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_LED_AVAILABLE_LEDS_DIM_MAX_SIZE_1 3 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_LENS_INFO_AVAILABLE_APERTURES_DIM_MAX_SIZE_1 3 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_LENS_INFO_AVAILABLE_FILTER_DENSITIES_DIM_MAX_SIZE_1 3 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_LENS_INFO_AVAILABLE_FOCAL_LENGTHS_DIM_MAX_SIZE_1 3 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_LENS_INFO_AVAILABLE_OPTICAL_STABILIZATION_DIM_MAX_SIZE_1 2 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_LENS_INFO_GEOMETRIC_CORRECTION_MAP_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_LENS_INFO_GEOMETRIC_CORRECTION_MAP_DIM_MAX_SIZE_2 3
#define GUZZI_CAMERA3_STATIC_LENS_INFO_GEOMETRIC_CORRECTION_MAP_DIM_MAX_SIZE_3 12 /* TODO: m */
#define GUZZI_CAMERA3_STATIC_LENS_INFO_GEOMETRIC_CORRECTION_MAP_DIM_MAX_SIZE_4 9 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_LENS_INFO_GEOMETRIC_CORRECTION_MAP_SIZE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_LENS_INFO_SHADING_MAP_SIZE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_LENS_OPTICAL_AXIS_ANGLE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_LENS_POSITION_DIM_MAX_SIZE_1 3 /* TODO: 3, location in mm, in the sensor coordinate
            system */
#define GUZZI_CAMERA3_STATIC_REQUEST_MAX_NUM_OUTPUT_STREAMS_DIM_MAX_SIZE_1 3
#define GUZZI_CAMERA3_STATIC_REQUEST_MAX_NUM_REPROCESS_STREAMS_DIM_MAX_SIZE_1 1
#define GUZZI_CAMERA3_STATIC_SCALER_AVAILABLE_FORMATS_DIM_MAX_SIZE_1 7 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_SCALER_AVAILABLE_JPEG_MIN_DURATIONS_DIM_MAX_SIZE_1 5 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_SCALER_AVAILABLE_JPEG_SIZES_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_SCALER_AVAILABLE_JPEG_SIZES_DIM_MAX_SIZE_2 5 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_SCALER_AVAILABLE_PROCESSED_MIN_DURATIONS_DIM_MAX_SIZE_1 9 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_SCALER_AVAILABLE_PROCESSED_SIZES_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_SCALER_AVAILABLE_PROCESSED_SIZES_DIM_MAX_SIZE_2 9 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_SCALER_AVAILABLE_RAW_MIN_DURATIONS_DIM_MAX_SIZE_1 1 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_SCALER_AVAILABLE_RAW_SIZES_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_SCALER_AVAILABLE_RAW_SIZES_DIM_MAX_SIZE_2 1 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_SENSOR_BLACK_LEVEL_PATTERN_DIM_MAX_SIZE_1 4
#define GUZZI_CAMERA3_STATIC_SENSOR_CALIBRATION_TRANSFORM1_DIM_MAX_SIZE_1 9
#define GUZZI_CAMERA3_STATIC_SENSOR_CALIBRATION_TRANSFORM2_DIM_MAX_SIZE_1 9
#define GUZZI_CAMERA3_STATIC_SENSOR_COLOR_TRANSFORM1_DIM_MAX_SIZE_1 9
#define GUZZI_CAMERA3_STATIC_SENSOR_COLOR_TRANSFORM2_DIM_MAX_SIZE_1 9
#define GUZZI_CAMERA3_STATIC_SENSOR_FORWARD_MATRIX1_DIM_MAX_SIZE_1 9
#define GUZZI_CAMERA3_STATIC_SENSOR_FORWARD_MATRIX2_DIM_MAX_SIZE_1 9
#define GUZZI_CAMERA3_STATIC_SENSOR_INFO_ACTIVE_ARRAY_SIZE_DIM_MAX_SIZE_1 4
#define GUZZI_CAMERA3_STATIC_SENSOR_INFO_EXPOSURE_TIME_RANGE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_SENSOR_INFO_PHYSICAL_SIZE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_SENSOR_INFO_PIXEL_ARRAY_SIZE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_SENSOR_INFO_SENSITIVITY_RANGE_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_SENSOR_NOISE_MODEL_COEFFICIENTS_DIM_MAX_SIZE_1 2
#define GUZZI_CAMERA3_STATIC_STATISTICS_INFO_AVAILABLE_FACE_DETECT_MODES_DIM_MAX_SIZE_1 3 /* TODO: n */
#define GUZZI_CAMERA3_STATIC_STATISTICS_INFO_SHARPNESS_MAP_SIZE_DIM_MAX_SIZE_1 2

/*
 * ****************************************************************************
 * ** Guzzi specific **********************************************************
 * ****************************************************************************
 */
/*
 * ****************************************************************************
 * * controls
 * ****************************************************************************
 */
#define GUZZI_CAMERA3_CONTROLS_CAPTURE_REQUEST_ACTIVE_DIM_MAX_SIZE_1 8
#define GUZZI_CAMERA3_CONTROLS_STREAM_CONFIG_FORMAT_DIM_MAX_SIZE_1 8
#define GUZZI_CAMERA3_CONTROLS_STREAM_CONFIG_HEIGHT_DIM_MAX_SIZE_1 8
#define GUZZI_CAMERA3_CONTROLS_STREAM_CONFIG_ID_DIM_MAX_SIZE_1 8
#define GUZZI_CAMERA3_CONTROLS_STREAM_CONFIG_TYPE_DIM_MAX_SIZE_1 8
#define GUZZI_CAMERA3_CONTROLS_STREAM_CONFIG_WIDTH_DIM_MAX_SIZE_1 8
#define GUZZI_CAMERA3_CONTROLS_Z_CUSTOM_EXPOSURE_BRACKETING_SEQUENCE_DIM_MAX_SIZE_1 3

/*
 * ****************************************************************************
 * * Used types ***************************************************************
 * ****************************************************************************
 */
typedef double guzzi_camera3_double_t;
typedef float guzzi_camera3_float_t;
typedef int64 guzzi_camera3_int64_t;
typedef struct {
    int nom;
    int denom;
} guzzi_camera3_rational_t;
typedef int32 guzzi_camera3_int32_t;
typedef uint8 guzzi_camera3_byte_t;

#include <guzzi/auto_gen/camera3/metadata_struct.h>

#define META_DIM_SIZE_1(M) ((M)->dim_size_1)
#define META_DIM_SIZE_2(M) ((M)->dim_size_2)
#define META_DIM_SIZE_3(M) ((M)->dim_size_3)
#define META_DIM_SIZE_4(M) ((M)->dim_size_4)

#define META_ARR_SIZE_1(M)  META_DIM_SIZE_1(M)
#define META_ARR_SIZE_2(M) (META_ARR_SIZE_1(M)*META_DIM_SIZE_2(M))
#define META_ARR_SIZE_3(M) (META_ARR_SIZE_2(M)*META_DIM_SIZE_3(M))
#define META_ARR_SIZE_4(M) (META_ARR_SIZE_3(M)*META_DIM_SIZE_4(M))

/* int arr[Dn]...[D2][D1]; x = arr[iN]...[i2][i1]; */
#define ARRIDX1(i1)                   (i1)
#define ARRIDX2(i2,i1,D1)             ARRIDX1((i2)*(D1) + (i1))
#define ARRIDX3(i3,i2,i1,D2,D1)       ARRIDX2(ARRIDX2(i3,i2,D2)      , i1, D1)
#define ARRIDX4(i4,i3,i2,i1,D3,D2,D1) ARRIDX2(ARRIDX3(i4,i3,i2,D3,D2), i1, D1)

#define METAIDX1(M,i1) \
    ((M)->v[ARRIDX1(i1)])
#define METAIDX2(M,i2,i1) \
    ((M)->v[ARRIDX2(i2, i1, META_DIM_SIZE_1(M))])
#define METAIDX3(M,i3,i2,i1) \
    ((M)->v[ARRIDX3(i3, i2, i1, META_DIM_SIZE_2(M), META_DIM_SIZE_1(M))])
#define METAIDX4(M,i4,i3,i2,i1) \
    ((M)->v[ARRIDX4(i4, i3, i2, i1, META_DIM_SIZE_3(M), META_DIM_SIZE_2(M), META_DIM_SIZE_1(M))])

#define meta_arr_iterate(D,M,i) \
    for (i = 0; i < META_ARR_SIZE_##D(M); i++)

#define meta_arr_iterate_dim_1(D,M,i) \
    for (i = 0; i < META_DIM_SIZE_##D(M); i++)
#define meta_arr_iterate_dim_2(D2,D1,M,i2,i1) \
    meta_arr_iterate_dim_1(D2,M,i2) \
       meta_arr_iterate_dim_1(D1,M,i1)
#define meta_arr_iterate_dim_3(D3,D2,D1,M,i3,i2,i1) \
    meta_arr_iterate_dim_2(D3,D2,M,i3,i2) \
       meta_arr_iterate_dim_1(D1,M,i1)
#define meta_arr_iterate_dim_4(D4,D3,D2,D1,M,i4,i3,i2,i1) \
    meta_arr_iterate_dim_3(D4,D3,D2,M,i4,i3,i2) \
       meta_arr_iterate_dim_1(D1,M,i1)

#ifdef __cplusplus
}
#endif

#endif /* _GUZZI_CAMERA3_METADATA_STRUCT_H */

