#ifndef __AXIDMA_DEFS_H__
#define __AXIDMA_DEFS_H__

#define AXI3_MAX_PAGE_SIZE (4096)

/**
 * AXI DMAC configuration
 ****************************************************************************************/

#define AXIDMA_CH_NUM (8)

#define AXIDMA_MIN_CH_PRIO (0)
#define AXIDMA_MAX_CH_PRIO (AXIDMA_CH_NUM - 1)

#define AXIDMA_MAX_BLK_NUM (1024) /* Maximum value of number of blocks (CHx_BLOCK_TS register) */

/**
 * AXIDMA DMAC CONFIG REGISTER
 ****************************************************************************************/
#define AXIDMA_DMAC_CFG_0_DMAC_EN_POS  (0)
#define AXIDMA_DMAC_CFG_0_DMAC_EN_MASK (1 << AXIDMA_DMAC_CFG_0_DMAC_EN_POS)
#define AXIDMA_DMAC_CFG_0_INT_EN_POS   (1)
#define AXIDMA_DMAC_CFG_0_INT_EN_MASK  (1 << AXIDMA_DMAC_CFG_0_INT_EN_POS)

/**
 * AXIDMA DMAC CHANNEL ENABLE REGISTER
 ****************************************************************************************/
#define AXIDMA_DMAC_CH_EN_0_CH_EN_POS       (0)
#define AXIDMA_DMAC_CH_EN_0_CH_EN_MASK      (0xFF << AXIDMA_DMAC_CH_EN_0_CH_EN_POS)
#define AXIDMA_DMAC_CH_EN_0_CH_EN_WE_POS    (8)
#define AXIDMA_DMAC_CH_EN_0_CH_EN_WE_MASK   (0xFF << AXIDMA_DMAC_CH_EN_0_CH_EN_WE_POS)
#define AXIDMA_DMAC_CH_EN_0_CH_SUSP_POS     (16)
#define AXIDMA_DMAC_CH_EN_0_CH_SUSP_MASK    (0xFF << AXIDMA_DMAC_CH_EN_0_CH_SUSP_POS)
#define AXIDMA_DMAC_CH_EN_0_CH_SUSP_WE_POS  (24)
#define AXIDMA_DMAC_CH_EN_0_CH_SUSP_WE_MASK (0xFF << AXIDMA_DMAC_CH_EN_0_CH_SUSP_WE_POS)

#define AXIDMA_DMAC_CH_EN_1_CH_ABORT_POS     (0)
#define AXIDMA_DMAC_CH_EN_1_CH_ABORT_MASK    (0xFF << AXIDMA_DMAC_CH_EN_1_CH_ABORT_POS)
#define AXIDMA_DMAC_CH_EN_1_CH_ABORT_WE_POS  (8)
#define AXIDMA_DMAC_CH_EN_1_CH_ABORT_WE_MASK (0xFF << AXIDMA_DMAC_CH_EN_1_CH_ABORT_WE_POS)

/**
 * AXIDMA DMAC COMMON INTERRUPT STATUS REGISTER
 ****************************************************************************************/
#define AXIDMA_DMAC_COMMON_INTSTATUS_DEC_ERR_POS               (0)
#define AXIDMA_DMAC_COMMON_INTSTATUS_DEC_ERR_MASK              (1 << AXIDMA_DMAC_COMMON_INTSTATUS_DEC_ERR_POS)
#define AXIDMA_DMAC_COMMON_INTSTATUS_WR2RO_ERR_POS             (1)
#define AXIDMA_DMAC_COMMON_INTSTATUS_WR2RO_ERR_MASK            (1 << AXIDMA_DMAC_COMMON_INTSTATUS_WR2RO_ERR_POS)
#define AXIDMA_DMAC_COMMON_INTSTATUS_RD2WO_ERR_POS             (2)
#define AXIDMA_DMAC_COMMON_INTSTATUS_RD2WO_ERR_MASK            (1 << AXIDMA_DMAC_COMMON_INTSTATUS_RD2WO_ERR_POS)
#define AXIDMA_DMAC_COMMON_INTSTATUS_WRONHOLD_ERR_POS          (3)
#define AXIDMA_DMAC_COMMON_INTSTATUS_WRONHOLD_MASK             (1 << AXIDMA_DMAC_COMMON_INTSTATUS_WRONHOLD_ERR_POS)
#define AXIDMA_DMAC_COMMON_INTSTATUS_UNDEFINEDREG_DEC_ERR_POS  (8)
#define AXIDMA_DMAC_COMMON_INTSTATUS_UNDEFINEDREG_DEC_ERR_MASK (1 << AXIDMA_DMAC_COMMON_INTSTATUS_UNDEFINEDREG_DEC_ERR_POS)

#define AXIDMA_DMAC_INTSTATUS_MASK (AXIDMA_DMAC_COMMON_INTSTATUS_DEC_ERR_MASK             | \
                                    AXIDMA_DMAC_COMMON_INTSTATUS_WR2RO_ERR_MASK           | \
                                    AXIDMA_DMAC_COMMON_INTSTATUS_RD2WO_ERR_MASK           | \
                                    AXIDMA_DMAC_COMMON_INTSTATUS_WRONHOLD_MASK            | \
                                    AXIDMA_DMAC_COMMON_INTSTATUS_UNDEFINEDREG_DEC_ERR_MASK)

/**
 * AXIDMA DMAC INTERRUPT STATUS REGISTER
 ****************************************************************************************/
#define AXIDMA_DMAC_INT_STATUS_0_CHANNELS_INT_STAT_POS  (0)
#define AXIDMA_DMAC_INT_STATUS_0_CHANNELS_INT_STAT_MASK (0xFF << AXIDMA_DMAC_INT_STATUS_0_CHANNELS_INT_STAT_POS)
#define AXIDMA_DMAC_INT_STATUS_0_COMMON_INT_STAT_POS    (16)
#define AXIDMA_DMAC_INT_STATUS_0_COMMON_INT_STAT_MASK   (1 << AXIDMA_DMAC_INT_STATUS_0_COMMON_INT_STAT_POS)

/**
 * AXIDMA RESET REGISTER
 ****************************************************************************************/
#define AXIDMA_DMAC_RESETREG_DMAC_RST_POS  (0)
#define AXIDMA_DMAC_RESETREG_DMAC_RST_MASK (1 << AXIDMA_DMAC_RESETREG_DMAC_RST_POS)

/**
 * AXIDMA CHANNEL CONFIG REGISTERS
 ****************************************************************************************/
#define AXIDMA_CHANNEL_CONFIG_0_SRC_MULTBLK_TYPE_POS  (0)
#define AXIDMA_CHANNEL_CONFIG_0_SRC_MULTBLK_TYPE_MASK (0x3 << AXIDMA_CHANNEL_CONFIG_0_SRC_MULTBLK_TYPE_POS)
#define AXIDMA_CHANNEL_CONFIG_0_DST_MULTBLK_TYPE_POS  (2)
#define AXIDMA_CHANNEL_CONFIG_0_DST_MULTBLK_TYPE_MASK (0x3 << AXIDMA_CHANNEL_CONFIG_0_DST_MULTBLK_TYPE_POS)

#define AXIDMA_CHANNEL_CONFIG_1_TT_FC_POS         (0)
#define AXIDMA_CHANNEL_CONFIG_1_TT_FC_MASK        (0x7 << AXIDMA_CHANNEL_CONFIG_1_TT_FC_POS)
#define AXIDMA_CHANNEL_CONFIG_1_HS_SEL_SRC_POS    (3)
#define AXIDMA_CHANNEL_CONFIG_1_HS_SEL_SRC_MASK   (0x1 << AXIDMA_CHANNEL_CONFIG_1_HS_SEL_SRC_POS)
#define AXIDMA_CHANNEL_CONFIG_1_HS_SEL_DST_POS    (4)
#define AXIDMA_CHANNEL_CONFIG_1_HS_SEL_DST_MASK   (0x1 << AXIDMA_CHANNEL_CONFIG_1_HS_SEL_DST_POS)
#define AXIDMA_CHANNEL_CONFIG_1_SRC_HWHS_POL_POS  (5)
#define AXIDMA_CHANNEL_CONFIG_1_SRC_HWHS_POL_MASK (0x1 << AXIDMA_CHANNEL_CONFIG_1_SRC_HWHS_POL_POS)
#define AXIDMA_CHANNEL_CONFIG_1_DST_HWHS_POL_POS  (6)
#define AXIDMA_CHANNEL_CONFIG_1_DST_HWHS_POL_MASK (0x1 << AXIDMA_CHANNEL_CONFIG_1_DST_HWHS_POL_POS)
#define AXIDMA_CHANNEL_CONFIG_1_SRC_PER_POS       (7)
#define AXIDMA_CHANNEL_CONFIG_1_SRC_PER_MASK      (0xF << AXIDMA_CHANNEL_CONFIG_1_SRC_PER_POS)
#define AXIDMA_CHANNEL_CONFIG_1_DST_PER_POS       (12)
#define AXIDMA_CHANNEL_CONFIG_1_DST_PER_MASK      (0xF << AXIDMA_CHANNEL_CONFIG_1_DST_PER_POS)
#define AXIDMA_CHANNEL_CONFIG_1_CH_PRIOR_POS      (17)
#define AXIDMA_CHANNEL_CONFIG_1_CH_PRIOR_MASK     (0x7 << AXIDMA_CHANNEL_CONFIG_1_CH_PRIOR_POS)
#define AXIDMA_CHANNEL_CONFIG_1_LOCK_CH_POS       (20)
#define AXIDMA_CHANNEL_CONFIG_1_LOCK_CH_MASK      (0x1 << AXIDMA_CHANNEL_CONFIG_1_LOCK_CH_POS)
#define AXIDMA_CHANNEL_CONFIG_1_LOCK_CH_L_POS     (21)
#define AXIDMA_CHANNEL_CONFIG_1_LOCK_CH_L_MASK    (0x3 << AXIDMA_CHANNEL_CONFIG_1_LOCK_CH_L_POS)
#define AXIDMA_CHANNEL_CONFIG_1_SRC_OSR_LMT_POS   (23)
#define AXIDMA_CHANNEL_CONFIG_1_SRC_OSR_LMT_MASK  (0xF << AXIDMA_CHANNEL_CONFIG_1_SRC_OSR_LMT_POS)
#define AXIDMA_CHANNEL_CONFIG_1_DST_OSR_LMT_POS   (27)
#define AXIDMA_CHANNEL_CONFIG_1_DST_OSR_LMT_MASK  (0xF << AXIDMA_CHANNEL_CONFIG_1_DST_OSR_LMT_POS)

/**
 * AXIDMA CHANNEL CONTROL REGISTERS
 ****************************************************************************************/
#define AXIDMA_CHANNEL_CONTROL_0_SMS_POS                   (0)
#define AXIDMA_CHANNEL_CONTROL_0_SMS_MASK                  (0x1 << AXIDMA_CHANNEL_CONTROL_0_SMS_POS)
#define AXIDMA_CHANNEL_CONTROL_0_DMS_POS                   (2)
#define AXIDMA_CHANNEL_CONTROL_0_DMS_MASK                  (0x1 << AXIDMA_CHANNEL_CONTROL_0_DMS_POS)
#define AXIDMA_CHANNEL_CONTROL_0_SINC_POS                  (4)
#define AXIDMA_CHANNEL_CONTROL_0_SINC_MASK                 (0x1 << AXIDMA_CHANNEL_CONTROL_0_SINC_POS)
#define AXIDMA_CHANNEL_CONTROL_0_DINC_POS                  (6)
#define AXIDMA_CHANNEL_CONTROL_0_DINC_MASK                 (0x1 << AXIDMA_CHANNEL_CONTROL_0_DINC_POS)
#define AXIDMA_CHANNEL_CONTROL_0_SRC_TR_WIDTH_POS          (8)
#define AXIDMA_CHANNEL_CONTROL_0_SRC_TR_WIDTH_MASK         (0x7 << AXIDMA_CHANNEL_CONTROL_0_SRC_TR_WIDTH_POS)
#define AXIDMA_CHANNEL_CONTROL_0_DST_TR_WIDTH_POS          (11)
#define AXIDMA_CHANNEL_CONTROL_0_DST_TR_WIDTH_MASK         (0x7 << AXIDMA_CHANNEL_CONTROL_0_DST_TR_WIDTH_POS)
#define AXIDMA_CHANNEL_CONTROL_0_SRC_MSIZE_POS             (14)
#define AXIDMA_CHANNEL_CONTROL_0_SRC_MSIZE_MASK            (0xF << AXIDMA_CHANNEL_CONTROL_0_SRC_MSIZE_POS)
#define AXIDMA_CHANNEL_CONTROL_0_DST_MSIZE_POS             (18)
#define AXIDMA_CHANNEL_CONTROL_0_DST_MSIZE_MASK            (0xF << AXIDMA_CHANNEL_CONTROL_0_DST_MSIZE_POS)
#define AXIDMA_CHANNEL_CONTROL_0_NONPOSTED_LAST_WRITE_POS  (30)
#define AXIDMA_CHANNEL_CONTROL_0_NONPOSTED_LAST_WRITE_MASK (0x1 << AXIDMA_CHANNEL_CONTROL_0_NONPOSTED_LAST_WRITE_POS)

#define AXIDMA_CHANNEL_CONTROL_1_ARLEN_EN_POS             (6)
#define AXIDMA_CHANNEL_CONTROL_1_ARLEN_EN_MASK            (0x1 << AXIDMA_CHANNEL_CONTROL_1_ARLEN_EN_POS)
#define AXIDMA_CHANNEL_CONTROL_1_ARLEN_POS                (7)
#define AXIDMA_CHANNEL_CONTROL_1_ARLEN_MASK               (0xFF << AXIDMA_CHANNEL_CONTROL_1_ARLEN_POS)
#define AXIDMA_CHANNEL_CONTROL_1_AWLEN_EN_POS             (15)
#define AXIDMA_CHANNEL_CONTROL_1_AWLEN_EN_MASK            (0x1 << AXIDMA_CHANNEL_CONTROL_1_AWLEN_EN_POS)
#define AXIDMA_CHANNEL_CONTROL_1_AWLEN_POS                (16)
#define AXIDMA_CHANNEL_CONTROL_1_AWLEN_MASK               (0xFF << AXIDMA_CHANNEL_CONTROL_1_AWLEN_POS)
#define AXIDMA_CHANNEL_CONTROL_1_SRC_STAT_EN_POS          (24)
#define AXIDMA_CHANNEL_CONTROL_1_SRC_STAT_EN_MASK         (0x1 << AXIDMA_CHANNEL_CONTROL_1_SRC_STAT_EN_POS)
#define AXIDMA_CHANNEL_CONTROL_1_DST_STAT_EN_POS          (25)
#define AXIDMA_CHANNEL_CONTROL_1_DST_STAT_EN_MASK         (0x1 << AXIDMA_CHANNEL_CONTROL_1_DST_STAT_EN_POS)
#define AXIDMA_CHANNEL_CONTROL_1_IOC_BLK_TFR_POS          (26)
#define AXIDMA_CHANNEL_CONTROL_1_IOC_BLK_TFR_MASK         (0x1 << AXIDMA_CHANNEL_CONTROL_1_IOC_BLK_TFR_POS)
#define AXIDMA_CHANNEL_CONTROL_1_SHADOW_OR_LLI_LAST_POS   (30)
#define AXIDMA_CHANNEL_CONTROL_1_SHADOW_OR_LLI_LAST_MASK  (0x1 << AXIDMA_CHANNEL_CONTROL_1_SHADOW_OR_LLI_LAST_POS)
#define AXIDMA_CHANNEL_CONTROL_1_SHADOW_OR_LLI_VALID_POS  (31)
#define AXIDMA_CHANNEL_CONTROL_1_SHADOW_OR_LLI_VALID_MASK (0x1 << AXIDMA_CHANNEL_CONTROL_1_SHADOW_OR_LLI_VALID_POS)

/**
 * AXIDMA CHANNEL INTERRUPT STATUS REGISTERS
 ****************************************************************************************/
#define AXIDMA_CHANNEL_INTSTATUS_0_BLOCK_TRF_DONE_POS                  (0)
#define AXIDMA_CHANNEL_INTSTATUS_0_BLOCK_TRF_DONE_MASK                 (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_BLOCK_TRF_DONE_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_DMA_TRF_DONE_POS                    (1)
#define AXIDMA_CHANNEL_INTSTATUS_0_DMA_TRF_DONE_MASK                   (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_DMA_TRF_DONE_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SRC_TRANS_COMP_POS                  (3)
#define AXIDMA_CHANNEL_INTSTATUS_0_SRC_TRANS_COMP_MASK                 (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SRC_TRANS_COMP_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_DST_TRANS_COMP_POS                  (4)
#define AXIDMA_CHANNEL_INTSTATUS_0_DST_TRANS_COMP_MASK                 (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_DST_TRANS_COMP_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SRC_DEC_ERR_POS                     (5)
#define AXIDMA_CHANNEL_INTSTATUS_0_SRC_DEC_ERR_MASK                    (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SRC_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_DST_DEC_ERR_POS                     (6)
#define AXIDMA_CHANNEL_INTSTATUS_0_DST_DEC_ERR_MASK                    (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_DST_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SRC_SLV_ERR_POS                     (7)
#define AXIDMA_CHANNEL_INTSTATUS_0_SRC_SLV_ERR_MASK                    (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SRC_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_DST_SLV_ERR_POS                     (8)
#define AXIDMA_CHANNEL_INTSTATUS_0_DST_SLV_ERR_MASK                    (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_DST_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_DEC_ERR_POS                  (9)
#define AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_DEC_ERR_MASK                 (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_DEC_ERR_POS                  (10)
#define AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_DEC_ERR_MASK                 (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_SLV_ERR_POS                  (11)
#define AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_SLV_ERR_MASK                 (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_SLV_ERR_POS                  (12)
#define AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_SLV_ERR_MASK                 (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SHADOWREG_OR_LLI_INVALID_ERR_POS    (13)
#define AXIDMA_CHANNEL_INTSTATUS_0_SHADOWREG_OR_LLI_INVALID_ERR_MASK   (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SHADOWREG_OR_LLI_INVALID_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_MULTIBLKTYPE_ERR_POS          (14)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_MULTIBLKTYPE_ERR_MASK         (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_MULTIBLKTYPE_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_DEC_ERR_POS                   (16)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_DEC_ERR_MASK                  (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WR2RO_ERR_POS                 (17)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WR2RO_ERR_MASK                (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WR2RO_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_RD2RWO_ERR_POS                (18)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_RD2RWO_ERR_MASK               (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_RD2RWO_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONCHEN_ERR_POS              (19)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONCHEN_ERR_MASK             (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONCHEN_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_SHADOWREG_WRON_VALID_ERR_POS  (20)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_SHADOWREG_WRON_VALID_ERR_MASK (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_SHADOWREG_WRON_VALID_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONHOLD_ERR_POS              (21)
#define AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONHOLD_ERR_MASK             (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONHOLD_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_LOCK_CLEARED_POS                    (27)
#define AXIDMA_CHANNEL_INTSTATUS_0_LOCK_CLEARED_MASK                   (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_LOCK_CLEARED_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_SRC_SUSPENDED_POS                   (28)
#define AXIDMA_CHANNEL_INTSTATUS_0_SRC_SUSPENDED_MASK                  (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_SRC_SUSPENDED_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_CH_SUSPENDED_POS                    (29)
#define AXIDMA_CHANNEL_INTSTATUS_0_CH_SUSPENDED_MASK                   (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_CH_SUSPENDED_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_CH_DISABLED_POS                     (30)
#define AXIDMA_CHANNEL_INTSTATUS_0_CH_DISABLED_MASK                    (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_CH_DISABLED_POS)
#define AXIDMA_CHANNEL_INTSTATUS_0_CH_ABORTED_POS                      (31)
#define AXIDMA_CHANNEL_INTSTATUS_0_CH_ABORTED_MASK                     (0x1 << AXIDMA_CHANNEL_INTSTATUS_0_CH_ABORTED_POS)

#define AXIDMA_CHANNEL_ALL_STATUS_MASK (AXIDMA_CHANNEL_INTSTATUS_0_BLOCK_TRF_DONE_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_DMA_TRF_DONE_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SRC_TRANS_COMP_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_DST_TRANS_COMP_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SRC_DEC_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_DST_DEC_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SRC_SLV_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_DST_SLV_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_DEC_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_DEC_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_SLV_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_SLV_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SHADOWREG_OR_LLI_INVALID_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_MULTIBLKTYPE_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_DEC_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WR2RO_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_RD2RWO_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONCHEN_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_SHADOWREG_WRON_VALID_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONHOLD_ERR_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_LOCK_CLEARED_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_SRC_SUSPENDED_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_CH_SUSPENDED_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_CH_DISABLED_MASK | \
                                        AXIDMA_CHANNEL_INTSTATUS_0_CH_ABORTED_MASK)
/**
 * AXIDMA CHANNEL INTERRUPT STATUS ENABLE REGISTERS
 ****************************************************************************************/
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_BLOCK_TRF_DONE_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_BLOCK_TRF_DONE_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_BLOCK_TRF_DONE_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_BLOCK_TRF_DONE_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_DMA_TRF_DONE_POS                    (AXIDMA_CHANNEL_INTSTATUS_0_DMA_TRF_DONE_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_DMA_TRF_DONE_MASK                   (AXIDMA_CHANNEL_INTSTATUS_0_DMA_TRF_DONE_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SRC_TRANS_COMP_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_SRC_TRANS_COMP_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SRC_TRANS_COMP_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_SRC_TRANS_COMP_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_DST_TRANS_COMP_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_DST_TRANS_COMP_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_DST_TRANS_COMP_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_DST_TRANS_COMP_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SRC_DEC_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_SRC_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SRC_DEC_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_SRC_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_DST_DEC_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_DST_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_DST_DEC_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_DST_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SRC_SLV_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SRC_SLV_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_DST_SLV_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_DST_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_DST_SLV_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_DST_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_LLI_RD_DEC_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_LLI_RD_DEC_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_LLI_WR_DEC_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_LLI_WR_DEC_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_LLI_RD_SLV_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_LLI_RD_SLV_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_LLI_WR_SLV_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_LLI_WR_SLV_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SHADOWREG_OR_LLI_INVALID_ERR_POS    (AXIDMA_CHANNEL_INTSTATUS_0_SHADOWREG_OR_LLI_INVALID_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SHADOWREG_OR_LLI_INVALID_ERR_MASK   (AXIDMA_CHANNEL_INTSTATUS_0_SHADOWREG_OR_LLI_INVALID_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_MULTIBLKTYPE_ERR_POS          (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_MULTIBLKTYPE_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_MULTIBLKTYPE_ERR_MASK         (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_MULTIBLKTYPE_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_DEC_ERR_POS                   (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_DEC_ERR_MASK                  (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_WR2RO_ERR_POS                 (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WR2RO_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_WR2RO_ERR_MASK                (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WR2RO_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_RD2RWO_ERR_POS                (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_RD2RWO_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_RD2RWO_ERR_MASK               (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_RD2RWO_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_WRONCHEN_ERR_POS              (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONCHEN_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_WRONCHEN_ERR_MASK             (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONCHEN_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_SHADOWREG_WRON_VALID_ERR_POS  (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_SHADOWREG_WRON_VALID_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_SHADOWREG_WRON_VALID_ERR_MASK (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_SHADOWREG_WRON_VALID_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_WRONHOLD_ERR_POS              (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONHOLD_ERR_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SLVIF_WRONHOLD_ERR_MASK             (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONHOLD_ERR_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_LOCK_CLEARED_POS                    (AXIDMA_CHANNEL_INTSTATUS_0_LOCK_CLEARED_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_LOCK_CLEARED_MASK                   (AXIDMA_CHANNEL_INTSTATUS_0_LOCK_CLEARED_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SRC_SUSPENDED_POS                   (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SUSPENDED_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_SRC_SUSPENDED_MASK                  (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SUSPENDED_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_CH_SUSPENDED_POS                    (AXIDMA_CHANNEL_INTSTATUS_0_CH_SUSPENDED_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_CH_SUSPENDED_MASK                   (AXIDMA_CHANNEL_INTSTATUS_0_CH_SUSPENDED_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_CH_DISABLED_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_CH_DISABLED_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_CH_DISABLED_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_CH_DISABLED_MASK)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_CH_ABORTED_POS                      (AXIDMA_CHANNEL_INTSTATUS_0_CH_ABORTED_POS)
#define AXIDMA_CHANNEL_INTSTATUS_ENABLE_0_CH_ABORTED_MASK                     (AXIDMA_CHANNEL_INTSTATUS_0_CH_ABORTED_MASK)

/**
 * AXIDMA CHANNEL INTERRUPT SIGNAL ENABLE REGISTERS
 ****************************************************************************************/
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_BLOCK_TRF_DONE_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_BLOCK_TRF_DONE_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_BLOCK_TRF_DONE_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_BLOCK_TRF_DONE_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_DMA_TRF_DONE_POS                    (AXIDMA_CHANNEL_INTSTATUS_0_DMA_TRF_DONE_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_DMA_TRF_DONE_MASK                   (AXIDMA_CHANNEL_INTSTATUS_0_DMA_TRF_DONE_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SRC_TRANS_COMP_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_SRC_TRANS_COMP_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SRC_TRANS_COMP_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_SRC_TRANS_COMP_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_DST_TRANS_COMP_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_DST_TRANS_COMP_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_DST_TRANS_COMP_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_DST_TRANS_COMP_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SRC_DEC_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_SRC_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SRC_DEC_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_SRC_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_DST_DEC_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_DST_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_DST_DEC_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_DST_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SRC_SLV_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SRC_SLV_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_DST_SLV_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_DST_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_DST_SLV_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_DST_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_LLI_RD_DEC_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_LLI_RD_DEC_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_LLI_WR_DEC_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_LLI_WR_DEC_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_LLI_RD_SLV_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_LLI_RD_SLV_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_LLI_WR_SLV_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_LLI_WR_SLV_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SHADOWREG_OR_LLI_INVALID_ERR_POS    (AXIDMA_CHANNEL_INTSTATUS_0_SHADOWREG_OR_LLI_INVALID_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SHADOWREG_OR_LLI_INVALID_ERR_MASK   (AXIDMA_CHANNEL_INTSTATUS_0_SHADOWREG_OR_LLI_INVALID_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_MULTIBLKTYPE_ERR_POS          (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_MULTIBLKTYPE_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_MULTIBLKTYPE_ERR_MASK         (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_MULTIBLKTYPE_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_DEC_ERR_POS                   (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_DEC_ERR_MASK                  (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_WR2RO_ERR_POS                 (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WR2RO_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_WR2RO_ERR_MASK                (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WR2RO_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_RD2RWO_ERR_POS                (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_RD2RWO_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_RD2RWO_ERR_MASK               (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_RD2RWO_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_WRONCHEN_ERR_POS              (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONCHEN_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_WRONCHEN_ERR_MASK             (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONCHEN_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_SHADOWREG_WRON_VALID_ERR_POS  (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_SHADOWREG_WRON_VALID_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_SHADOWREG_WRON_VALID_ERR_MASK (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_SHADOWREG_WRON_VALID_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_WRONHOLD_ERR_POS              (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONHOLD_ERR_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SLVIF_WRONHOLD_ERR_MASK             (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONHOLD_ERR_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_LOCK_CLEARED_POS                    (AXIDMA_CHANNEL_INTSTATUS_0_LOCK_CLEARED_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_LOCK_CLEARED_MASK                   (AXIDMA_CHANNEL_INTSTATUS_0_LOCK_CLEARED_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SRC_SUSPENDED_POS                   (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SUSPENDED_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_SRC_SUSPENDED_MASK                  (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SUSPENDED_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_CH_SUSPENDED_POS                    (AXIDMA_CHANNEL_INTSTATUS_0_CH_SUSPENDED_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_CH_SUSPENDED_MASK                   (AXIDMA_CHANNEL_INTSTATUS_0_CH_SUSPENDED_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_CH_DISABLED_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_CH_DISABLED_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_CH_DISABLED_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_CH_DISABLED_MASK)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_CH_ABORTED_POS                      (AXIDMA_CHANNEL_INTSTATUS_0_CH_ABORTED_POS)
#define AXIDMA_CHANNEL_INTSIGNAL_ENABLE_0_CH_ABORTED_MASK                     (AXIDMA_CHANNEL_INTSTATUS_0_CH_ABORTED_MASK)

/**
 * AXIDMA CHANNEL INTERRUPT CLEAR REGISTERS
 ****************************************************************************************/
#define AXIDMA_CHANNEL_INTCLEAR_0_BLOCK_TRF_DONE_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_BLOCK_TRF_DONE_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_BLOCK_TRF_DONE_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_BLOCK_TRF_DONE_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_DMA_TRF_DONE_POS                    (AXIDMA_CHANNEL_INTSTATUS_0_DMA_TRF_DONE_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_DMA_TRF_DONE_MASK                   (AXIDMA_CHANNEL_INTSTATUS_0_DMA_TRF_DONE_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SRC_TRANS_COMP_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_SRC_TRANS_COMP_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_SRC_TRANS_COMP_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_SRC_TRANS_COMP_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_DST_TRANS_COMP_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_DST_TRANS_COMP_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_DST_TRANS_COMP_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_DST_TRANS_COMP_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SRC_DEC_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_SRC_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_SRC_DEC_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_SRC_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_DST_DEC_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_DST_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_DST_DEC_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_DST_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SRC_SLV_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_SRC_SLV_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_DST_SLV_ERR_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_DST_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_DST_SLV_ERR_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_DST_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_LLI_RD_DEC_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_LLI_RD_DEC_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_LLI_WR_DEC_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_LLI_WR_DEC_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_LLI_RD_SLV_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_LLI_RD_SLV_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_RD_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_LLI_WR_SLV_ERR_POS                  (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_SLV_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_LLI_WR_SLV_ERR_MASK                 (AXIDMA_CHANNEL_INTSTATUS_0_LLI_WR_SLV_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SHADOWREG_OR_LLI_INVALID_ERR_POS    (AXIDMA_CHANNEL_INTSTATUS_0_SHADOWREG_OR_LLI_INVALID_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_SHADOWREG_OR_LLI_INVALID_ERR_MASK   (AXIDMA_CHANNEL_INTSTATUS_0_SHADOWREG_OR_LLI_INVALID_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_MULTIBLKTYPE_ERR_POS          (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_MULTIBLKTYPE_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_MULTIBLKTYPE_ERR_MASK         (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_MULTIBLKTYPE_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_DEC_ERR_POS                   (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_DEC_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_DEC_ERR_MASK                  (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_DEC_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_WR2RO_ERR_POS                 (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WR2RO_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_WR2RO_ERR_MASK                (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WR2RO_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_RD2RWO_ERR_POS                (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_RD2RWO_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_RD2RWO_ERR_MASK               (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_RD2RWO_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_WRONCHEN_ERR_POS              (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONCHEN_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_WRONCHEN_ERR_MASK             (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONCHEN_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_SHADOWREG_WRON_VALID_ERR_POS  (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_SHADOWREG_WRON_VALID_ERR_POS )
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_SHADOWREG_WRON_VALID_ERR_MASK (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_SHADOWREG_WRON_VALID_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_WRONHOLD_ERR_POS              (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONHOLD_ERR_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_SLVIF_WRONHOLD_ERR_MASK             (AXIDMA_CHANNEL_INTSTATUS_0_SLVIF_WRONHOLD_ERR_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_LOCK_CLEARED_POS                    (AXIDMA_CHANNEL_INTSTATUS_0_LOCK_CLEARED_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_LOCK_CLEARED_MASK                   (AXIDMA_CHANNEL_INTSTATUS_0_LOCK_CLEARED_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_SRC_SUSPENDED_POS                   (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SUSPENDED_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_SRC_SUSPENDED_MASK                  (AXIDMA_CHANNEL_INTSTATUS_0_SRC_SUSPENDED_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_CH_SUSPENDED_POS                    (AXIDMA_CHANNEL_INTSTATUS_0_CH_SUSPENDED_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_CH_SUSPENDED_MASK                   (AXIDMA_CHANNEL_INTSTATUS_0_CH_SUSPENDED_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_CH_DISABLED_POS                     (AXIDMA_CHANNEL_INTSTATUS_0_CH_DISABLED_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_CH_DISABLED_MASK                    (AXIDMA_CHANNEL_INTSTATUS_0_CH_DISABLED_MASK)
#define AXIDMA_CHANNEL_INTCLEAR_0_CH_ABORTED_POS                      (AXIDMA_CHANNEL_INTSTATUS_0_CH_ABORTED_POS)
#define AXIDMA_CHANNEL_INTCLEAR_0_CH_ABORTED_MASK                     (AXIDMA_CHANNEL_INTSTATUS_0_CH_ABORTED_MASK)

/**
 * AXI DMAC APB CONTROL REGISTER 
 ****************************************************************************************/
#define AXIDMA_CTRL_DMA_CFG_DMAC_HOLDREQ_POS                        (0)
#define AXIDMA_CTRL_DMA_CFG_DMAC_HOLDREQ_MASK                       (1 << AXIDMA_CTRL_DMA_CFG_DMAC_HOLDREQ_POS)
#define AXIDMA_CTRL_DMA_CFG_DBG_CH_NUM_POS                          (1)
#define AXIDMA_CTRL_DMA_CFG_DBG_CH_NUM_MASK                         (7 << AXIDMA_CTRL_DMA_CFG_DBG_CH_NUM_POS)
#define AXIDMA_CTRL_DMA_CFG_INT_SEL_POS                             (4)
#define AXIDMA_CTRL_DMA_CFG_INT_SEL_MASK                            (0xFF << AXIDMA_CTRL_DMA_CFG_INT_SEL_POS)

/**
 * AXI DMAC APB STATUS REGISTER 
 ****************************************************************************************/
#define AXIDMA_CTRL_DMA_STAT_DMAC_BUSY_POS                              (0)
#define AXIDMA_CTRL_DMA_STAT_DMAC_BUSY_MASK                             (1 << AXIDMA_CTRL_DMA_STAT_DMAC_BUSY_POS)
#define AXIDMA_CTRL_DMA_STAT_DMAC_HOLD_ACK_POS                          (1)
#define AXIDMA_CTRL_DMA_STAT_DMAC_HOLD_ACK_MASK                         (1 << AXIDMA_CTRL_DMA_STAT_DMAC_HOLD_ACK_POS)
#define AXIDMA_CTRL_DMA_STAT_DMAC_SLVIF_BUSY_POS                        (2)
#define AXIDMA_CTRL_DMA_STAT_DMAC_SLVIF_BUSY_MASK                       (1 << AXIDMA_CTRL_DMA_STAT_DMAC_SLVIF_BUSY_POS)
#define AXIDMA_CTRL_DMA_STAT_INTR_CMNREG_POS                            (3)
#define AXIDMA_CTRL_DMA_STAT_INTR_CMNREG_MASK                           (1 << AXIDMA_CTRL_DMA_STAT_INTR_CMNREG_POS)
#define AXIDMA_CTRL_DMA_STAT_INTR_POS                                   (4)
#define AXIDMA_CTRL_DMA_STAT_INTR_MASK                                  (1 << AXIDMA_CTRL_DMA_STAT_INTR_POS)


/**
 * AXI DMAC Control registers fields
 ****************************************************************************************/
#define AXIDMA_CTL_TR_WIDTH_8   (0)
#define AXIDMA_CTL_TR_WIDTH_16  (1)
#define AXIDMA_CTL_TR_WIDTH_32  (2)
#define AXIDMA_CTL_TR_WIDTH_64  (3)
#define AXIDMA_CTL_TR_WIDTH_128 (4)
#define AXIDMA_CTL_TR_WIDTH_256 (5)
#define AXIDMA_CTL_TR_WIDTH_512 (6)

#define AXIDMA_CTL_INC    (0)
#define AXIDMA_CTL_NO_INC (1)

#define AXIDMA_CTL_MSIZE_1    (0)
#define AXIDMA_CTL_MSIZE_4    (1)
#define AXIDMA_CTL_MSIZE_8    (2)
#define AXIDMA_CTL_MSIZE_16   (3)
#define AXIDMA_CTL_MSIZE_32   (4)
#define AXIDMA_CTL_MSIZE_64   (5)
#define AXIDMA_CTL_MSIZE_128  (6)
#define AXIDMA_CTL_MSIZE_256  (7)
#define AXIDMA_CTL_MSIZE_512  (8)
#define AXIDMA_CTL_MSIZE_1024 (9)

#define AXIDMA_CTL_MASTER_1 (0)
#define AXIDMA_CTL_MASTER_2 (1)

#define AXIDMA_CTL_INC    (0)
#define AXIDMA_CTL_NO_INC (1)

/**
 * AXI DMAC Config registers settings
 ****************************************************************************************/
#define AXIDMA_CFG_MULTBLK_CONTIGUOUS  (0)
#define AXIDMA_CFG_MULTBLK_RELOAD      (1)
#define AXIDMA_CFG_MULTBLK_SHADOW_REG  (2)
#define AXIDMA_CFG_MULTBLK_LINKED_LIST (3)

#define AXIDMA_CFG_LOCK_DMA_TRANSFER   (0)
#define AXIDMA_CFG_LOCK_BLOCK_TRANSFER (1)

#define AXIDMA_CFG_TT_FC_D_M2M  (0) /* Transfer Type is memory to memory and Flow Controller is DW_axi_dmac */
#define AXIDMA_CFG_TT_FC_D_M2P  (1) /* Transfer Type is memory to peripheral and Flow Controller is DW_axi_dmac */
#define AXIDMA_CFG_TT_FC_D_P2M  (2) /* Transfer Type is peripheral to memory and Flow Controller is DW_axi_dmac */
#define AXIDMA_CFG_TT_FC_D_P2P  (3) /* Transfer Type is peripheral to peripheral and Flow Controller is DW_axi_dmac */
#define AXIDMA_CFG_TT_FC_SP_P2M (4) /* Transfer Type is peripheral to Memory and Flow Controller is Source peripheral */
#define AXIDMA_CFG_TT_FC_SP_P2P (5) /* Transfer Type is peripheral to peripheral and Flow Controller is Source peripheral */
#define AXIDMA_CFG_TT_FC_DP_M2P (6) /* Transfer Type is memory to peripheral and Flow Controller is Destination peripheral */
#define AXIDMA_CFG_TT_FC_DP_P2P (7) /* Transfer Type is peripheral to peripheral and Flow Controller is Destination peripheral */

#define AXIDMA_CFG_MULTBLK_CONTIGUOUS  (0)
#define AXIDMA_CFG_MULTBLK_RELOAD      (1)
#define AXIDMA_CFG_MULTBLK_SHADOW_REG  (2)
#define AXIDMA_CFG_MULTBLK_LINKED_LIST (3)

#define AXIDMA_CFG_HS_SEL_HW (0)
#define AXIDMA_CFG_HS_SEL_SW (1)

#define AXIDMA_CFG_HS_ACT_HIGH (0)
#define AXIDMA_CFG_HS_ACT_LOW  (1)

/**
 * AXIDMA LINK LIST
 ****************************************************************************************/
#define AXIDMA_LLP_MASTER_0 (0)
#define AXIDMA_LLP_MASTER_1 (1)

#define AXIDMA_LLP_STATUS_1_DMA_TRF_DONE_POS    (31)
#define AXIDMA_LLP_STATUS_1_DMA_TRF_DONE_MASK   (0x1 << AXIDMA_LLP_STATUS_1_DMA_TRF_DONE_POS)
#define AXIDMA_LLP_STATUS_1_BLOCK_TRF_DONE_POS  (30)
#define AXIDMA_LLP_STATUS_1_BLOCK_TRF_DONE_MASK (0x1 << AXIDMA_LLP_STATUS_1_BLOCK_TRF_DONE_POS)

/**
 * Register field access macros
 ****************************************************************************************/

/*#define AXIDMA_REG_ACCESS_VERBOSE*/

#define AXIDMA_CHANNEL_SET_REG_FIELD(_reg_name_, _reg_field_, _field_value_, _reg_value_) \
    _reg_value_ &= ~(AXIDMA_CHANNEL_##_reg_name_##_##_reg_field_##_MASK); \
    _reg_value_ |= ((_field_value_ << AXIDMA_CHANNEL_##_reg_name_##_##_reg_field_##_POS) & (AXIDMA_CHANNEL_##_reg_name_##_##_reg_field_##_MASK));

#define AXIDMA_CHANNEL_GET_REG_FIELD(_reg_name_, _reg_field_, _field_value_, _reg_value_) \
    _field_value_ = ((_reg_value_ & AXIDMA_CHANNEL_##_reg_name_##_##_reg_field_##_MASK) >> AXIDMA_CHANNEL_##_reg_name_##_##_reg_field_##_POS);

#define AXIDMA_GET_CHANNEL_REG_ADR(_channel_id_, _reg_name_) \
    (AXIDMA0_BASE_ADR + AXIDMA_CHANNEL_0_REGS_OFFSET * (_channel_id_ + 1) + AXIDMA_CHANNEL_##_reg_name_##_OFFSET)

#ifdef AXIDMA_REG_ACCESS_VERBOSE
#define AXIDMA_CHANNEL_READ_REG(_channel_id_, _reg_name_, _reg_value_) \
    do { \
        uint32_t _reg_adr_ = AXIDMA_GET_CHANNEL_REG_ADR(_channel_id_, _reg_name_); \
        _reg_value_ = GET_REG_WORD_VAL(_reg_adr_); \
         printf("READ - ADR = 0x%08x[%s] - VAL = 0x%08x\n", (unsigned int)_reg_adr_, #_reg_name_, (unsigned int)_reg_value_); \
     } while (0)

//          printf ("[%s:%u] - READ - ADR = 0x%08x[%s] - VAL = 0x%08x\n", __func__, __LINE__, (unsigned int)_reg_adr_, #_reg_name_, (unsigned int)_reg_value_);
//     } while (0)

#define AXIDMA_CHANNEL_WRITE_REG(_channel_id_, _reg_name_, _reg_value_) \
    do { \
        uint32_t _reg_adr_ = AXIDMA_GET_CHANNEL_REG_ADR(_channel_id_, _reg_name_); \
        SET_REG_WORD(_reg_adr_, _reg_value_); \
        printf("WRITE - ADR = 0x%08x[%s] - VAL = 0x%08x\n", (unsigned int)_reg_adr_, #_reg_name_, (unsigned int)_reg_value_); \
    } while (0)

//         printf ("[%s:%u] - WRITE - ADR = 0x%08x[%s] - VAL = 0x%08x\n", __func__, __LINE__, (unsigned int)_reg_adr_, #_reg_name_, (unsigned int)_reg_value_);
//    } while (0)

#else /* AXIDMA_REG_ACCESS_VERBOSE */
#define AXIDMA_CHANNEL_READ_REG(_channel_id_, _reg_name_, _reg_value_) \
    do { \
        uint32_t _reg_adr_ = AXIDMA_GET_CHANNEL_REG_ADR(_channel_id_, _reg_name_); \
        _reg_value_ = GET_REG_WORD_VAL(_reg_adr_); \
    } while (0)

#define AXIDMA_CHANNEL_WRITE_REG(_channel_id_, _reg_name_, _reg_value_) \
    do { \
        uint32_t _reg_adr_ = AXIDMA_GET_CHANNEL_REG_ADR(_channel_id_, _reg_name_); \
        SET_REG_WORD(_reg_adr_, _reg_value_); \
    } while (0)
#endif /* AXIDMA_REG_ACCESS_VERBOSE */

#endif /*__AXIDMA_DEFS_H__*/
