/* usbpump_usbdi_ttclass.h	Wed Feb 13 2008 19:20:16 djt */

/*

Module:  usbpump_usbdi_ttclass.h

Function:
	Definition of TT class object

Version:
	V1.97k	Wed Feb 13 2008 19:20:16 djt	Edit level 3

Copyright notice:
	This file copyright (C) 2007 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	Debbie Totsline, MCCI Corporation	October 2007

Revision history:
   1.97j  Tue Oct 02 2007 13:39:21 djt
	3265: Module created.

   1.97j  Mon Dec 10 2007 11:57:01  djt
	3265: Fixed cosmetic errors found during code review.

   1.97k  Wed Feb 13 2008 19:20:16  djt
	6900: Moved CLASS_NAME here.

*/

#ifndef _USBPUMP_USBDI_TTCLASS_H_		/* prevent multiple includes */
#define _USBPUMP_USBDI_TTCLASS_H_

#ifndef _USBPUMP_USBDI_TYPES_H_
# include "usbpump_usbdi_types.h"
#endif

#ifndef _USBPUMPOBJECT_H_
# include "usbpumpobject.h"
#endif


/*******************************************************************************\
|
|	The USBDI_TT_CLASS object is used for submitting requests to the TT CLASS 
|	object.
|
\*******************************************************************************/

/*

Type:	USBPUMP_USBDI_TT_CLASS

Function:
	Represents the TT CLASS object

Description:
	Each hub within USBDI manages an optional collection of TT
	objects that export a USBPUMP_USBDI_TT view of themselves.
	This view is used by function drivers to send requests to the
	TT class.

Contents:
	USBPUMP_OBJECT_CLASS		*pTTClassObject;
		Pointer to the class object.

	USBPUMP_USBDI_TT_CLASS_METHOD_TABLE *pMethods;
		The method table contains:

 Notes: 
	There are currently no methods defined for the TT CLASS object.
	This is a place holder in case we come up with some in the future.

*/


__TMS_TYPE_DEF_STRUCT(USBPUMP_USBDI_TT_CLASS);
struct __TMS_STRUCTNAME(USBPUMP_USBDI_TT_CLASS)
	{
	__TMS_USBPUMP_OBJECT_CLASS		*pTTClassObject;
/*
||	__TMS_CONST __TMS_USBPUMP_USBDI_PUBLIC_TT_CLASS_METHOD_TABLE *pMethods;
*/
	};

#define	__TMS_USBPUMP_USBDI_TT_CLASS_NAME	\
				__TMS_USBPUMP_USBDI_NAME("tt.class")

/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/
/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_USBDI_TT_CLASS_NAME	\
   __TMS_USBPUMP_USBDI_TT_CLASS_NAME
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpump_usbdi_ttclass.h ****/
#endif /* _usbpump_usbdi_ttclass_H_ */
