///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "sippTutD0Model.h"

#include <include/sippHwDefs.h>
#include <filters/conv5x5/conv5x5.h>
#include <filters/absdiff/absdiff.h>
#include <filters/arithmeticAdd/arithmeticAdd.h>


//The full-frame buffers
UInt8      DDR_DATA SippTutD0Model_dmaIn0_buffer[512      * 512     * 1  ]ALIGNED(8);
UInt8      DDR_DATA SippTutD0Model_dmaOut1_buffer[512      * 512     * 1  ]ALIGNED(8);
	
///
void readSippTutD0ModelInput(SippTutD0Model *pPl)
{
   sippRdFileU8((UInt8*)SippTutD0Model_dmaIn0_buffer,512        * 512     * 1 * sizeof(UInt8),"../../../../../../../resources/lena_512x512_luma.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeSippTutD0ModelOutput(SippTutD0Model *pPl)
{
   sippWrFileU8((UInt8*)SippTutD0Model_dmaOut1_buffer,512        * 512     * 1 * sizeof(UInt8),"output.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildSippTutD0Model(SippTutD0Model *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->conv5x54        =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SZ(Conv5x5Param),   SVU_SYM(svuConv5x5),          0);
   pPl->absdiff0        =  sippCreateFilter(pPl->pl, 0x0,        512,    512,    N_PL(1),  SZ(UInt8), 0,                  SVU_SYM(svuAbsdiff),          0);
   pPl->arithmeticAdd4  =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), 0,                  SVU_SYM(svuArithmeticAdd),    0);
   pPl->dmaOut1         =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->conv5x54,      pPl->dmaIn0,        5,5                 );
   sippLinkFilter(pPl->absdiff0,      pPl->dmaIn0,        1,1                 );
   sippLinkFilter(pPl->absdiff0,      pPl->conv5x54,      1,1                 );
   sippLinkFilter(pPl->arithmeticAdd4, pPl->dmaIn0,        1,1                 );
   sippLinkFilter(pPl->arithmeticAdd4, pPl->absdiff0,      1,1                 );
   sippLinkFilter(pPl->dmaOut1,       pPl->arithmeticAdd4, 1,1                 );
	
}

UInt16 conv5x54Cfg_cMat[25];
  
void configSippTutD0Model(SippTutD0Model *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   Conv5x5Param        *conv5x54Cfg        = (Conv5x5Param     *)pPl->conv5x54->params;
   DmaParam            *dmaOut1Cfg         = (DmaParam         *)pPl->dmaOut1->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   conv5x54Cfg->cMat=       conv5x54Cfg_cMat;
   conv5x54Cfg->cMat[0]=    0x291f;
   conv5x54Cfg->cMat[1]=    0x291f;
   conv5x54Cfg->cMat[2]=    0x291f;
   conv5x54Cfg->cMat[3]=    0x291f;
   conv5x54Cfg->cMat[4]=    0x291f;
   conv5x54Cfg->cMat[5]=    0x291f;
   conv5x54Cfg->cMat[6]=    0x291f;
   conv5x54Cfg->cMat[7]=    0x291f;
   conv5x54Cfg->cMat[8]=    0x291f;
   conv5x54Cfg->cMat[9]=    0x291f;
   conv5x54Cfg->cMat[10]=   0x291f;
   conv5x54Cfg->cMat[11]=   0x291f;
   conv5x54Cfg->cMat[12]=   0x291f;
   conv5x54Cfg->cMat[13]=   0x291f;
   conv5x54Cfg->cMat[14]=   0x291f;
   conv5x54Cfg->cMat[15]=   0x291f;
   conv5x54Cfg->cMat[16]=   0x291f;
   conv5x54Cfg->cMat[17]=   0x291f;
   conv5x54Cfg->cMat[18]=   0x291f;
   conv5x54Cfg->cMat[19]=   0x291f;
   conv5x54Cfg->cMat[20]=   0x291f;
   conv5x54Cfg->cMat[21]=   0x291f;
   conv5x54Cfg->cMat[22]=   0x291f;
   conv5x54Cfg->cMat[23]=   0x291f;
   conv5x54Cfg->cMat[24]=   0x291f;
   dmaIn0Cfg->ddrAddr   = (UInt32)&SippTutD0Model_dmaIn0_buffer;
   dmaOut1Cfg->ddrAddr  = (UInt32)&SippTutD0Model_dmaOut1_buffer;
  
  
}
