///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTD0MODEL_H__
#define __SIPPTUTD0MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>



//The full-frame buffers
extern UInt8 DDR_DATA SippTutD0Model_dmaIn0_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutD0Model_dmaOut1_buffer[ 512 * 512 * 1 ]ALIGNED(8);
	
///

typedef struct SippTutD0Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut1;
	SippFilter *arithmeticAdd4;
	SippFilter *conv5x54;
	SippFilter *absdiff0;

} SippTutD0Model;

void readSippTutD0ModelInput(SippTutD0Model *pPl);
void writeSippTutD0ModelOutput(SippTutD0Model *pPl);

void buildSippTutD0Model(SippTutD0Model *pPl);
void configSippTutD0Model(SippTutD0Model *pPl);


#endif