/* usbpump_xdci_ioctlcodes.h	Wed Apr 13 2016 20:49:54 skpark */

/*

Module:  usbpump_xdci_ioctlcodes.h

Function:
	IOCTL codes specific to XDCI

Version:
	V3.17a	Wed Apr 13 2016 20:49:54 skpark	Edit level 1

Copyright notice:
	This file copyright (C) 2016 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation.

Author:
	SK Park, MCCI Corporation	April 2016

Revision history:
   3.17a  Wed Apr 13 2016 20:49:54  skpark
	20030: Module created.

*/

#ifndef _USBPUMP_XDCI_IOCTLCODES_H_	/* prevent multiple includes */
# define _USBPUMP_XDCI_IOCTLCODES_H_

#ifndef _USBPUMPIOCTL_H_
# include "usbpumpioctl.h"
#endif

#ifndef _USBPUMPOBJECT_H_
# include "usbpumpobject.h"
#endif

#ifndef _USBIOCTL_API_H_
# include "usbioctl_api.h"
#endif

#ifndef _XDCDKERN_H_
# include "xdcdkern.h"
#endif

/****************************************************************************\
|
|	Define the GUID & the request codes (pGuidSpecificInfo[0])
|	pGuidSpecificInfo[1] is always the pDcdXDci.
|
\****************************************************************************/

/* {5434f0da-662a-4fec-ae81-33ce7220db5d} */
#define	__TMS_USBPUMP_DCD_XDCI_GUID_PLATFORM_REQUEST			\
	__TMS_USBGUID_INIT(						\
0x5434f0da, 0x662a, 0x4fec, 0xae, 0x81, 0x33, 0xce, 0x72, 0x20, 0xdb, 0x5d \
	    )

/* define the request codes */
#define	__TMS_USBPUMP_DCD_XDCI_API_INDICATE_CODE(uIndex)		\
	((__TMS_VOID *) (0xBEEF0000 + (uIndex)))

#define __TMS_USBPUMP_DCD_XDCI_API_INDICATE_PLATFORM_INIT_USB_HARDWARE	\
	__TMS_USBPUMP_DCD_XDCI_API_INDICATE_CODE(0)

/****************************************************************************\
|
|	Uncloak names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_DCD_XDCI_GUID_PLATFORM_REQUEST	\
   __TMS_USBPUMP_DCD_XDCI_GUID_PLATFORM_REQUEST
# define USBPUMP_DCD_XDCI_API_INDICATE_CODE(uIndex)	\
   __TMS_USBPUMP_DCD_XDCI_API_INDICATE_CODE(uIndex)
# define USBPUMP_DCD_XDCI_API_INDICATE_PLATFORM_INIT_USB_HARDWARE	\
   __TMS_USBPUMP_DCD_XDCI_API_INDICATE_PLATFORM_INIT_USB_HARDWARE
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/* end of file */
#endif /* _USBPUMP_XDCI_IOCTLCODES_H_*/
