/* xdcdkern.h	Mon Jun  1 2015 00:37:32 tmm */

/*

Module:  xdcdkern.h

Function:
	Master include file for the XDCI DCD for the MCCI USB DataPump.

Version:
	V3.15b	Mon Jun  1 2015 00:37:32 tmm	Edit level 10

Copyright notice:
	This file copyright (C) 2012-2015 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	Wonkun Kim, MCCI Corporation	January 2012

Revision history:
   3.01f  Wed Jan 18 2012 13:40:56  wkkim
	15128: Module created.

   3.01f  Thu Apr 12 2012 14:30:35  wkkim
	15128: Remove unused structures and members and add document

   3.01f  Wed Jun 06 2012 10:50:29  wkkim
	15128: Add flags and power request function pointer and context
	to support low power mode
	15128: Add PMU control wiring option and functions

   3.01f  Mon Jun 11 2012 21:44:08  wkkim
	15128: Add uepxdcd_fReceivedXferNotReady to handle the case that
	Xfer Not Ready event happens before status IN transfer is started.

   3.01f  Wed Jun 27 2012 13:45:43  wkkim
	15128: Add udevxdcd_OldLinkState


   3.01f  Fri Jul 13 2012 14:34:49  wkkim
	15643: Add fEnumDone and fDeviceStopPending flags
	15645: Add pPendingIoctlQeHead

   3.01f  Fri Jul 27 2012 13:56:53  wkkim
	15128: Add endpoint variables for isoch transfer

   3.11d  Tue Dec 03 2013 15:21:15  ssyang
	17603: Add udevxdcdhh_pSofCallback and udevxdcdhh_fMicroFrameCallback
	for USBPUMP_IOCTL_DEVICE_XDCD_REGISTER_SOF_CLIENT processing.

   3.13a  Thu Jul 10 2014 17:03:16  tmm
	18309: refactor as part of SSIC work.

   3.15b  Mon Jun  1 2015 00:37:32  tmm
	19211: correct usages of "DataPump".

*/

#ifndef _XDCDKERN_H_		/* prevent multiple includes */
#define _XDCDKERN_H_

#ifndef _XDCDKERN_TYPES_H_
# include "xdcdkern_types.h"
#endif

#ifndef _UPLATFORMAPI_H_
# include "uplatformapi.h"
#endif

#ifndef _USBPUMP_UHILAUX_H_
# include "usbpump_uhilaux.h"
#endif

#ifndef _USBPUMP_ENDPOINT_XDCD_H_
# include "usbpump_endpoint_xdcd.h"
#endif

#ifndef _USBPUMP_DEVICE_XDCD_H_
# include "usbpump_device_xdcd.h"
#endif

#ifndef _USBPUMP_IOCTL_DEVICE_XDCD_H_
# include "usbpump_ioctl_device_xdcd.h"
#endif

/* most of the .c files need these */
#ifndef _BASEHIL_H_
# include "basehil.h"
#endif

#ifndef _USBPUMP_H_
# include "usbpump.h"
#endif

/****************************************************************************\
|
|	Here are the functions that are internal to the DataPump.
|
\****************************************************************************/

__TMS_BEGIN_DECLS

extern	__TMS_ROM __TMS_UDEVICESWITCH	gk_UsbPumpXdcd_switch;

__TMS_VOID xdcd_EpioInit(
	__TMS_USBPUMP_DEVICE_XDCD *,		/* pDcd */
	__TMS_UPIPE *,				/* pPipe */
	__TMS_USBPUMP_ENDPOINT_XDCD *,		/* pUep */
	__TMS_UCHAR				/* EpId */
	);

__TMS_END_DECLS

/****************************************************************************\
|
|	Last come the USB Resource Compiler Descriptor types:
|
\****************************************************************************/

#ifndef _USBRCTAB_H_
#include "usbrctab.h"
typedef struct __USBRCTAB_RESPTR    USBRC_RESPTR;
typedef	struct __USBRCTAB_LANGIDPTR USBRC_LANGIDPTR;
#endif

/****************************************************************************\
|
|	Uncloaked definitions
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of xdcdkern.h ****/
#endif /* _XDCDKERN_H_ */
