///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTC0MODEL_H__
#define __SIPPTUTC0MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "sippMat.h"


//The full-frame buffers
extern UInt8 DDR_DATA SippTutC0Model_dmaIn0_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutC0Model_dmaOut3_buffer[ 512 * 512 * 1 ]ALIGNED(8);
	
///

typedef struct SippTutC0Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut3;
	SippFilter *dilate5x52;

} SippTutC0Model;

void readSippTutC0ModelInput(SippTutC0Model *pPl);
void writeSippTutC0ModelOutput(SippTutC0Model *pPl);

void buildSippTutC0Model(SippTutC0Model *pPl);
void configSippTutC0Model(SippTutC0Model *pPl);


#endif