///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "sippTutC0Model.h"

#include <include/sippHwDefs.h>
#include <filters/dilate5x5/dilate5x5.h>


//The full-frame buffers
UInt8      DDR_DATA SippTutC0Model_dmaIn0_buffer[512      * 512     * 1  ]ALIGNED(8);
UInt8      DDR_DATA SippTutC0Model_dmaOut3_buffer[512      * 512     * 1  ]ALIGNED(8);
	
///
void readSippTutC0ModelInput(SippTutC0Model *pPl)
{
   sippRdFileU8((UInt8*)SippTutC0Model_dmaIn0_buffer,512        * 512     * 1 * sizeof(UInt8),"../../../../../../../resources/lena_512x512_luma.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeSippTutC0ModelOutput(SippTutC0Model *pPl)
{
   sippWrFileU8((UInt8*)SippTutC0Model_dmaOut3_buffer,512        * 512     * 1 * sizeof(UInt8),"gui_tut_C0_512x512_luma.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildSippTutC0Model(SippTutC0Model *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->dilate5x52      =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SZ(Dilate5x5Param), SVU_SYM(svuDilate5x5),        0);
   pPl->dmaOut3         =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->dilate5x52,    pPl->dmaIn0,        5,5                 );
   sippLinkFilter(pPl->dmaOut3,       pPl->dilate5x52,    1,1                 );
	
}

  
void configSippTutC0Model(SippTutC0Model *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   Dilate5x5Param      *dilate5x52Cfg      = (Dilate5x5Param   *)pPl->dilate5x52->params;
   DmaParam            *dmaOut3Cfg         = (DmaParam         *)pPl->dmaOut3->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   dilate5x52Cfg->dMat[0]=  (UInt8*)&dMat[0];
   dilate5x52Cfg->dMat[1]=  (UInt8*)&dMat[2];
   dilate5x52Cfg->dMat[2]=  (UInt8*)&dMat[4];
   dilate5x52Cfg->dMat[3]=  (UInt8*)&dMat[6];
   dilate5x52Cfg->dMat[4]=  (UInt8*)&dMat[8];
   dmaIn0Cfg->ddrAddr   = (UInt32)&SippTutC0Model_dmaIn0_buffer;
   dmaOut3Cfg->ddrAddr  = (UInt32)&SippTutC0Model_dmaOut3_buffer;
  
  
}
