#!/bin/bash

# this script is intended to be run in the directory containing the sipp
# filters. That's $(MDK_INSTALL_DIR_ABS)/common/components/sipp

FILTERS_DIR=filters
FILTERS_KCNF=kcnf
FILTERS_MAKEFILE=subdir.mk
LOCAL_FILTER_MAKEFILE=subdir.mk

pushd $FILTERS_DIR > /dev/null

truncate -s 0 $FILTERS_KCNF

cat > $FILTERS_MAKEFILE <<MAKEFILE_WARNING
# Warning: This file was generated by a script
# modify on your own risk of losing your changes
MAKEFILE_WARNING


FILTERS=$(ls -1 -d */)

for k in $FILTERS ; do
k=${k%%/}
k_UPPER=${k^^}
KCNF_OPTION=USE_SIPP_FILTER_$k_UPPER
cat >>$FILTERS_KCNF <<KCNF_ENTRY
config $KCNF_OPTION
  depends on USE_COMPONENT_SIPP
  bool "Use sipp filter $k"
  default n
  help
    Check this if you want to compile the $k sipp filter into your application

KCNF_ENTRY

echo "subdirs-shave-\$(CONFIG_$KCNF_OPTION)+=$k" >> $FILTERS_MAKEFILE

# now generate the Makefile for the filter
pushd "$k" > /dev/null

truncate -s 0 $LOCAL_FILTER_MAKEFILE

SHAVE_INCLUDE_FILE=$(find . -type f -name "*.h")
[ -f "$SHAVE_INCLUDE_FILE" ] && \
  echo "include-dirs-shave-y+=\$(MDK_INSTALL_DIR_ABS)/components/sipp/$FILTERS_DIR/$k" >> $LOCAL_FILTER_MAKEFILE
  echo "include-dirs-los-y+=\$(include-dirs-shave-y)" >> $LOCAL_FILTER_MAKEFILE
  echo "include-dirs-lrt-y+=\$(include-dirs-shave-y)" >> $LOCAL_FILTER_MAKEFILE
echo "" >> $LOCAL_FILTER_MAKEFILE

C_FILES=$(find . -type f -name "*.c")
ASM_FILES=$(find . -type f -name "*.asm")

#TODO:check if convertPFp16U16/convertPFp16U16/svuConvertPFp16U16.c is leon or shave code
SHAVE_SOURCE_FILES=$(echo "$C_FILES" "$ASM_FILES" | grep -v "leon")
LEON_SOURCE_FILES=$(echo "$C_FILES"  "$ASM_FILES" | grep "leon")

if [ ! "$SHAVE_SOURCE_FILES" == "" ]; then echo -n "srcs-shave-y+=">> $LOCAL_FILTER_MAKEFILE ; fi
for f in $SHAVE_SOURCE_FILES ; do
  echo -en " \\\\\n  $f" >> $LOCAL_FILTER_MAKEFILE
done
echo "" >> $LOCAL_FILTER_MAKEFILE

if [ ! "$LEON_SOURCE_FILES" == "" ]; then echo -n "srcs-los-y+=">> $LOCAL_FILTER_MAKEFILE ; fi
for f in $LEON_SOURCE_FILES ; do
  echo -en " \\\\\n  $f" >> $LOCAL_FILTER_MAKEFILE
done
echo "" >> $LOCAL_FILTER_MAKEFILE

popd > /dev/null

done

echo "subdirs-los-y=\$(subdirs-shave-y)" >> $LOCAL_FILTER_MAKEFILE
echo "subdirs-lrt-y=\$(subdirs-shave-y)" >> $LOCAL_FILTER_MAKEFILE

popd > /dev/null
# vim: set tw=0: set wrapmargin=0 :
