///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __CAM208CVHDMIMODEL_H__
#define __CAM208CVHDMIMODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "sippModelParams.h"


//The full-frame buffers
	
///

typedef struct Cam208CvHdmiModel
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *erode3x30;
	SippFilter *dilate3x30;
	SippFilter *dmaOut0;
	SippFilter *sobel0;
	SippFilter *lutMa2x5x0;

} Cam208CvHdmiModel;

void readCam208CvHdmiModelInput(Cam208CvHdmiModel *pPl);
void writeCam208CvHdmiModelOutput(Cam208CvHdmiModel *pPl);

void buildCam208CvHdmiModel(Cam208CvHdmiModel *pPl);
void configCam208CvHdmiModel(Cam208CvHdmiModel *pPl);


#endif