///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTD2MODEL_H__
#define __SIPPTUTD2MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>



//The full-frame buffers
extern UInt8 DDR_DATA SippTutD2Model_dmaIn0_buffer[ 512 * 512 * 3 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutD2Model_dmaOut1_buffer[ 512 * 512 * 1 ]ALIGNED(8);
	
///

typedef struct SippTutD2Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut1;
	SippFilter *cvtColorRGBtoLuma2;

} SippTutD2Model;

void readSippTutD2ModelInput(SippTutD2Model *pPl);
void writeSippTutD2ModelOutput(SippTutD2Model *pPl);

void buildSippTutD2Model(SippTutD2Model *pPl);
void configSippTutD2Model(SippTutD2Model *pPl);


#endif