///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "MemRegionApi.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt16     DDR_DATA MemRegionApi_dmaIn0_buffer[MEM_API_TEST_BAYER_WIDTH* MEM_API_TEST_BAYER_HEIGHT* 1  ]ALIGNED(8);
UInt8      DDR_DATA MemRegionApi_dmaOut0_buffer[MEM_API_TEST_BAYER_WIDTH* MEM_API_TEST_BAYER_HEIGHT* 3  ]ALIGNED(8);
UInt16     DDR_DATA MemRegionApi_dmaOut1_buffer[MEM_API_TEST_BAYER_WIDTH* MEM_API_TEST_BAYER_HEIGHT* 1  ]ALIGNED(8);
	
///
void readMemRegionApiInput(MemRegionApi *pPl)
{
   sippRdFileU8((UInt8*)MemRegionApi_dmaIn0_buffer,MEM_API_TEST_BAYER_WIDTH * MEM_API_TEST_BAYER_HEIGHT * 1 * sizeof(UInt16),"../../../../../../resources/test_522x128.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeMemRegionApiOutput(MemRegionApi *pPl)
{
   sippWrFileU8((UInt8*)MemRegionApi_dmaOut0_buffer,MEM_API_TEST_BAYER_WIDTH * MEM_API_TEST_BAYER_HEIGHT * 3 * sizeof(UInt8),"output0.raw");
   sippWrFileU8((UInt8*)MemRegionApi_dmaOut1_buffer,MEM_API_TEST_BAYER_WIDTH * MEM_API_TEST_BAYER_HEIGHT * 1 * sizeof(UInt16),"output1.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildMemRegionApi(MemRegionApi *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 3, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       MEM_API_TEST_BAYER_WIDTH, MEM_API_TEST_BAYER_HEIGHT, N_PL(1),  SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->lscMa2x5x0      =  sippCreateFilter(pPl->pl, 0x0,        MEM_API_TEST_BAYER_WIDTH, MEM_API_TEST_BAYER_HEIGHT, N_PL(1),  SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_LSC_ID,        0);
   pPl->rawMa2x5x0      =  sippCreateFilter(pPl->pl, 0x0,        MEM_API_TEST_BAYER_WIDTH, MEM_API_TEST_BAYER_HEIGHT, N_PL(1),  SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_RAW_ID,        0);
   pPl->debayerMa2x5x0  =  sippCreateFilter(pPl->pl, 0x0,        MEM_API_TEST_BAYER_WIDTH, MEM_API_TEST_BAYER_HEIGHT, N_PL(3),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DBYR_ID,       0);
   sippFilterAddOBuf(pPl->debayerMa2x5x0, 1, sizeof(UInt8));
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       MEM_API_TEST_BAYER_WIDTH, MEM_API_TEST_BAYER_HEIGHT, N_PL(3),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->dmaOut1         =  sippCreateFilter(pPl->pl, 0x00,       MEM_API_TEST_BAYER_WIDTH, MEM_API_TEST_BAYER_HEIGHT, N_PL(1),  SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->lscMa2x5x0,    pPl->dmaIn0,        1,0                 );
   sippLinkFilter(pPl->rawMa2x5x0,    pPl->lscMa2x5x0,    5,5                 );
   sippLinkFilter(pPl->debayerMa2x5x0, pPl->rawMa2x5x0,    11,11               );
   sippLinkFilter(pPl->dmaOut0,       pPl->debayerMa2x5x0, 1,1                 );
   sippLinkFilter(pPl->dmaOut1,       pPl->debayerMa2x5x0, 1,1                 );
   sippLinkFilterSetOBuf(pPl->dmaOut1, pPl->debayerMa2x5x0, 1);
	
}

  
void configMemRegionApi(MemRegionApi *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   LscParam            *lscMa2x5x0Cfg      = (LscParam         *)pPl->lscMa2x5x0->params;
   RawParam            *rawMa2x5x0Cfg      = (RawParam         *)pPl->rawMa2x5x0->params;
   DbyrParam           *debayerMa2x5x0Cfg  = (DbyrParam        *)pPl->debayerMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
   DmaParam            *dmaOut1Cfg         = (DmaParam         *)pPl->dmaOut1->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   lscMa2x5x0Cfg->gmBase=   lscMesh;
   lscMa2x5x0Cfg->gmWidth=  LSC_GAIN_MAP_W;
   lscMa2x5x0Cfg->gmHeight= LSC_GAIN_MAP_H;
   lscMa2x5x0Cfg->dataFormat=SIPP_LSC_CFG_FORMAT(BAYER);
   lscMa2x5x0Cfg->dataWidth=BAYER_BITS;
   rawMa2x5x0Cfg->grgbPlat= RAW_GRGB_PLATO(GRGB_IMBAL_PLAT_DARK,GRGB_IMBAL_PLAT_BRIGHT);
   rawMa2x5x0Cfg->grgbDecay=RAW_GRGB_DECAY(GRGB_IMBAL_DECAY_BRIGHT,GRGB_IMBAL_DECAY_DARK);
   rawMa2x5x0Cfg->badPixCfg=RAW_BAD_PIX_CFG(BAD_PIX_NOISE_LEVEL,BAD_PIX_ALPHA_G_HOT,BAD_PIX_ALPHA_G_COLD,BAD_PIX_ALPHA_RB_HOT,BAD_PIX_ALPHA_RB_COLD);
   rawMa2x5x0Cfg->cfg=      RAW_CFG(BAYER,BAYER_PATTERN,1,0,0,0,(BAYER_BITS-1),GRGB_IMBAL_THRESHOLD,0,0,1,0,1);
   rawMa2x5x0Cfg->gainSat[0]=((DIGI_SAT_GR << 16) | DIGI_GAIN_GR);
   rawMa2x5x0Cfg->gainSat[1]=((DIGI_SAT_GB << 16) | DIGI_GAIN_GB);
   rawMa2x5x0Cfg->gainSat[2]=((DIGI_SAT_R << 16) | DIGI_GAIN_R);
   rawMa2x5x0Cfg->gainSat[3]=((DIGI_SAT_B << 16) | DIGI_GAIN_B);
   rawMa2x5x0Cfg->statsBase=0;
   rawMa2x5x0Cfg->statsPlanes=RAW_STATS_PLANES(0,0,0,0,0,0);
   rawMa2x5x0Cfg->statsPatchCfg=RAW_PATCH_CFG(0,0,0,0);
   rawMa2x5x0Cfg->statsPatchStart=RAW_PATCH_START(0,0);
   rawMa2x5x0Cfg->statsPatchSkip=RAW_PATCH_START(0,0);
   rawMa2x5x0Cfg->statsThresh=0;
   rawMa2x5x0Cfg->afF1coefs[0]=0;
   rawMa2x5x0Cfg->afF1coefs[1]=0;
   rawMa2x5x0Cfg->afF1coefs[2]=0;
   rawMa2x5x0Cfg->afF1coefs[3]=0;
   rawMa2x5x0Cfg->afF1coefs[4]=0;
   rawMa2x5x0Cfg->afF1coefs[5]=0;
   rawMa2x5x0Cfg->afF1coefs[6]=0;
   rawMa2x5x0Cfg->afF1coefs[7]=0;
   rawMa2x5x0Cfg->afF1coefs[8]=0;
   rawMa2x5x0Cfg->afF1coefs[9]=0;
   rawMa2x5x0Cfg->afF1coefs[10]=0;
   rawMa2x5x0Cfg->afF2coefs[0]=0;
   rawMa2x5x0Cfg->afF2coefs[1]=0;
   rawMa2x5x0Cfg->afF2coefs[2]=0;
   rawMa2x5x0Cfg->afF2coefs[3]=0;
   rawMa2x5x0Cfg->afF2coefs[4]=0;
   rawMa2x5x0Cfg->afF2coefs[5]=0;
   rawMa2x5x0Cfg->afF2coefs[6]=0;
   rawMa2x5x0Cfg->afF2coefs[7]=0;
   rawMa2x5x0Cfg->afF2coefs[8]=0;
   rawMa2x5x0Cfg->afF2coefs[9]=0;
   rawMa2x5x0Cfg->afF2coefs[10]=0;
   rawMa2x5x0Cfg->afMinThresh=0;
   rawMa2x5x0Cfg->afSubtract=0;
   rawMa2x5x0Cfg->afPatchCfg=0;
   rawMa2x5x0Cfg->afPatchStart=0;
   rawMa2x5x0Cfg->afStatsBase=0;
   rawMa2x5x0Cfg->histLumaBase=0;
   rawMa2x5x0Cfg->histRgbBase=0;
   debayerMa2x5x0Cfg->cfg=  DEBAYER_CFG(BAYER_PATTERN,0,0,BAYER_BITS,8,P_RGB,3,0);
   debayerMa2x5x0Cfg->thresh=DEBAYER_THRESH(0,0,1,1,0,0);
   debayerMa2x5x0Cfg->dewormCfg=DEBAYER_DEWORM(0,0);
   debayerMa2x5x0Cfg->lumaWeight=0;
   dmaIn0Cfg->ddrAddr   = (UInt32)&MemRegionApi_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&MemRegionApi_dmaOut0_buffer;
   dmaOut1Cfg->ddrAddr  = (UInt32)&MemRegionApi_dmaOut1_buffer;
  
  
}
