///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "testHwHarrisCorners.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt8      DDR_DATA TestHwHarrisCorners_dmaIn0_buffer[SIPP_HW_HARRIS_BUFFER_WIDTH* SIPP_HW_HARRIS_BUFFER_HEIGHT* SIPP_HW_HARRIS_BUFFER_NUM_PLANES]ALIGNED(8);
UInt32     DDR_DATA TestHwHarrisCorners_dmaOut0_buffer[SIPP_HW_HARRIS_BUFFER_WIDTH* SIPP_HW_HARRIS_BUFFER_HEIGHT* SIPP_HW_HARRIS_BUFFER_NUM_PLANES]ALIGNED(8);
	
///
void readTestHwHarrisCornersInput(TestHwHarrisCorners *pPl)
{
   sippRdFileU8((UInt8*)TestHwHarrisCorners_dmaIn0_buffer,SIPP_HW_HARRIS_BUFFER_WIDTH * SIPP_HW_HARRIS_BUFFER_HEIGHT * SIPP_HW_HARRIS_BUFFER_NUM_PLANES* sizeof(UInt8),"../../../../../../../resources/testIMG_1296x972_P400.rgb");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeTestHwHarrisCornersOutput(TestHwHarrisCorners *pPl)
{
   sippWrFileU8((UInt8*)TestHwHarrisCorners_dmaOut0_buffer,SIPP_HW_HARRIS_BUFFER_WIDTH * SIPP_HW_HARRIS_BUFFER_HEIGHT * SIPP_HW_HARRIS_BUFFER_NUM_PLANES* sizeof(UInt32),"harrisUnitTestOut.rgb");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildTestHwHarrisCorners(TestHwHarrisCorners *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_HARRIS_BUFFER_WIDTH, SIPP_HW_HARRIS_BUFFER_HEIGHT, N_PL(SIPP_HW_HARRIS_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->harriscornersMa2x5x0 =  sippCreateFilter(pPl->pl, 0x0,        SIPP_HW_HARRIS_BUFFER_WIDTH, SIPP_HW_HARRIS_BUFFER_HEIGHT, N_PL(SIPP_HW_HARRIS_BUFFER_NUM_PLANES), SZ(UInt32), SIPP_AUTO,          (FnSvuRun)SIPP_HARRIS_ID,     0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_HARRIS_BUFFER_WIDTH, SIPP_HW_HARRIS_BUFFER_HEIGHT, N_PL(SIPP_HW_HARRIS_BUFFER_NUM_PLANES), SZ(UInt32), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->harriscornersMa2x5x0, pPl->dmaIn0,        5,5                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->harriscornersMa2x5x0, 1,1                 );
	
}

  
void configTestHwHarrisCorners(TestHwHarrisCorners *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   HarrisParam         *harriscornersMa2x5x0Cfg= (HarrisParam      *)pPl->harriscornersMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   harriscornersMa2x5x0Cfg->cfg=HARRIS_CORNER_CFG(KERNEL_SIZE, OUTPUT_CHOICE, EXP_SUBTRAHEND);
   harriscornersMa2x5x0Cfg->kValue=K_VAL;
   dmaIn0Cfg->ddrAddr   = (UInt32)&TestHwHarrisCorners_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwHarrisCorners_dmaOut0_buffer;
  
  
}
