#ifndef LEON_TESTHWHARRISCORNERSSETUP_H_
#define LEON_TESTHWHARRISCORNERSSETUP_H_

#define SIPP_HW_HARRIS_BUFFER_WIDTH      1296
#define SIPP_HW_HARRIS_BUFFER_HEIGHT     972
#define SIPP_HW_HARRIS_BUFFER_NUM_PLANES  1
#define SIPP_HW_HARRIS_BUFFER_SIZE  (SIPP_HW_HARRIS_BUFFER_WIDTH * SIPP_HW_HARRIS_BUFFER_HEIGHT * SIPP_HW_HARRIS_BUFFER_NUM_PLANES)

// Application specific parameters
#define HARRIS_OUTPUT_SCORE        0
#define HARRIS_OUTPUT_DETERMINANT  1
#define KERNEL_SIZE         5
#define OUTPUT_CHOICE       HARRIS_OUTPUT_SCORE
#define EXP_SUBTRAHEND      0
#define K_VAL               0.05f

#endif /* LEON_TESTHWHARRISCORNERSSETUP_H_ */
