///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __TESTHWHARRISCORNERS_H__
#define __TESTHWHARRISCORNERS_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "testHwHarrisCornersSetup.h"


//The full-frame buffers
extern UInt8 DDR_DATA TestHwHarrisCorners_dmaIn0_buffer[ SIPP_HW_HARRIS_BUFFER_WIDTH * SIPP_HW_HARRIS_BUFFER_HEIGHT * SIPP_HW_HARRIS_BUFFER_NUM_PLANES ]ALIGNED(8);
extern UInt32 DDR_DATA TestHwHarrisCorners_dmaOut0_buffer[ SIPP_HW_HARRIS_BUFFER_WIDTH * SIPP_HW_HARRIS_BUFFER_HEIGHT * SIPP_HW_HARRIS_BUFFER_NUM_PLANES ]ALIGNED(8);
	
///

typedef struct TestHwHarrisCorners
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *harriscornersMa2x5x0;
	SippFilter *dmaOut0;

} TestHwHarrisCorners;

void readTestHwHarrisCornersInput(TestHwHarrisCorners *pPl);
void writeTestHwHarrisCornersOutput(TestHwHarrisCorners *pPl);

void buildTestHwHarrisCorners(TestHwHarrisCorners *pPl);
void configTestHwHarrisCorners(TestHwHarrisCorners *pPl);


#endif