///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
///

#include "testHwRaw.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt8      DDR_DATA TestHwRaw_dmaOut0_buffer [SIPP_HW_RAW_BUFFER_WIDTH* SIPP_HW_RAW_BUFFER_HEIGHT* SIPP_HW_RAW_BUFFER_NUM_PLANES]ALIGNED(8);

///
void readTestHwRawInput(TestHwRaw *pPl)
{
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}

void writeTestHwRawOutput(TestHwRaw *pPl)
{
   sippWrFileU8((UInt8*)TestHwRaw_dmaOut0_buffer,SIPP_HW_RAW_BUFFER_WIDTH * SIPP_HW_RAW_BUFFER_HEIGHT * SIPP_HW_RAW_BUFFER_NUM_PLANES* sizeof(UInt8),"output.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}

void buildTestHwRaw(TestHwRaw *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 0, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_RAW_BUFFER_WIDTH, SIPP_HW_RAW_BUFFER_HEIGHT, N_PL(SIPP_HW_RAW_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->rawMa2x5x0      =  sippCreateFilter(pPl->pl, 0x0,        SIPP_HW_RAW_BUFFER_WIDTH, SIPP_HW_RAW_BUFFER_HEIGHT, N_PL(SIPP_HW_RAW_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_RAW_ID,        0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_RAW_BUFFER_WIDTH, SIPP_HW_RAW_BUFFER_HEIGHT, N_PL(SIPP_HW_RAW_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);

   // link filters
   sippLinkFilter(pPl->rawMa2x5x0,    pPl->dmaIn0,        5,5                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->rawMa2x5x0,    1,1                 );

}


void configTestHwRaw(TestHwRaw *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   RawParam            *rawMa2x5x0Cfg      = (RawParam         *)pPl->rawMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;

  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   rawMa2x5x0Cfg->grgbPlat= 0;
   rawMa2x5x0Cfg->grgbDecay=0;
   rawMa2x5x0Cfg->badPixCfg=0;
   rawMa2x5x0Cfg->cfg=      RAW_CFG(BAYER, BAYER_PATTERN,0,0,AE_PATCH_STATS_EN,AE_RGB_HIST_STATS_EN,(INPUT_DATA_WIDTH-1),0,0,AF_PATCH_STATS_EN,0,AE_Y_HIST_STATS_EN,0);
   rawMa2x5x0Cfg->gainSat[0]=((DIGI_SAT<<16) | DIGI_GAIN );
   rawMa2x5x0Cfg->gainSat[1]= ((DIGI_SAT<<16) | DIGI_GAIN );
   rawMa2x5x0Cfg->gainSat[2]= ((DIGI_SAT<<16) | DIGI_GAIN );
   rawMa2x5x0Cfg->gainSat[3]= ((DIGI_SAT<<16) | DIGI_GAIN );
   rawMa2x5x0Cfg->statsBase=(UInt32*)aeStatsBuff;
   rawMa2x5x0Cfg->statsPlanes=(PATCH_PLANE_0   <<  0) | ( PATCH_PLANE_1   <<  4) | (Y_HIST_PLANE    << 16) | ((ACTIVE_PATCH_PLANES - 1)*(2<<19));
   rawMa2x5x0Cfg->statsPatchCfg=((AE_HPATCHES_NO - 1) | (AE_VPATCHES_NO - 1) <<  8 | (AE_PATCH_WIDTH - 1) << 16 | (AE_PATCH_HEIGHT- 1) << 24);
   rawMa2x5x0Cfg->statsPatchStart=(AE_Y_START     << 16) |  AE_X_START;
   rawMa2x5x0Cfg->statsPatchSkip=((AE_Y_SKIP - 1) << 16) | (AE_X_SKIP - 1);
   rawMa2x5x0Cfg->statsThresh=(0<<16) | 255;
   rawMa2x5x0Cfg->afF1coefs[0]=44;
   rawMa2x5x0Cfg->afF1coefs[1]=  288;
   rawMa2x5x0Cfg->afF1coefs[2]= -200;
   rawMa2x5x0Cfg->afF1coefs[3]=   16;
   rawMa2x5x0Cfg->afF1coefs[4]=  28;
   rawMa2x5x0Cfg->afF1coefs[5]=  16;
   rawMa2x5x0Cfg->afF1coefs[6]=  368;
   rawMa2x5x0Cfg->afF1coefs[7]= -212;
   rawMa2x5x0Cfg->afF1coefs[8]= 536;
   rawMa2x5x0Cfg->afF1coefs[9]= -1076;
   rawMa2x5x0Cfg->afF1coefs[10]= 536;
   rawMa2x5x0Cfg->afF2coefs[0]=44;
   rawMa2x5x0Cfg->afF2coefs[1]= -288;
   rawMa2x5x0Cfg->afF2coefs[2]= -200;
   rawMa2x5x0Cfg->afF2coefs[3]=  104;
   rawMa2x5x0Cfg->afF2coefs[4]= 204;
   rawMa2x5x0Cfg->afF2coefs[5]= 104;
   rawMa2x5x0Cfg->afF2coefs[6]= -368;
   rawMa2x5x0Cfg->afF2coefs[7]= -212;
   rawMa2x5x0Cfg->afF2coefs[8]=  76;
   rawMa2x5x0Cfg->afF2coefs[9]=  -152;
   rawMa2x5x0Cfg->afF2coefs[10]=  76;
   rawMa2x5x0Cfg->afMinThresh=0;
   rawMa2x5x0Cfg->afSubtract=32;
   rawMa2x5x0Cfg->afPatchCfg=((AF_HPATCHES_NO - 1) | ((AF_VPATCHES_NO - 1) << 8 )| ((AF_PATCH_WIDTH - 1) << 16)| ((AF_PATCH_HEIGHT- 1) << 24));
   rawMa2x5x0Cfg->afPatchStart=((AF_X_START) |(AF_Y_START << 16));
   rawMa2x5x0Cfg->afStatsBase=(UInt32*)afStatsBuff;
   rawMa2x5x0Cfg->histLumaBase=histLuma;
   rawMa2x5x0Cfg->histRgbBase=histRGB;
   dmaIn0Cfg->ddrAddr   = (UInt32)&SippHwRaw_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwRaw_dmaOut0_buffer;


}
