///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __TESTHWRAW_H__
#define __TESTHWRAW_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "testHwRawSetup.h"


//The full-frame buffers
extern UInt8 DDR_DATA TestHwRaw_dmaOut0_buffer[ SIPP_HW_RAW_BUFFER_WIDTH * SIPP_HW_RAW_BUFFER_HEIGHT * SIPP_HW_RAW_BUFFER_NUM_PLANES ]ALIGNED(8);
	
///

typedef struct TestHwRaw
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *rawMa2x5x0;
	SippFilter *dmaIn0;
	SippFilter *dmaOut0;

} TestHwRaw;

void readTestHwRawInput(TestHwRaw *pPl);
void writeTestHwRawOutput(TestHwRaw *pPl);

void buildTestHwRaw(TestHwRaw *pPl);
void configTestHwRaw(TestHwRaw *pPl);


#endif