KERNEL_ASM_LABEL = mvcvCalcBxBy_asm
CXXFLAGS += -std=c++11
USES_OPENCV = yes

MVCV_KERNELS_DEPS = conv3x3fp32Scharr calcG calcBxBy bilinearInterpolation_u16

include ../../../shared/unittest/test_common.mk
