///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "testHwEdgeOperator.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt8      DDR_DATA TestHwEdgeOperator_dmaIn0_buffer[SIPP_HW_EDGE_OP_BUFFER_WIDTH* SIPP_HW_EDGE_OP_BUFFER_HEIGHT* SIPP_HW_EDGE_OP_BUFFER_NUM_PLANES]ALIGNED(8);
UInt8      DDR_DATA TestHwEdgeOperator_dmaOut0_buffer[SIPP_HW_EDGE_OP_BUFFER_WIDTH* SIPP_HW_EDGE_OP_BUFFER_HEIGHT* SIPP_HW_EDGE_OP_BUFFER_NUM_PLANES]ALIGNED(8);
	
///
void readTestHwEdgeOperatorInput(TestHwEdgeOperator *pPl)
{
   sippRdFileU8((UInt8*)TestHwEdgeOperator_dmaIn0_buffer,SIPP_HW_EDGE_OP_BUFFER_WIDTH * SIPP_HW_EDGE_OP_BUFFER_HEIGHT * SIPP_HW_EDGE_OP_BUFFER_NUM_PLANES* sizeof(UInt8),"../../../../../../../resources/testIMG_1296x972_P400.rgb");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeTestHwEdgeOperatorOutput(TestHwEdgeOperator *pPl)
{
   sippWrFileU8((UInt8*)TestHwEdgeOperator_dmaOut0_buffer,SIPP_HW_EDGE_OP_BUFFER_WIDTH * SIPP_HW_EDGE_OP_BUFFER_HEIGHT * SIPP_HW_EDGE_OP_BUFFER_NUM_PLANES* sizeof(UInt8),"edgeOpTestOut.rgb");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildTestHwEdgeOperator(TestHwEdgeOperator *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_EDGE_OP_BUFFER_WIDTH, SIPP_HW_EDGE_OP_BUFFER_HEIGHT, N_PL(SIPP_HW_EDGE_OP_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->edgeoperatorMa2x5x0 =  sippCreateFilter(pPl->pl, 0x0,        SIPP_HW_EDGE_OP_BUFFER_WIDTH, SIPP_HW_EDGE_OP_BUFFER_HEIGHT, N_PL(SIPP_HW_EDGE_OP_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_EDGE_OP_ID,    0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_EDGE_OP_BUFFER_WIDTH, SIPP_HW_EDGE_OP_BUFFER_HEIGHT, N_PL(SIPP_HW_EDGE_OP_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->edgeoperatorMa2x5x0, pPl->dmaIn0,        3,3                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->edgeoperatorMa2x5x0, 1,1                 );
	
}

  
void configTestHwEdgeOperator(TestHwEdgeOperator *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   EdgeParam           *edgeoperatorMa2x5x0Cfg= (EdgeParam        *)pPl->edgeoperatorMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   edgeoperatorMa2x5x0Cfg->cfg=EDGE_OPERATOR_CFG(INPUT_MODE, OUTPUT_MODE, THETA_MODE, MAGN_SCALE_FACT, THETA_OVX);
   edgeoperatorMa2x5x0Cfg->xCoeff=( 1 & 0x1f) | (-1 & 0x1f) << 5 | ( 2 & 0x1f) << 10 | (-2 & 0x1f) << 15 | ( 1 & 0x1f) << 20 | (-1 & 0x1f) << 25;
   edgeoperatorMa2x5x0Cfg->yCoeff=( 1 & 0x1f) | ( 2 & 0x1f) << 5 | ( 1 & 0x1f) << 10 | (-1 & 0x1f) << 15 | (-2 & 0x1f) << 20 | (-1 & 0x1f) << 25;
   dmaIn0Cfg->ddrAddr   = (UInt32)&TestHwEdgeOperator_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwEdgeOperator_dmaOut0_buffer;
  
  
}
