///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __TESTHWEDGEOPERATOR_H__
#define __TESTHWEDGEOPERATOR_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "testHwEdgeOperatorSetup.h"


//The full-frame buffers
extern UInt8 DDR_DATA TestHwEdgeOperator_dmaIn0_buffer[ SIPP_HW_EDGE_OP_BUFFER_WIDTH * SIPP_HW_EDGE_OP_BUFFER_HEIGHT * SIPP_HW_EDGE_OP_BUFFER_NUM_PLANES ]ALIGNED(8);
extern UInt8 DDR_DATA TestHwEdgeOperator_dmaOut0_buffer[ SIPP_HW_EDGE_OP_BUFFER_WIDTH * SIPP_HW_EDGE_OP_BUFFER_HEIGHT * SIPP_HW_EDGE_OP_BUFFER_NUM_PLANES ]ALIGNED(8);
	
///

typedef struct TestHwEdgeOperator
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut0;
	SippFilter *edgeoperatorMa2x5x0;

} TestHwEdgeOperator;

void readTestHwEdgeOperatorInput(TestHwEdgeOperator *pPl);
void writeTestHwEdgeOperatorOutput(TestHwEdgeOperator *pPl);

void buildTestHwEdgeOperator(TestHwEdgeOperator *pPl);
void configTestHwEdgeOperator(TestHwEdgeOperator *pPl);


#endif