///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "testHwDoGLTM.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt8      DDR_DATA TestHwDoGLTM_dmaIn0_buffer[1584     * 1290    * 1  ]ALIGNED(8);
UInt8      DDR_DATA TestHwDoGLTM_dmaOut0_buffer[1584     * 1290    * 1  ]ALIGNED(8);
	
///
void readTestHwDoGLTMInput(TestHwDoGLTM *pPl)
{
   sippRdFileU8((UInt8*)TestHwDoGLTM_dmaIn0_buffer,1584       * 1290    * 1 * sizeof(UInt8),"../../../../../../../resources/OCT_1584x1290_I_dogltm_8bpp.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeTestHwDoGLTMOutput(TestHwDoGLTM *pPl)
{
   sippWrFileU8((UInt8*)TestHwDoGLTM_dmaOut0_buffer,1584       * 1290    * 1 * sizeof(UInt8),"dogLtmOutput_8bit_1584x1290.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildTestHwDoGLTM(TestHwDoGLTM *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 0, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       1584,   1290,   N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->dogLtmMa2x5x0   =  sippCreateFilter(pPl->pl, 0x0,        1584,   1290,   N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DOGL_ID,       0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       1584,   1290,   N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->dogLtmMa2x5x0, pPl->dmaIn0,        15,15               );
   sippLinkFilter(pPl->dmaOut0,       pPl->dogLtmMa2x5x0, 1,1                 );
	
}

  
void configTestHwDoGLTM(TestHwDoGLTM *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   DogLtmParam         *dogLtmMa2x5x0Cfg   = (DogLtmParam      *)pPl->dogLtmMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   dogLtmMa2x5x0Cfg->cfg=   DOGL_CFG_SET(MODE,DOG_THR,DOG_OUTPUT_CLAMP,DS_MODE,LTM_THR,0,DOG_HEIGHT);
   dogLtmMa2x5x0Cfg->dogCoeffs11=KCSet0;
   dogLtmMa2x5x0Cfg->dogCoeffs15=KCSet1;
   dogLtmMa2x5x0Cfg->dogStrength=0xFF;
   dogLtmMa2x5x0Cfg->ltmCurves=(u16 *)ltm_curves;
   dmaIn0Cfg->ddrAddr   = (UInt32)&TestHwDoGLTM_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwDoGLTM_dmaOut0_buffer;
  
  
}
