///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "BayerISPModel.h"

#include <include/sippHwDefs.h>
#include <filters/negative/negative.h>


//The full-frame buffers
UInt8      DDR_DATA BayerISPModel_dmaIn0_buffer[522      * 128     * 1  ]ALIGNED(8);
UInt8      DDR_DATA BayerISPModel_dmaOut1_buffer[522      * 128     * 1  ]ALIGNED(8);
	
///
void readBayerISPModelInput(BayerISPModel *pPl)
{
   sippRdFileU8((UInt8*)BayerISPModel_dmaIn0_buffer,522        * 128     * 1 * sizeof(UInt8),"../../../resources/test_522x128.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeBayerISPModelOutput(BayerISPModel *pPl)
{
   sippWrFileU8((UInt8*)BayerISPModel_dmaOut1_buffer,522        * 128     * 1 * sizeof(UInt8),"test_neg_522x128.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildBayerISPModel(BayerISPModel *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(4, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       522,    128,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->negative0       =  sippCreateFilter(pPl->pl, 0x0,        522,    128,    N_PL(1),  SZ(UInt8), 0,                  SVU_SYM(svuNegative),         0);
   pPl->dmaOut1         =  sippCreateFilter(pPl->pl, 0x00,       522,    128,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->negative0,     pPl->dmaIn0,        1,1                 );
   sippLinkFilter(pPl->dmaOut1,       pPl->negative0,     1,1                 );
	
}

  
void configBayerISPModel(BayerISPModel *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   DmaParam            *dmaOut1Cfg         = (DmaParam         *)pPl->dmaOut1->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   dmaIn0Cfg->ddrAddr   = (UInt32)&BayerISPModel_dmaIn0_buffer;
   dmaOut1Cfg->ddrAddr  = (UInt32)&BayerISPModel_dmaOut1_buffer;
  
  
}
