///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "HwConv.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt8      DDR_DATA HwConv_dmaIn0_buffer     [SIPP_HW_CONV_BUFFER_WIDTH* SIPP_HW_CONV_BUFFER_HEIGHT* SIPP_HW_CONV_BUFFER_NUM_PLANES]ALIGNED(8);
UInt8      DDR_DATA HwConv_dmaOut0_buffer    [SIPP_HW_CONV_BUFFER_WIDTH* SIPP_HW_CONV_BUFFER_HEIGHT* SIPP_HW_CONV_BUFFER_NUM_PLANES]ALIGNED(8);
	
///
void readHwConvInput(HwConv *pPl)
{
   sippRdFileU8((UInt8*)HwConv_dmaIn0_buffer,SIPP_HW_CONV_BUFFER_WIDTH * SIPP_HW_CONV_BUFFER_HEIGHT * SIPP_HW_CONV_BUFFER_NUM_PLANES* sizeof(UInt8),"../../../../../../../resources/testIMG_1296x972_P400.rgb");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeHwConvOutput(HwConv *pPl)
{
   sippWrFileU8((UInt8*)HwConv_dmaOut0_buffer,SIPP_HW_CONV_BUFFER_WIDTH * SIPP_HW_CONV_BUFFER_HEIGHT * SIPP_HW_CONV_BUFFER_NUM_PLANES* sizeof(UInt8),"output.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildHwConv(HwConv *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 3, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_CONV_BUFFER_WIDTH, SIPP_HW_CONV_BUFFER_HEIGHT, N_PL(SIPP_HW_CONV_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->convolutionMa2x5x0 =  sippCreateFilter(pPl->pl, 0x0,        SIPP_HW_CONV_BUFFER_WIDTH, SIPP_HW_CONV_BUFFER_HEIGHT, N_PL(SIPP_HW_CONV_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_CONV_ID,       0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_CONV_BUFFER_WIDTH, SIPP_HW_CONV_BUFFER_HEIGHT, N_PL(SIPP_HW_CONV_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->convolutionMa2x5x0, pPl->dmaIn0,        3,3                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->convolutionMa2x5x0, 1,1                 );
	
}

  
void configHwConv(HwConv *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   ConvParam           *convolutionMa2x5x0Cfg= (ConvParam        *)pPl->convolutionMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   convolutionMa2x5x0Cfg->cfg=CONV_CFG(3, 1, 1, 0,1, 0,  0x3646, 1, 0);
   convolutionMa2x5x0Cfg->kernel[0]=0x0;
   convolutionMa2x5x0Cfg->kernel[1]= 0x0;
   convolutionMa2x5x0Cfg->kernel[2]= 0x0;
   convolutionMa2x5x0Cfg->kernel[3]= 0x0;
   convolutionMa2x5x0Cfg->kernel[4]= 0x00003000;
   convolutionMa2x5x0Cfg->kernel[5]= 0x0;
   convolutionMa2x5x0Cfg->kernel[6]= 0x30000000;
   convolutionMa2x5x0Cfg->kernel[7]= 0x30003800;
   convolutionMa2x5x0Cfg->kernel[8]= 0x0;
   convolutionMa2x5x0Cfg->kernel[9]= 0x0;
   convolutionMa2x5x0Cfg->kernel[10]= 0x00003000;
   convolutionMa2x5x0Cfg->kernel[11]= 0x0;
   convolutionMa2x5x0Cfg->kernel[12]= 0x0;
   convolutionMa2x5x0Cfg->kernel[13]= 0x0;
   convolutionMa2x5x0Cfg->kernel[14]= 0x0;
   convolutionMa2x5x0Cfg->shadowKernel[0]=0x0;
   convolutionMa2x5x0Cfg->shadowKernel[1]= 0x0;
   convolutionMa2x5x0Cfg->shadowKernel[2]= 0x0;
   convolutionMa2x5x0Cfg->shadowKernel[3]= 0x0;
   convolutionMa2x5x0Cfg->shadowKernel[4]= 0x00003000;
   convolutionMa2x5x0Cfg->shadowKernel[5]= 0x0;
   convolutionMa2x5x0Cfg->shadowKernel[6]= 0x30000000;
   convolutionMa2x5x0Cfg->shadowKernel[7]= 0x30003800;
   convolutionMa2x5x0Cfg->shadowKernel[8]= 0x0;
   convolutionMa2x5x0Cfg->shadowKernel[9]= 0x0;
   convolutionMa2x5x0Cfg->shadowKernel[10]= 0x00003000;
   convolutionMa2x5x0Cfg->shadowKernel[11]= 0x0;
   convolutionMa2x5x0Cfg->shadowKernel[12]= 0x0;
   convolutionMa2x5x0Cfg->shadowKernel[13]= 0x0;
   convolutionMa2x5x0Cfg->shadowKernel[14]= 0x0;
   dmaIn0Cfg->ddrAddr   = (UInt32)&HwConv_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&HwConv_dmaOut0_buffer;
  
  
}
