/*
 * testHwConvSetup.h
 */

#ifndef LEON_TESTHWCONVSETUP_H_
#define LEON_TESTHWCONVSETUP_H_

#define SIPP_HW_CONV_BUFFER_WIDTH      1296
#define SIPP_HW_CONV_BUFFER_HEIGHT     972
#define SIPP_HW_CONV_BUFFER_NUM_PLANES  1
#define SIPP_HW_CONV_BUFFER_SIZE  (SIPP_HW_CONV_BUFFER_WIDTH * SIPP_HW_CONV_BUFFER_HEIGHT * SIPP_HW_CONV_BUFFER_NUM_PLANES)


#endif /* LEON_TESTHWCONVSETUP_H_ */
