///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __ISPPIPE_H__
#define __ISPPIPE_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "ISPPipeSettings.h"


//The full-frame buffers
extern UInt16 DDR_DATA ISPPipe_dmaIn0_buffer[ SIPP_ISP_PIPE_BUFFER_WIDTH * SIPP_ISP_PIPE_BUFFER_HEIGHT * SIPP_ISP_PIPE_BUFFER_INPUT_NUM_PLANES ]ALIGNED(8);
extern UInt8 DDR_DATA ISPPipe_dmaOut0_buffer[ SIPP_ISP_PIPE_BUFFER_WIDTH * SIPP_ISP_PIPE_BUFFER_HEIGHT * 3 ]ALIGNED(8);
	
///

typedef struct ISPPipe
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *sigmaDnsMa2x5x0;
	SippFilter *lscMa2x5x0;
	SippFilter *rawMa2x5x0;
	SippFilter *debayerMa2x5x0;
	SippFilter *dogLtmMa2x5x0;
	SippFilter *ydnsMa2x5x0;
	SippFilter *sharpenMa2x5x0;
	SippFilter *chromaGenMa2x5x0;
	SippFilter *medianMa2x5x0;
	SippFilter *chromadnsMa2x5x0;
	SippFilter *colorcombMa2x5x0;
	SippFilter *lutMa2x5x0;
	SippFilter *dmaOut0;

} ISPPipe;

void readISPPipeInput(ISPPipe *pPl);
void writeISPPipeOutput(ISPPipe *pPl);

void buildISPPipe(ISPPipe *pPl);
void configISPPipe(ISPPipe *pPl);


#endif