///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __TESTHWPOLYPHASEFIR_H__
#define __TESTHWPOLYPHASEFIR_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "testHwPolyPhaseFIRSetup.h"


//The full-frame buffers
extern UInt8 DDR_DATA TestHwPolyPhaseFIR_dmaIn0_buffer[ SIPP_HW_POLY_FIR_INPUT_BUFFER_WIDTH * SIPP_HW_POLY_FIR_INPUT_BUFFER_HEIGHT * SIPP_HW_POLY_FIR_INPUT_BUFFER_NUM_PLANES ]ALIGNED(8);
extern UInt8 DDR_DATA TestHwPolyPhaseFIR_dmaOut0_buffer[ SIPP_HW_POLY_FIR_OUTPUT_BUFFER_WIDTH * SIPP_HW_POLY_FIR_OUTPUT_BUFFER_HEIGHT * SIPP_HW_POLY_FIR_INPUT_BUFFER_NUM_PLANES ]ALIGNED(8);
	
///

typedef struct TestHwPolyPhaseFIR
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut0;
	SippFilter *polyphasefirMa2x5x0;

} TestHwPolyPhaseFIR;

void readTestHwPolyPhaseFIRInput(TestHwPolyPhaseFIR *pPl);
void writeTestHwPolyPhaseFIROutput(TestHwPolyPhaseFIR *pPl);

void buildTestHwPolyPhaseFIR(TestHwPolyPhaseFIR *pPl);
void configTestHwPolyPhaseFIR(TestHwPolyPhaseFIR *pPl);


#endif