/* usbpump_hcd_raw_api.h	Wed May 19 2010 12:56:31 chwon */

/*

Module:  usbpump_hcd_raw_api.h

Function:
	Definition of USBPUMP_HCD_RAW_API

Version:
	V3.01c	Wed May 19 2010 12:56:31 chwon	Edit level 3

Copyright notice:
	This file copyright (C) 2010 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	ChaeHee Won, MCCI Corporation	April 2010

Revision history:
   3.01c  Thu Apr 22 2010 13:31:37 chwon
	10182: Module created.

   3.01c  Thu Apr 22 2010 16:08:13  chwon
	10076: Add USBPUMP_HCD_RAW_API_GET_PORT_STATUS_FN.

   3.01c  Wed May 19 2010 12:56:31  chwon
	10182, 10076: Remove USBPUMP_HCD_RAW_API_GET_PORT_STATUS_FN and
	add USBPUMP_HCD_RAW_API_CLOSE_FN.

*/

#ifndef _USBPUMP_HCD_RAW_API_H_		/* prevent multiple includes */
#define _USBPUMP_HCD_RAW_API_H_

#ifndef _USBPUMP_HCD_TYPES_H_
# include "usbpump_hcd_types.h"
#endif

#ifndef _USBPUMP_USBDI_TYPES_H_
# include "usbpump_usbdi_types.h"
#endif

/****************************************************************************\
|
|	HCD Raw API types
|
\****************************************************************************/

__TMS_TYPE_DEF_HANDLE(USBPUMP_HCD_RAW_API_HANDLE);

/*

Type:	USBPUMP_HCD_RAW_API_CLOSE_FN

Index:	Type:	PUSBPUMP_HCD_RAW_API_CLOSE_FN

Function:
	Close raw API

Definition:
	VOID USBPUMP_HCD_RAW_API_CLOSE_FN(
		USBPUMP_HCD_RAW_API_HANDLE hRawApiHandle
		);

Description:
	Close raw api with hRawApiHandle.

Returns:
	None.

*/

__TMS_FNTYPE_DEF(
USBPUMP_HCD_RAW_API_CLOSE_FN,
__TMS_VOID,
	(
	__TMS_USBPUMP_HCD_RAW_API_HANDLE	/* hRawApiHandle */
	));

/*

Type:	USBPUMP_HCD_RAW_API_GET_FRAME_FN

Index:	Type:	PUSBPUMP_HCD_RAW_API_GET_FRAME_FN

Function:
	Get frame number

Definition:
	UINT32 MCCIUSBD_BUSIFFN_API_M_GET_FRAME_NUMBER(
		USBPUMP_HCD_RAW_API_HANDLE hRawApiHandle,
		BOOL fStandardFrameNumber,
		USTAT *pStat
		);

Description:
	Returns current frame number. If fStandardFrameNumber is TRUE, it will
	return the "standard" frame count, in milliseconds (always compatible
	with full speed).  If fStandardFrameNumber is FALSE, it will return
	the microframe count.

Returns:
	Current frame number

*/

__TMS_FNTYPE_DEF(
USBPUMP_HCD_RAW_API_GET_FRAME_FN,
__TMS_UINT32,					/* frame number */
	(
	__TMS_USBPUMP_HCD_RAW_API_HANDLE	/* hRawApiHandle */,
	__TMS_BOOL				/* fStandardFrameNumber */,
	__TMS_USTAT *				/* pStat */
	));


__TMS_TYPE_DEF_STRUCT  (USBPUMP_HCD_RAW_API_SWITCH);
struct __TMS_STRUCTNAME(USBPUMP_HCD_RAW_API_SWITCH)
	{
	__TMS_USBPUMP_HCD_RAW_API_CLOSE_FN *		pCloseFn;
	__TMS_USBPUMP_HCD_RAW_API_GET_FRAME_FN *	pGetFrameFn;
	};


#define	__TMS_USBPUMP_HCD_RAW_API_SWITCH_INIT_V1(			\
	a_pCloseFn,							\
	a_pGetFrameFn							\
	)								\
	{								\
	(a_pCloseFn),							\
	(a_pGetFrameFn)							\
	}

#define	__TMS_USBPUMP_HCD_RAW_API_SWITCH_SETUP_V1(			\
	a_pSwitch,							\
	a_pCloseFn,							\
	a_pGetFrameFn							\
	)								\
    do	{								\
	(a_pSwitch)->pCloseFn = (a_pCloseFn);				\
	(a_pSwitch)->pGetFrameFn = (a_pGetFrameFn);			\
	} while (0)


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_HCD_RAW_API_SWITCH_INIT_V1(			\
	a_pCloseFn,							\
	a_pGetFrameFn							\
	)	\
	__TMS_USBPUMP_HCD_RAW_API_SWITCH_INIT_V1(			\
	a_pCloseFn,							\
	a_pGetFrameFn							\
	)
# define USBPUMP_HCD_RAW_API_SWITCH_SETUP_V1(			\
	a_pSwitch,							\
	a_pCloseFn,							\
	a_pGetFrameFn							\
	)	\
	__TMS_USBPUMP_HCD_RAW_API_SWITCH_SETUP_V1(			\
	a_pSwitch,							\
	a_pCloseFn,							\
	a_pGetFrameFn							\
	)
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpump_hcd_raw_api.h ****/
#endif /* _USBPUMP_HCD_RAW_API_H_ */
