/* usbpump_classkit_class.h	Thu Jul 17 2008 11:46:50 chwon */

/*

Module:  usbpump_classkit_class.h

Function:
	Definitions related to USBPUMP_CLASSKIT_CLASS objects.

Version:
	V1.97k	Thu Jul 17 2008 11:46:50 chwon	Edit level 3

Copyright notice:
	This file copyright (C) 2008 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	ChaeHee Won, MCCI Corporation	April 2008

Revision history:
   1.97k  Tue Apr 01 2008 12:03:28 chwon
	Module created.

   1.97k  Tue Jul 01 2008 12:49:47  chwon
	4257: fix typo from USBPUMP_CLASSKIT_INIT_FUNCTIOIN_INCALL_FN to
	USBPUMP_CLASSKIT_INIT_FUNCTION_INCALL_FN.

   1.97k  Thu Jul 17 2008 11:46:50  chwon
	4301: remove pRegisterSessionHead.
	4250: use generic INCALL and OUTCALL definition.

*/

#ifndef _USBPUMP_CLASSKIT_CLASS_H_	/* prevent multiple includes */
#define _USBPUMP_CLASSKIT_CLASS_H_

#ifndef _USBPUMP_USBDI_CLASS_H_
# include "usbpump_usbdi_class.h"
#endif

#ifndef _USBPUMP_CLASSKIT_SESSION_H_
# include "usbpump_classkit_session.h"
#endif

/****************************************************************************\
|
|	The USBDI ClassKit driver class object
|
\****************************************************************************/

__TMS_FNTYPE_DEF(
USBPUMP_CLASSKIT_INIT_FUNCTION_INCALL_FN,
__TMS_BOOL,
	(
	__TMS_USBPUMP_CLASSKIT_CLASS *		/* pDriverClass */,
	__TMS_USBPUMP_CLASSKIT_FUNCTION *	/* pFunction */,
	__TMS_USBPUMP_CLASSKIT_FUNCTION_INCALL */* pInCallBuffer */,
	__TMS_RECSIZE				/* sizeInCallBuffer */
	));

struct __TMS_STRUCTNAME	(USBPUMP_CLASSKIT_CLASS_CONTENTS)
	{
	__TMS_USBPUMP_USBDI_DRIVER_CLASS_CONTENTS__STRUCT;

	__TMS_CONST __TMS_USBGUID *			pGuid;
	__TMS_USBPUMP_CLASSKIT_INIT_FUNCTION_INCALL_FN *pInitFunctionIncallFn;
	__TMS_BYTES					sizeConfigTree;

	__TMS_USBPUMP_CLASSKIT_SESSION *		pFreeSessionHead;
	__TMS_USBPUMP_CLASSKIT_SESSION *		pOpenSessionHead;
	};

union __TMS_UNIONNAME	(USBPUMP_CLASSKIT_CLASS)
	{
	__TMS_USBPUMP_USBDI_DRIVER_CLASS_CONTENTS__UNION;
	__TMS_USBPUMP_CLASSKIT_CLASS_CONTENTS	ClassKit;
	};

#define	__TMS_USBPUMP_CLASSKIT_CLASS_CONTENTS__STRUCT		\
	__TMS_USBPUMP_CLASSKIT_CLASS_CONTENTS	ClassKit

#define	__TMS_USBPUMP_CLASSKIT_CLASS_CONTENTS__UNION		\
	__TMS_USBPUMP_USBDI_DRIVER_CLASS_CONTENTS__UNION;	\
	__TMS_USBPUMP_CLASSKIT_CLASS_CONTENTS	ClassKit;	\
	__TMS_USBPUMP_CLASSKIT_CLASS		ClassKitCast


#define __TMS_USBPUMP_OBJECT_HEADER_TO_CLASSKIT_DRIVER_CLASS(pObject)	\
	((__TMS_USBPUMP_CLASSKIT_CLASS *) &(pObject)->Tag)


/****************************************************************************\
|
|	API functions
|
\****************************************************************************/

__TMS_BEGIN_DECLS

__TMS_BOOL
UsbPumpClassKitI_InitDriverClass_V1(
	__TMS_USBPUMP_CLASSKIT_CLASS *			pDriverClass,
	__TMS_CONST __TMS_USBGUID *			pGuid,
	__TMS_USBPUMP_CLASSKIT_INIT_FUNCTION_INCALL_FN *pInitFunctionIncallFn,
	__TMS_UINT					MaxSession,
	__TMS_BYTES					sizeConfigTree
	);

__TMS_USBPUMP_IOCTL_RESULT
UsbPumpClassKitI_OpenSession(
	__TMS_USBPUMP_CLASSKIT_CLASS *			pDriverClass,
	__TMS_CONST __TMS_VOID *			pInParam,
	__TMS_VOID *					pOutParam,
	__TMS_CONST __TMS_VOID *			pvInCalls,
	__TMS_RECSIZE					sizeInCalls
	);

__TMS_VOID
UsbPumpClassKitI_SendNotification(
	__TMS_USBPUMP_CLASSKIT_CLASS *			pDriverClass,
	__TMS_USBPUMP_CLASSKIT_NOTIFICATION		NotificationId,
	__TMS_CONST __TMS_VOID *			pNotificationInfo,
	__TMS_BYTES					sizeNotificationInfo
	);

/*
|| UsbPumpClassKitI_ClassIoctl is sample code. Driver class should implement
|| own IOCTL handler based on this.
*/
__TMS_USBPUMP_OBJECT_CLASS_IOCTL_FN
UsbPumpClassKitI_ClassIoctl;

__TMS_END_DECLS


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_CLASSKIT_CLASS_CONTENTS__STRUCT	\
   __TMS_USBPUMP_CLASSKIT_CLASS_CONTENTS__STRUCT
# define USBPUMP_CLASSKIT_CLASS_CONTENTS__UNION	\
   __TMS_USBPUMP_CLASSKIT_CLASS_CONTENTS__UNION
# define USBPUMP_OBJECT_HEADER_TO_CLASSKIT_DRIVER_CLASS(pObject)	\
   __TMS_USBPUMP_OBJECT_HEADER_TO_CLASSKIT_DRIVER_CLASS(pObject)
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpump_classkit_class.h ****/
#endif /* _USBPUMP_CLASSKIT_CLASS_H_ */
