/* usbpump_hcd_timings.h	Fri Feb 24 2006 22:11:14 tmm */

/*

Module:  usbpump_hcd_timings.h

Function:
	Sample (default) timing values for HCDs to use in preparing
	the result of USBPUMP_IOCTL_HCD_GET_SCHEDULE_PARAMS.

Version:
	V1.93e	Fri Feb 24 2006 22:11:14 tmm	Edit level 1

Copyright notice:
	This file copyright (C) 2006 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.
	
	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation.
 
Author:
	Terry Moore, MCCI Corporation	February 2006

Revision history:
   1.93e  Fri Feb 24 2006 22:11:14  tmm
	Module created.

*/

#ifndef _USBPUMP_HCD_TIMINGS_H_		/* prevent multiple includes */
#define _USBPUMP_HCD_TIMINGS_H_

/****************************************************************************\
|
|	The timing parameters
|
\****************************************************************************/

#define	__TMS_USBPUMP_HCD_TIMING_SCHEDULE_LEVELS	6
#define	__TMS_USBPUMP_HCD_TIMING_SCHEDULE_LEVELS_MAX	6

#define	__TMS_USBPUMP_HCD_TIMING_LS_HUB_SETUP_CLOCKS	4
#define	__TMS_USBPUMP_HCD_TIMING_LS_HOST_DELAY_CLOCKS	8
#define	__TMS_USBPUMP_HCD_TIMING_FS_HOST_DELAY_CLOCKS	8
#define	__TMS_USBPUMP_HCD_TIMING_HS_HOST_DELAY_CLOCKS	8
#define	__TMS_USBPUMP_HCD_TIMING_FS_MAX_PERIODIC_CLOCKS	10800
#define	__TMS_USBPUMP_HCD_TIMING_HS_MAX_PERIODIC_CLOCKS	48000

/****************************************************************************\
|
|	uncloaked definitions
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_HCD_TIMING_SCHEDULE_LEVELS	\
   __TMS_USBPUMP_HCD_TIMING_SCHEDULE_LEVELS
# define USBPUMP_HCD_TIMING_SCHEDULE_LEVELS_MAX	\
   __TMS_USBPUMP_HCD_TIMING_SCHEDULE_LEVELS_MAX
# define USBPUMP_HCD_TIMING_LS_HUB_SETUP_CLOCKS	\
   __TMS_USBPUMP_HCD_TIMING_LS_HUB_SETUP_CLOCKS
# define USBPUMP_HCD_TIMING_LS_HOST_DELAY_CLOCKS	\
   __TMS_USBPUMP_HCD_TIMING_LS_HOST_DELAY_CLOCKS
# define USBPUMP_HCD_TIMING_FS_HOST_DELAY_CLOCKS	\
   __TMS_USBPUMP_HCD_TIMING_FS_HOST_DELAY_CLOCKS
# define USBPUMP_HCD_TIMING_HS_HOST_DELAY_CLOCKS	\
   __TMS_USBPUMP_HCD_TIMING_HS_HOST_DELAY_CLOCKS
# define USBPUMP_HCD_TIMING_FS_MAX_PERIODIC_CLOCKS	\
   __TMS_USBPUMP_HCD_TIMING_FS_MAX_PERIODIC_CLOCKS
# define USBPUMP_HCD_TIMING_HS_MAX_PERIODIC_CLOCKS	\
   __TMS_USBPUMP_HCD_TIMING_HS_MAX_PERIODIC_CLOCKS
#endif /* !__TMS_CLOAKED_NAMES_ONLY */


/**** end of usbpump_hcd_timings.h ****/
#endif /* _USBPUMP_HCD_TIMINGS_H_ */
