/* usbpump_usbdi_composite.h	Fri Mar 14 2008 13:03:31 chwon */

/*

Module:  usbpump_usbdi_composite.h

Function:
	Information related to the composite driver

Version:
	V1.97k	Fri Mar 14 2008 13:03:31 chwon	Edit level 1

Copyright notice:
	This file copyright (C) 2008 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	ChaeHee Won, MCCI Corporation	March 2008

Revision history:
   1.97k  Fri Mar 14 2008 13:03:31 chwon
	Module created.

*/

#ifndef _USBPUMP_USBDI_COMPOSITE_H_		/* prevent multiple includes */
#define _USBPUMP_USBDI_COMPOSITE_H_

#ifndef _USBPUMP_USBDI_CLASS_H_
# include "usbpump_usbdi_class.h"
#endif

#ifndef _USBPUMP_USBDI_FUNCTION_H_
# include "usbpump_usbdi_function.h"
#endif

/****************************************************************************\
|
|	Define the partial pattern for matching the "composite driver".
|
\****************************************************************************/

#define __TMS_USBPUMP_USBDI_COMPOSITE_COMPOSITE_DEVICE_CLASS	0xef
#define __TMS_USBPUMP_USBDI_COMPOSITE_COMPOSITE_DEVICE_SUBCLASS	0x02
#define __TMS_USBPUMP_USBDI_COMPOSITE_COMPOSITE_DEVICE_PROTO	0x01

/* the base string -- must match with above definition */
#define	__TMS_USBPUMP_USBDI_COMPOSITE_DEVICE_CSP	"dc=ef/02/01"

/* the canonical match string for the composite driver */
#define	__TMS_USBPUMP_USBDI_COMPOSITE_MATCH_STRING	\
	"*;" __TMS_USBPUMP_USBDI_COMPOSITE_DEVICE_CSP ";"


/****************************************************************************\
|
|	Define the composite driver class and function name
|
\****************************************************************************/

#define	__TMS_USBPUMP_USBDI_DRIVER_CLASS_COMPOSITE_NAME	\
	__TMS_USBPUMP_USBDI_DRIVER_CLASS_NAME("composite")

#define	__TMS_USBPUMP_USBDI_FUNCTION_COMPOSITE_NAME	\
	__TMS_USBPUMP_USBDI_FUNCTION_NAME("composite")


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_USBDI_COMPOSITE_COMPOSITE_DEVICE_CLASS	\
   __TMS_USBPUMP_USBDI_COMPOSITE_COMPOSITE_DEVICE_CLASS
# define USBPUMP_USBDI_COMPOSITE_COMPOSITE_DEVICE_SUBCLASS	\
   __TMS_USBPUMP_USBDI_COMPOSITE_COMPOSITE_DEVICE_SUBCLASS
# define USBPUMP_USBDI_COMPOSITE_COMPOSITE_DEVICE_PROTO	\
   __TMS_USBPUMP_USBDI_COMPOSITE_COMPOSITE_DEVICE_PROTO
# define USBPUMP_USBDI_COMPOSITE_DEVICE_CSP	\
   __TMS_USBPUMP_USBDI_COMPOSITE_DEVICE_CSP
# define USBPUMP_USBDI_COMPOSITE_MATCH_STRING	\
   __TMS_USBPUMP_USBDI_COMPOSITE_MATCH_STRING
# define USBPUMP_USBDI_DRIVER_CLASS_COMPOSITE_NAME	\
   __TMS_USBPUMP_USBDI_DRIVER_CLASS_COMPOSITE_NAME
# define USBPUMP_USBDI_FUNCTION_COMPOSITE_NAME	\
   __TMS_USBPUMP_USBDI_FUNCTION_COMPOSITE_NAME
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpump_usbdi_composite.h ****/
#endif /* _USBPUMP_USBDI_COMPOSITE_H_ */
