/* usbpump_usbdi_power_state.h	Fri Mar 30 2012 10:17:33 cccho */

/*

Module:  usbpump_usbdi_power_state.h

Function:
	Definition of power state

Version:
	V3.01f	Fri Mar 30 2012 10:17:33 cccho	Edit level 4

Copyright notice:
	This file copyright (C) 2010-2012 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	ChaeHee Won, MCCI Corporation	August 2010

Revision history:
   3.01c  Mon Aug 16 2010 11:25:43 chwon
	10988: Module created.

   3.01d  Thu Mar 10 2011 23:35:17  chwon
	12923: add power action value definition.

   3.01d  Tue Apr 05 2011 14:29:58  chwon
	13048: add power action -- USBPUMP_USBDI_POWER_ACTION_RESTART.

   3.01f  Fri Mar 30 2012 10:17:33  cccho
	15053: use usbpump common power type to define usbpump usbdi power
	types.

*/

#ifndef _USBPUMP_USBDI_POWER_STATE_H_	/* prevent multiple includes */
#define _USBPUMP_USBDI_POWER_STATE_H_

#ifndef _USBPUMP_USBDI_TYPES_H_
# include "usbpump_usbdi_types.h"
#endif

#ifndef _USBPUMP_POWER_STATE_H_
# include "usbpump_power_state.h"
#endif

/****************************************************************************\
|
|	USBDI power state
|
\****************************************************************************/

#define	__TMS_USBPUMP_USBDI_POWER_STATE_D0	\
		__TMS_USBPUMP_POWER_STATE_D0	/* the working state */
#define	__TMS_USBPUMP_USBDI_POWER_STATE_D1	\
		__TMS_USBPUMP_POWER_STATE_D1	/* intermediate sleep */
#define	__TMS_USBPUMP_USBDI_POWER_STATE_D2	\
		__TMS_USBPUMP_POWER_STATE_D2	/* intermediate sleep */
#define	__TMS_USBPUMP_USBDI_POWER_STATE_D3	\
		__TMS_USBPUMP_POWER_STATE_D3	/* the deepest sleep */


/****************************************************************************\
|
|	USBDI power action
|
\****************************************************************************/

#define	__TMS_USBPUMP_USBDI_POWER_ACTION_NONE		\
		__TMS_USBPUMP_POWER_ACTION_NONE
#define	__TMS_USBPUMP_USBDI_POWER_ACTION_SLEEP		\
		__TMS_USBPUMP_POWER_ACTION_SLEEP
#define	__TMS_USBPUMP_USBDI_POWER_ACTION_HIBERNATE	\
		__TMS_USBPUMP_POWER_ACTION_HIBERNATE
#define	__TMS_USBPUMP_USBDI_POWER_ACTION_SHUTDOWN	\
		__TMS_USBPUMP_POWER_ACTION_SHUTDOWN
#define	__TMS_USBPUMP_USBDI_POWER_ACTION_RESTART	\
		__TMS_USBPUMP_POWER_ACTION_RESTART


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_USBDI_POWER_STATE_D0	\
   __TMS_USBPUMP_USBDI_POWER_STATE_D0
# define USBPUMP_USBDI_POWER_STATE_D1	\
   __TMS_USBPUMP_USBDI_POWER_STATE_D1
# define USBPUMP_USBDI_POWER_STATE_D2	\
   __TMS_USBPUMP_USBDI_POWER_STATE_D2
# define USBPUMP_USBDI_POWER_STATE_D3	\
   __TMS_USBPUMP_USBDI_POWER_STATE_D3
# define USBPUMP_USBDI_POWER_ACTION_NONE	\
   __TMS_USBPUMP_USBDI_POWER_ACTION_NONE
# define USBPUMP_USBDI_POWER_ACTION_SLEEP	\
   __TMS_USBPUMP_USBDI_POWER_ACTION_SLEEP
# define USBPUMP_USBDI_POWER_ACTION_HIBERNATE	\
   __TMS_USBPUMP_USBDI_POWER_ACTION_HIBERNATE
# define USBPUMP_USBDI_POWER_ACTION_SHUTDOWN	\
   __TMS_USBPUMP_USBDI_POWER_ACTION_SHUTDOWN
# define USBPUMP_USBDI_POWER_ACTION_RESTART	\
   __TMS_USBPUMP_USBDI_POWER_ACTION_RESTART
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpump_usbdi_power_state.h ****/
#endif /* _USBPUMP_USBDI_POWER_STATE_H_ */
