/* usbpump_usbd_class_uvc_config.h	Thu Mar 16 2017 16:55:51 chwon */

/*

Module:  usbpump_usbd_class_uvc_config.h

Function:
	Definition of the USBD Uvc driver configuration

Version:
	V3.19b	Thu Mar 16 2017 16:55:51 chwon	Edit level 1

Copyright notice:
	This file copyright (C) 2017 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	ChaeHee Won, MCCI Corporation	March 2017

Revision history:
   3.19b  Thu Mar 16 2017 16:55:51  chwon
	20517: Module created.

*/

#ifndef _USBPUMP_USBD_CLASS_UVC_CONFIG_H_	/* prevent multiple includes */
#define _USBPUMP_USBD_CLASS_UVC_CONFIG_H_

#ifndef _USBPUMP_USBD_CLASS_UVC_TYPES_H_
# include "usbpump_usbd_class_uvc_types.h"
#endif

/****************************************************************************\
|
|	The USBD Uvc Class Driver Configuration
|
\****************************************************************************/

struct __TMS_STRUCTNAME	(USBPUMP_USBDI_CLASS_UVC_CONFIG)
	{
	__TMS_UINT32			MagicBegin;

	/*
	|| Number of maximum sessions -- it should include OpenSession and
	|| OpenFunction session.
	*/
	__TMS_UINT			MaxSession;
	__TMS_UINT			ControlBufferSize;

	/* put uvc driver configuration info if required. */

	__TMS_UINT32			MagicEnd;
	};


#define	__TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_MAGIC_BEGIN	\
	__TMS_UHIL_MEMTAG('<', 'T', 's', 'd')

#define	__TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_MAGIC_END		\
	__TMS_UHIL_MEMTAG('>', 'T', 's', 'd')

#define	__TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_INIT_V1(		\
	a_MaxSession,						\
	a_ControlBufferSize					\
	)							\
	{							\
	__TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_MAGIC_BEGIN,	\
	(a_MaxSession),						\
	(a_ControlBufferSize),					\
	__TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_MAGIC_END		\
	}

#define	__TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_SETUP_V1(			\
	a_pConfig,							\
	a_MaxSession,							\
	a_ControlBufferSize						\
	)								\
    do	{								\
	(a_pConfig)->MagicBegin =					\
		__TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_MAGIC_BEGIN;	\
	(a_pConfig)->MaxSession = a_MaxSession;				\
	(a_pConfig)->ControlBufferSize = a_ControlBufferSize;		\
	(a_pConfig)->MagicEnd =						\
		__TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_MAGIC_END;		\
	} while (0)


/****************************************************************************\
|
|	Default linkage
|
\****************************************************************************/

__TMS_BEGIN_DECLS

extern
__TMS_CONST
__TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG
gk_UsbPumpUsbdiUvc_ConfigDefault;

__TMS_END_DECLS


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_USBDI_CLASS_UVC_CONFIG_MAGIC_BEGIN	\
   __TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_MAGIC_BEGIN
# define USBPUMP_USBDI_CLASS_UVC_CONFIG_MAGIC_END	\
   __TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_MAGIC_END
# define USBPUMP_USBDI_CLASS_UVC_CONFIG_INIT_V1(		\
	a_MaxSession,						\
	a_ControlBufferSize					\
	)	\
	__TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_INIT_V1(		\
	a_MaxSession,						\
	a_ControlBufferSize					\
	)
# define USBPUMP_USBDI_CLASS_UVC_CONFIG_SETUP_V1(			\
	a_pConfig,							\
	a_MaxSession,							\
	a_ControlBufferSize						\
	)	\
	__TMS_USBPUMP_USBDI_CLASS_UVC_CONFIG_SETUP_V1(			\
	a_pConfig,							\
	a_MaxSession,							\
	a_ControlBufferSize						\
	)
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpump_usbd_class_uvc_config.h ****/
#endif /* _USBPUMP_USBD_CLASS_UVC_CONFIG_H_ */
