///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __TESTHWCOLORCOMB_H__
#define __TESTHWCOLORCOMB_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "testHwColorCombSetup.h"


//The full-frame buffers
extern UInt8 DDR_DATA TestHwColorComb_dmaIn0_buffer[ SIPP_HW_COL_COMB_LUMA_BUFFER_WIDTH * SIPP_HW_COL_COMB_LUMA_BUFFER_HEIGHT * SIPP_HW_COL_COMB_LUMA_BUFFER_NUM_PLANES ]ALIGNED(8);
extern UInt8 DDR_DATA TestHwColorComb_dmaIn1_buffer[ SIPP_HW_COL_COMB_CHR_BUFFER_WIDTH * SIPP_HW_COL_COMB_CHR_BUFFER_HEIGHT * SIPP_HW_COL_COMB_CHR_BUFFER_NUM_PLANES ]ALIGNED(8);
extern UInt16 DDR_DATA TestHwColorComb_dmaOut0_buffer[ SIPP_HW_COL_COMB_BUFFER_WIDTH * SIPP_HW_COL_COMB_BUFFER_HEIGHT * SIPP_HW_COL_COMB_BUFFER_NUM_PLANES ]ALIGNED(8);
	
///

typedef struct TestHwColorComb
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *colorcombMa2x5x0;
	SippFilter *dmaIn1;
	SippFilter *dmaOut0;

} TestHwColorComb;

void readTestHwColorCombInput(TestHwColorComb *pPl);
void writeTestHwColorCombOutput(TestHwColorComb *pPl);

void buildTestHwColorComb(TestHwColorComb *pPl);
void configTestHwColorComb(TestHwColorComb *pPl);


#endif