///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "testHwColorComb.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt8      DDR_DATA TestHwColorComb_dmaIn0_buffer[SIPP_HW_COL_COMB_LUMA_BUFFER_WIDTH* SIPP_HW_COL_COMB_LUMA_BUFFER_HEIGHT* SIPP_HW_COL_COMB_LUMA_BUFFER_NUM_PLANES]ALIGNED(8);
UInt8      DDR_DATA TestHwColorComb_dmaIn1_buffer[SIPP_HW_COL_COMB_CHR_BUFFER_WIDTH* SIPP_HW_COL_COMB_CHR_BUFFER_HEIGHT* SIPP_HW_COL_COMB_CHR_BUFFER_NUM_PLANES]ALIGNED(8);
UInt16     DDR_DATA TestHwColorComb_dmaOut0_buffer[SIPP_HW_COL_COMB_BUFFER_WIDTH* SIPP_HW_COL_COMB_BUFFER_HEIGHT* SIPP_HW_COL_COMB_BUFFER_NUM_PLANES]ALIGNED(8);
	
///
void readTestHwColorCombInput(TestHwColorComb *pPl)
{
   sippRdFileU8((UInt8*)TestHwColorComb_dmaIn0_buffer,SIPP_HW_COL_COMB_LUMA_BUFFER_WIDTH * SIPP_HW_COL_COMB_LUMA_BUFFER_HEIGHT * SIPP_HW_COL_COMB_LUMA_BUFFER_NUM_PLANES* sizeof(UInt8),"../../../../../../../resources/OCT_1584x1290_I_Chroma_block__luma_8bpp.raw");
   sippRdFileU8((UInt8*)TestHwColorComb_dmaIn1_buffer,SIPP_HW_COL_COMB_CHR_BUFFER_WIDTH * SIPP_HW_COL_COMB_CHR_BUFFER_HEIGHT * SIPP_HW_COL_COMB_CHR_BUFFER_NUM_PLANES* sizeof(UInt8),"../../../../../../../resources/OCT_792x645_I_chroma_block__chroma_8bpp.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeTestHwColorCombOutput(TestHwColorComb *pPl)
{
   sippWrFileU8((UInt8*)TestHwColorComb_dmaOut0_buffer,SIPP_HW_COL_COMB_BUFFER_WIDTH * SIPP_HW_COL_COMB_BUFFER_HEIGHT * SIPP_HW_COL_COMB_BUFFER_NUM_PLANES* sizeof(UInt16),"colorCombOutput.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildTestHwColorComb(TestHwColorComb *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_COL_COMB_LUMA_BUFFER_WIDTH, SIPP_HW_COL_COMB_LUMA_BUFFER_HEIGHT, N_PL(SIPP_HW_COL_COMB_LUMA_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->dmaIn1          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_COL_COMB_CHR_BUFFER_WIDTH, SIPP_HW_COL_COMB_CHR_BUFFER_HEIGHT, N_PL(SIPP_HW_COL_COMB_CHR_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->colorcombMa2x5x0 =  sippCreateFilter(pPl->pl, 0x0,        SIPP_HW_COL_COMB_BUFFER_WIDTH, SIPP_HW_COL_COMB_BUFFER_HEIGHT, N_PL(SIPP_HW_COL_COMB_BUFFER_NUM_PLANES), SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_CC_ID,         0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_COL_COMB_BUFFER_WIDTH, SIPP_HW_COL_COMB_BUFFER_HEIGHT, N_PL(SIPP_HW_COL_COMB_BUFFER_NUM_PLANES), SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->colorcombMa2x5x0, pPl->dmaIn0,        1,1                 );
   sippLinkFilter(pPl->colorcombMa2x5x0, pPl->dmaIn1,        5,5                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->colorcombMa2x5x0, 1,1                 );
	
}

  
void configTestHwColorComb(TestHwColorComb *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   DmaParam            *dmaIn1Cfg          = (DmaParam         *)pPl->dmaIn1->params;
   ColCombParam        *colorcombMa2x5x0Cfg= (ColCombParam     *)pPl->colorcombMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   colorcombMa2x5x0Cfg->cfg=CC_CFG(FORCE_LUMA_ONE,0,LUT_3D_BYPASS,LUT_3D_LOAD,U12F_OUTPUT,OUTPUT_PLANE_MULT);
   colorcombMa2x5x0Cfg->krgb[0]=K_R | (K_G << 16);
   colorcombMa2x5x0Cfg->krgb[1]=(K_B | (EPSILON << 16));
   colorcombMa2x5x0Cfg->ccm[0]=(colCorrMatrix[0] | colCorrMatrix[1] << 16);
   colorcombMa2x5x0Cfg->ccm[1]=(colCorrMatrix[2] | colCorrMatrix[3] << 16);
   colorcombMa2x5x0Cfg->ccm[2]=(colCorrMatrix[4] | colCorrMatrix[5] << 16);
   colorcombMa2x5x0Cfg->ccm[3]=(colCorrMatrix[6] | colCorrMatrix[7] << 16);
   colorcombMa2x5x0Cfg->ccm[4]=(colCorrMatrix[8] | R_OFF << 16);
   colorcombMa2x5x0Cfg->ccOffs=(G_OFF | B_OFF << 16);
   colorcombMa2x5x0Cfg->threeDLut=Lut3D;
   colorcombMa2x5x0Cfg->lutFormat=0x2;
   dmaIn0Cfg->ddrAddr   = (UInt32)&TestHwColorComb_dmaIn0_buffer;
   dmaIn1Cfg->ddrAddr   = (UInt32)&TestHwColorComb_dmaIn1_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwColorComb_dmaOut0_buffer;
  
  
}
