///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "testHwSharpen.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt8      DDR_DATA TestHwSharpen_dmaIn0_buffer[SIPP_HW_SHARPEN_BUFFER_WIDTH* SIPP_HW_SHARPEN_BUFFER_HEIGHT* 1  ]ALIGNED(8);
UInt8      DDR_DATA TestHwSharpen_dmaOut0_buffer[SIPP_HW_SHARPEN_BUFFER_WIDTH* SIPP_HW_SHARPEN_BUFFER_HEIGHT* 1  ]ALIGNED(8);
	
///
void readTestHwSharpenInput(TestHwSharpen *pPl)
{
   sippRdFileU8((UInt8*)TestHwSharpen_dmaIn0_buffer,SIPP_HW_SHARPEN_BUFFER_WIDTH * SIPP_HW_SHARPEN_BUFFER_HEIGHT * 1 * sizeof(UInt8),"../../../../../../../resources/lumaSharpenInput.y");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeTestHwSharpenOutput(TestHwSharpen *pPl)
{
   sippWrFileU8((UInt8*)TestHwSharpen_dmaOut0_buffer,SIPP_HW_SHARPEN_BUFFER_WIDTH * SIPP_HW_SHARPEN_BUFFER_HEIGHT * 1 * sizeof(UInt8),"output.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildTestHwSharpen(TestHwSharpen *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 0, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_SHARPEN_BUFFER_WIDTH, SIPP_HW_SHARPEN_BUFFER_HEIGHT, N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->sharpenMa2x5x   =  sippCreateFilter(pPl->pl, 0x0,        SIPP_HW_SHARPEN_BUFFER_WIDTH, SIPP_HW_SHARPEN_BUFFER_HEIGHT, N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_SHARPEN_ID,    0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_SHARPEN_BUFFER_WIDTH, SIPP_HW_SHARPEN_BUFFER_HEIGHT, N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->sharpenMa2x5x, pPl->dmaIn0,        7,7                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->sharpenMa2x5x, 1,1                 );
	
}

  
void configTestHwSharpen(TestHwSharpen *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   UsmParam            *sharpenMa2x5xCfg   = (UsmParam         *)pPl->sharpenMa2x5x->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   sharpenMa2x5xCfg->cfg=   SHARPEN_CFG( THR,  KERNEL_SIZE,OUTPUT_CLAMP ,SHARPENING,OUTPUT_DELTAS);
   sharpenMa2x5xCfg->strength=SHARPEN_STRENGTH_CFG(STRENGTH_LIGHTEN, STRENGTH_DARKEN );
   sharpenMa2x5xCfg->clip=  CLIPPING_ALPHA;
   sharpenMa2x5xCfg->limit=  SHARPEN_LIMITS_CFG(UNDERSHOOT,OVERSHOOT);
   sharpenMa2x5xCfg->rgnStop01=SHARPEN_RANGESTOP01_CFG(RANGE_STOP0, RANGE_STOP1);
   sharpenMa2x5xCfg->rgnStop23= SHARPEN_RANGESTOP01_CFG(RANGE_STOP2, RANGE_STOP3);
   sharpenMa2x5xCfg->coef01=SHARPEN_COEFS01_CFG(0x2400,0x2e00);
   sharpenMa2x5xCfg->coef23=SHARPEN_COEFS23_CFG(0x3380, 0x3500);
   dmaIn0Cfg->ddrAddr   = (UInt32)&TestHwSharpen_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwSharpen_dmaOut0_buffer;
  
  
}
