///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __TESTHWSHARPEN_H__
#define __TESTHWSHARPEN_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "testMacros.h"


//The full-frame buffers
extern UInt8 DDR_DATA TestHwSharpen_dmaIn0_buffer[ SIPP_HW_SHARPEN_BUFFER_WIDTH * SIPP_HW_SHARPEN_BUFFER_HEIGHT * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA TestHwSharpen_dmaOut0_buffer[ SIPP_HW_SHARPEN_BUFFER_WIDTH * SIPP_HW_SHARPEN_BUFFER_HEIGHT * 1 ]ALIGNED(8);
	
///

typedef struct TestHwSharpen
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut0;
	SippFilter *sharpenMa2x5x;

} TestHwSharpen;

void readTestHwSharpenInput(TestHwSharpen *pPl);
void writeTestHwSharpenOutput(TestHwSharpen *pPl);

void buildTestHwSharpen(TestHwSharpen *pPl);
void configTestHwSharpen(TestHwSharpen *pPl);


#endif