///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "testHwChromaDns.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt8      DDR_DATA TestHwChromaDns_dmaIn0_buffer[792      * 645     * 3  ]ALIGNED(8);
UInt8      DDR_DATA TestHwChromaDns_dmaOut0_buffer[792      * 645     * 3  ]ALIGNED(8);
	
///
void readTestHwChromaDnsInput(TestHwChromaDns *pPl)
{
   sippRdFileU8((UInt8*)TestHwChromaDns_dmaIn0_buffer,792        * 645     * 3 * sizeof(UInt8),"../../../../../../../resources/OCT_792x645_I_chroma_dns_8bpp.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeTestHwChromaDnsOutput(TestHwChromaDns *pPl)
{
   sippWrFileU8((UInt8*)TestHwChromaDns_dmaOut0_buffer,792        * 645     * 3 * sizeof(UInt8),"uvDnsUnitTestOut.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildTestHwChromaDns(TestHwChromaDns *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       792,    645,    N_PL(3),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->chromadnsMa2x5x0 =  sippCreateFilter(pPl->pl, 0x0,        792,    645,    N_PL(3),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_CHROMA_ID,     0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       792,    645,    N_PL(3),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->chromadnsMa2x5x0, pPl->dmaIn0,        3,3                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->chromadnsMa2x5x0, 1,1                 );
	
}

  
void configTestHwChromaDns(TestHwChromaDns *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   ChrDnsParam         *chromadnsMa2x5x0Cfg= (ChrDnsParam      *)pPl->chromadnsMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   chromadnsMa2x5x0Cfg->cfg=CHROMA_DNS_CFG(HOR_ENABLE,LIMIT,FORCE_WT_H,FORCE_WT_V,0,OFFSET,SLOPE);
   chromadnsMa2x5x0Cfg->thr[0]=0x07030703;
   chromadnsMa2x5x0Cfg->thr[1]=0x0b000b;
   chromadnsMa2x5x0Cfg->greyPt=CHORMA_GREY_PT_SET(GREY_CB,GREY_CG,GREY_CR,GREY_PT);
   chromadnsMa2x5x0Cfg->chrCoefs=CHROMA_DNS_COEFFS_SET(CENTER_COEFF,CENTER_EDGE_COEFF,CORNER_COEFF);
   dmaIn0Cfg->ddrAddr   = (UInt32)&TestHwChromaDns_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwChromaDns_dmaOut0_buffer;
  
  
}
