/* usbpump_xhci_ioctlcodes.h	Wed Dec 30 2015 17:15:46 tmm */

/*

Module:  usbpump_xhci_ioctlcodes.h

Function:
	IOCTL codes specific to XHCI

Version:
	V3.15d	Wed Dec 30 2015 17:15:46 tmm	Edit level 1

Copyright notice:
	This file copyright (C) 2015 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.
	
	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation.
 
Author:
	Terry Moore, MCCI Corporation	December 2015

Revision history:
   3.15d  Wed Dec 30 2015 17:15:46  tmm
	19789: Module created.

*/

#ifndef _USBPUMP_XHCI_IOCTLCODES_H_	/* prevent multiple includes */
# define _USBPUMP_XHCI_IOCTLCODES_H_

#ifndef _USBPUMPIOCTL_H_
# include "usbpumpioctl.h"
#endif

#ifndef _USBPUMPOBJECT_H_
# include "usbpumpobject.h"
#endif

#ifndef _USBIOCTL_API_H_
# include "usbioctl_api.h"
#endif

#ifndef _USBPUMP_XHCD_H_
# include "usbpump_xhcd.h"
#endif

/****************************************************************************\
|
|	Define the GUID & the request codes (pGuidSpecificInfo[0])
|	pGuidSpecificInfo[1] is always the pHcdXhci.
|
\****************************************************************************/

/* {9FEF730B-A42B-4621-B7EB-5F9CBA82D8C1} */
#define	__TMS_USBPUMP_HCD_XHCI_GUID_PLATFORM_REQUEST			\
	__TMS_USBGUID_INIT(						\
0x9fef730b, 0xa42b, 0x4621, 0xb7, 0xeb, 0x5f, 0x9c, 0xba, 0x82, 0xd8, 0xc1 \
	    )

/* define the request codes */
#define	__TMS_USBPUMP_HCD_XHCI_API_INDICATE_CODE(uIndex)		\
	((__TMS_VOID *) (0xBEEF0000 + (uIndex)))

#define __TMS_USBPUMP_HCD_XHCI_API_INDICATE_PLATFORM_POST_RESET_INIT	\
	__TMS_USBPUMP_HCD_XHCI_API_INDICATE_CODE(0)

/* not really part of the API, but we need this type for the platform function */
__TMS_TYPE_DEF_FUNCTION(
	USBPUMP_HCD_XHCI_POST_RESET_FN,
	__TMS_VOID,
		(
		__TMS_USBPUMP_HCD_XHCI *
		));

/****************************************************************************\
|
|	Uncloak names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_HCD_XHCI_GUID_PLATFORM_REQUEST	\
   __TMS_USBPUMP_HCD_XHCI_GUID_PLATFORM_REQUEST
# define USBPUMP_HCD_XHCI_API_INDICATE_CODE(uIndex)	\
   __TMS_USBPUMP_HCD_XHCI_API_INDICATE_CODE(uIndex)
# define USBPUMP_HCD_XHCI_API_INDICATE_PLATFORM_POST_RESET_INIT	\
   __TMS_USBPUMP_HCD_XHCI_API_INDICATE_PLATFORM_POST_RESET_INIT
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/* end of file */
#endif /* _USBPUMP_XHCI_IOCTLCODES_H_*/
