/* usbpump_xhcd_types.h	Sun Jul 18 2010 19:11:51 luxw */

/*

Module:  usbpump_xhcd_types.h

Function:
	Definition of XHCD/XHCI types.

Version:
	V3.01c	Sun Jul 18 2010 19:11:51 luxw	Edit level 6

Copyright notice:
	This file copyright (C) 2009-2010 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	Xiaowen Lu, MCCI Corporation	March 2009

Revision history:
   2.01a  Fri Mar 13 2009 13:55:04 luxw
	7678: Module created.

   2.01a  Sun May 17 2009 15:34:12  luxw
	7678: Added USBPUMP_XHCI_PORT_SPEED type.

   2.01a  Thu Jul 02 2009 10:28:10  luxw
	8306: Added USBPUMP_XHCD_TR_STATE type.

   2.01a  Tue Nov 24 2009 19:31:59  luxw
	9272: Add stream context and stream id declaration.

   2.01a  Thu Dec 03 2009 15:25:03  chwon
	9191: Use USBPUMP_HCDKIT_ROOTHUBPORT instead of USBPUMP_XHCD_ROOTPORT

   3.01c  Sun Jul 18 2010 19:11:51  luxw
	8779: Added scratchpad buffer related structures.

*/

#ifndef _USBPUMP_XHCD_TYPES_H_		/* prevent multiple includes */
#define _USBPUMP_XHCD_TYPES_H_

#ifndef _USBPUMP_TYPES_H_
# include "usbpump_types.h"
#endif

/****************************************************************************\
|
|	Forward types
|
\****************************************************************************/

__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_TRB);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_SLOT_CONTEXT);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_ENDPOINT_CONTEXT);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_INPUT_CONTROL_CONTEXT);

__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_DCBAA_ENTRY);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_COMMAND_RING);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_EVENT_RING_SEGMENT_TABLE_ENTRY);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_EVENT_RING_SEGMENT_TABLE);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_EVENT_RING_SEGMENT);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_EVENT_RING);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_TRANSFER_RING);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_STREAM_CONTEXT);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCI_SCRATCHPAD_BUFFER_ELEMENT);

__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_DCBAA);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_BUFFER_SEGMENT);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_INPUT_CONTEXT);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_DEVICE_CONTEXT);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_DEVICE_CONTEXT_ARRAY);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_COMMAND_RING);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_EVENT_RING_SEGMENT);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_EVENT_RING_SEGMENT_TABLE);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_EVENT_RING);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_TRANSFER_RING);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_STREAM_CONTEXT_ARRAY);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_SCRATCHPAD_BUFFER_ARRAY);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_SCRATCHPAD_BUFFER_ELEMENT);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_MAPPED_BUFFER_RANGE);
__TMS_TYPE_DEF_STRUCT(USBPUMP_XHCD_ISO_PKT_DESC);


__TMS_TYPE_DEF_ARG(USBPUMP_XHCD_COMMAND_TYPE,	UINT16);
__TMS_TYPE_DEF_ARG(USBPUMP_XHCD_SLOT_ID,	UINT8);
__TMS_TYPE_DEF_ARG(USBPUMP_XHCD_ENDPOINT_ID,	UINT8);
__TMS_TYPE_DEF_ARG(USBPUMP_XHCD_STREAM_ID,	UINT16);
__TMS_TYPE_DEF_ARG(USBPUMP_XHCD_ENDPOINT_TYPE,	UINT8);
__TMS_TYPE_DEF_ARG(USBPUMP_XHCD_COMPLETION_CODE, UINT8);
__TMS_TYPE_DEF_ARG(USBPUMP_XHCD_TR_STATE, 	UINT8);
__TMS_TYPE_DEF_ARG(USBPUMP_XHCI_PORT_SPEED, 	UINT8);

/**** end of usbpump_xhcd_types.h ****/
#endif /* _USBPUMP_XHCD_TYPES_H_ */
