///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTB0MODEL_H__
#define __SIPPTUTB0MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>



//The full-frame buffers
extern UInt8 DDR_DATA SippTutB0Model_dmaIn0_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutB0Model_dmaIn1_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutB0Model_dmaOut3_buffer[ 512 * 512 * 1 ]ALIGNED(8);
	
///

typedef struct SippTutB0Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaIn1;
	SippFilter *avg2;
	SippFilter *dmaOut3;

} SippTutB0Model;

void readSippTutB0ModelInput(SippTutB0Model *pPl);
void writeSippTutB0ModelOutput(SippTutB0Model *pPl);

void buildSippTutB0Model(SippTutB0Model *pPl);
void configSippTutB0Model(SippTutB0Model *pPl);


#endif