///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "testHwSigmaDenoise.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt16     DDR_DATA TestHwSigmaDenoise_dmaIn0_buffer[SIPP_HW_SIGMA_DNS_BUFFER_WIDTH* SIPP_HW_SIGMA_DNS_BUFFER_HEIGHT* SIPP_HW_SIGMA_DNS_BUFFER_NUM_PLANES]ALIGNED(8);
UInt16     DDR_DATA TestHwSigmaDenoise_dmaOut0_buffer[SIPP_HW_SIGMA_DNS_BUFFER_WIDTH* SIPP_HW_SIGMA_DNS_BUFFER_HEIGHT* SIPP_HW_SIGMA_DNS_BUFFER_NUM_PLANES]ALIGNED(8);
	
///
void readTestHwSigmaDenoiseInput(TestHwSigmaDenoise *pPl)
{
   sippRdFileU8((UInt8*)TestHwSigmaDenoise_dmaIn0_buffer,SIPP_HW_SIGMA_DNS_BUFFER_WIDTH * SIPP_HW_SIGMA_DNS_BUFFER_HEIGHT * SIPP_HW_SIGMA_DNS_BUFFER_NUM_PLANES* sizeof(UInt16),"../../../../../../../resources/OCT_1600x1300_I_Sigma_10bpp.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeTestHwSigmaDenoiseOutput(TestHwSigmaDenoise *pPl)
{
   sippWrFileU8((UInt8*)TestHwSigmaDenoise_dmaOut0_buffer,SIPP_HW_SIGMA_DNS_BUFFER_WIDTH * SIPP_HW_SIGMA_DNS_BUFFER_HEIGHT * SIPP_HW_SIGMA_DNS_BUFFER_NUM_PLANES* sizeof(UInt16),"output.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildTestHwSigmaDenoise(TestHwSigmaDenoise *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 0, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_SIGMA_DNS_BUFFER_WIDTH, SIPP_HW_SIGMA_DNS_BUFFER_HEIGHT, N_PL(SIPP_HW_SIGMA_DNS_BUFFER_NUM_PLANES), SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->sigmaDnsMa2x5x0 =  sippCreateFilter(pPl->pl, 0x0,        SIPP_HW_SIGMA_DNS_BUFFER_WIDTH, SIPP_HW_SIGMA_DNS_BUFFER_HEIGHT, N_PL(SIPP_HW_SIGMA_DNS_BUFFER_NUM_PLANES), SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_SIGMA_ID,      0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_SIGMA_DNS_BUFFER_WIDTH, SIPP_HW_SIGMA_DNS_BUFFER_HEIGHT, N_PL(SIPP_HW_SIGMA_DNS_BUFFER_NUM_PLANES), SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->sigmaDnsMa2x5x0, pPl->dmaIn0,        5,5                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->sigmaDnsMa2x5x0, 1,1                 );
	
}

  
void configTestHwSigmaDenoise(TestHwSigmaDenoise *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   SigmaParam          *sigmaDnsMa2x5x0Cfg = (SigmaParam       *)pPl->sigmaDnsMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   sigmaDnsMa2x5x0Cfg->thresh[0]=(GR_THR_MUL_0 <<  0 | GR_THR_MUL_1 <<  8 | R_THR_MUL_0 << 16 | R_THR_MUL_1 << 24);
   sigmaDnsMa2x5x0Cfg->thresh[1]=(B_THR_MUL_0 <<  0 | B_THR_MUL_1 <<  8 | GB_THR_MUL_0 << 16 | GB_THR_MUL_1 << 24);
   sigmaDnsMa2x5x0Cfg->cfg= SIGMA_DNS_CFG(NOISE_FLOOR , (DATA_WIDTH -1), PASSTHROUGH_BIT,FORMAT);
   sigmaDnsMa2x5x0Cfg->bayerPattern=GRBG;
   sigmaDnsMa2x5x0Cfg->blcGR=BLACK0;
   sigmaDnsMa2x5x0Cfg->blcR=BLACK1;
   sigmaDnsMa2x5x0Cfg->blcB=BLACK2;
   sigmaDnsMa2x5x0Cfg->blcGB=BLACK3;
   dmaIn0Cfg->ddrAddr   = (UInt32)&TestHwSigmaDenoise_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwSigmaDenoise_dmaOut0_buffer;
  
  
}
