///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __TESTHWSIGMADENOISE_H__
#define __TESTHWSIGMADENOISE_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "testData.h"


//The full-frame buffers
extern UInt16 DDR_DATA TestHwSigmaDenoise_dmaIn0_buffer[ SIPP_HW_SIGMA_DNS_BUFFER_WIDTH * SIPP_HW_SIGMA_DNS_BUFFER_HEIGHT * SIPP_HW_SIGMA_DNS_BUFFER_NUM_PLANES ]ALIGNED(8);
extern UInt16 DDR_DATA TestHwSigmaDenoise_dmaOut0_buffer[ SIPP_HW_SIGMA_DNS_BUFFER_WIDTH * SIPP_HW_SIGMA_DNS_BUFFER_HEIGHT * SIPP_HW_SIGMA_DNS_BUFFER_NUM_PLANES ]ALIGNED(8);
	
///

typedef struct TestHwSigmaDenoise
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *sigmaDnsMa2x5x0;
	SippFilter *dmaIn0;
	SippFilter *dmaOut0;

} TestHwSigmaDenoise;

void readTestHwSigmaDenoiseInput(TestHwSigmaDenoise *pPl);
void writeTestHwSigmaDenoiseOutput(TestHwSigmaDenoise *pPl);

void buildTestHwSigmaDenoise(TestHwSigmaDenoise *pPl);
void configTestHwSigmaDenoise(TestHwSigmaDenoise *pPl);


#endif