///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTA4MODEL_H__
#define __SIPPTUTA4MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>



//The full-frame buffers
extern UInt8 DDR_DATA SippTutA4Model_dmaIn0_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutA4Model_dmaOut1_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutA4Model_dmaOut4_buffer[ 512 * 512 * 1 ]ALIGNED(8);
	
///

typedef struct SippTutA4Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut1;
	SippFilter *conv5x52;
	SippFilter *conv5x53;
	SippFilter *dmaOut4;

} SippTutA4Model;

void readSippTutA4ModelInput(SippTutA4Model *pPl);
void writeSippTutA4ModelOutput(SippTutA4Model *pPl);

void buildSippTutA4Model(SippTutA4Model *pPl);
void configSippTutA4Model(SippTutA4Model *pPl);


#endif