mdbg::REG_DEFS {
    ARM_DBG_ROMENTRY_CORE0_DBG_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY0_OFFS}
    ARM_DBG_ROMENTRY_CORE0_CTI_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY1_OFFS}
    ARM_DBG_ROMENTRY_CORE0_PMU_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY2_OFFS}
    ARM_DBG_ROMENTRY_CORE0_ETM_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY3_OFFS}

    ARM_DBG_ROMENTRY_CORE1_DBG_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY4_OFFS}
    ARM_DBG_ROMENTRY_CORE1_CTI_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY5_OFFS}
    ARM_DBG_ROMENTRY_CORE1_PMU_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY6_OFFS}
    ARM_DBG_ROMENTRY_CORE1_ETM_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY7_OFFS}

    ARM_DBG_ROMENTRY_CORE2_DBG_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY8_OFFS}
    ARM_DBG_ROMENTRY_CORE2_CTI_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY9_OFFS}
    ARM_DBG_ROMENTRY_CORE2_PMU_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY10_OFFS}
    ARM_DBG_ROMENTRY_CORE2_ETM_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY11_OFFS}

    ARM_DBG_ROMENTRY_CORE3_DBG_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY12_OFFS}
    ARM_DBG_ROMENTRY_CORE3_CTI_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY13_OFFS}
    ARM_DBG_ROMENTRY_CORE3_PMU_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY14_OFFS}
    ARM_DBG_ROMENTRY_CORE3_ETM_ADDR  {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMENTRY15_OFFS}
}

mdbg::REG_DEFS {
    ARM_DBG_ROMPIDR0_ADDR   {$ARM_DBG_ROM_BASE_ADDR + $ARM_ROMPIDR0_OFFS}
}

apply {args {
    foreach cpu $args {
        REG_DEFS "
            ARMV8_CPU${cpu}_DBG_BASE_ADDR     {\$ARM_DBG_ROM_BASE_ADDR + 0x00010000 + ${cpu} * 0x100000}
            ARMV8_CPU${cpu}_CTI_BASE_ADDR     {\$ARM_DBG_ROM_BASE_ADDR + 0x00020000 + ${cpu} * 0x100000}
            ARMV8_CPU${cpu}_PMU_BASE_ADDR     {\$ARM_DBG_ROM_BASE_ADDR + 0x00030000 + ${cpu} * 0x100000}
            ARMV8_CPU${cpu}_ETM_BASE_ADDR     {\$ARM_DBG_ROM_BASE_ADDR + 0x00040000 + ${cpu} * 0x100000}

            ARMV8_DBG_CPU${cpu}_EDLAR_ADDR         {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_EDLAR_OFFS}
            ARMV8_DBG_CPU${cpu}_OSLAR_ADDR         {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_OSLAR_EL1_OFFS}
            ARMV8_DBG_CPU${cpu}_DBGDTRRX_ADDR      {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_DBGDTRRX_EL0_OFFS}
            ARMV8_DBG_CPU${cpu}_EDITR_ADDR         {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_EDITR_OFFS}
            ARMV8_DBG_CPU${cpu}_EDSCR_ADDR         {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_EDSCR_OFFS}
            ARMV8_DBG_CPU${cpu}_DBGDTRTX_ADDR      {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_DBGDTRTX_EL0_OFFS}

            ARMV8_DBG_CPU${cpu}_EDPRCR_ADDR        {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_EDPRCR_OFFS}
            ARMV8_DBG_CPU${cpu}_EDRCR_ADDR         {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_EDRCR_OFFS}
            ARMV8_DBG_CPU${cpu}_EDPRSR_ADDR        {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_EDPRSR_OFFS}

            ARMV8_DBG_CPU${cpu}_EDESR_ADDR         {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_EDESR_OFFS}
            ARMV8_DBG_CPU${cpu}_EDECR_ADDR         {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_EDECR_OFFS}
            ARMV8_DBG_CPU${cpu}_EDECCR_ADDR        {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_EDECCR_OFFS}
            ARMV8_DBG_CPU${cpu}_EDPCSR_LO_ADDR     {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_EDPCSR_LO_OFFS}
            ARMV8_DBG_CPU${cpu}_EDPCSR_HI_ADDR     {\$ARMV8_CPU${cpu}_DBG_BASE_ADDR + \$ARM_CPU_DBG_EDPCSR_HI_OFFS}
        "
    }
} ::mdbg} 0 1 2 3
