///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTE0MODEL_H__
#define __SIPPTUTE0MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "myDefs.h"


//The full-frame buffers
extern UInt8 DDR_DATA SippTutE0Model_dmaIn0_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutE0Model_dmaIn1_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutE0Model_dmaOut0_buffer[ 256 * 256 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutE0Model_dmaOut1_buffer[ 512 * 512 * 1 ]ALIGNED(8);
	
///

typedef struct SippTutE0Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *absdiff0;
	SippFilter *dmaIn1;
	SippFilter *conv3x30;
	SippFilter *dilate5x50;
	SippFilter *scale05BilinHV0;
	SippFilter *dmaOut0;
	SippFilter *dmaOut1;

} SippTutE0Model;

void readSippTutE0ModelInput(SippTutE0Model *pPl);
void writeSippTutE0ModelOutput(SippTutE0Model *pPl);

void buildSippTutE0Model(SippTutE0Model *pPl);
void configSippTutE0Model(SippTutE0Model *pPl);


#endif