///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "sippTutE0Model.h"

#include <include/sippHwDefs.h>
#include <filters/conv3x3/conv3x3.h>
#include <filters/dilate5x5/dilate5x5.h>
#include <filters/absdiff/absdiff.h>
#include <filters/scale05bilinHV/scale05BilinHV.h>


//The full-frame buffers
UInt8      DDR_DATA SippTutE0Model_dmaIn0_buffer[512      * 512     * 1  ]ALIGNED(8);
UInt8      DDR_DATA SippTutE0Model_dmaIn1_buffer[512      * 512     * 1  ]ALIGNED(8);
UInt8      DDR_DATA SippTutE0Model_dmaOut0_buffer[256      * 256     * 1  ]ALIGNED(8);
UInt8      DDR_DATA SippTutE0Model_dmaOut1_buffer[512      * 512     * 1  ]ALIGNED(8);
	
///
void readSippTutE0ModelInput(SippTutE0Model *pPl)
{
   sippRdFileU8((UInt8*)SippTutE0Model_dmaIn0_buffer,512        * 512     * 1 * sizeof(UInt8),"../../../../../../../resources/lena_512x512_luma.raw");
   sippRdFileU8((UInt8*)SippTutE0Model_dmaIn1_buffer,512        * 512     * 1 * sizeof(UInt8),"../../../../../../../resources/lena_512x512_luma.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeSippTutE0ModelOutput(SippTutE0Model *pPl)
{
   sippWrFileU8((UInt8*)SippTutE0Model_dmaOut0_buffer,256        * 256     * 1 * sizeof(UInt8),"output.raw");
   sippWrFileU8((UInt8*)SippTutE0Model_dmaOut1_buffer,512        * 512     * 1 * sizeof(UInt8),"output2.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildSippTutE0Model(SippTutE0Model *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->dmaIn1          =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->conv3x30        =  sippCreateFilter(pPl->pl, 0x0,        512,    512,    N_PL(1),  SZ(UInt8), SZ(Conv3x3Param),   SVU_SYM(svuConv3x3),          0);
   pPl->dilate5x50      =  sippCreateFilter(pPl->pl, 0x0,        512,    512,    N_PL(1),  SZ(UInt8), SZ(Dilate5x5Param), SVU_SYM(svuDilate5x5),        0);
   pPl->absdiff0        =  sippCreateFilter(pPl->pl, 0x0,        512,    512,    N_PL(1),  SZ(UInt8), 0,                  SVU_SYM(svuAbsdiff),          0);
   pPl->scale05BilinHV0 =  sippCreateFilter(pPl->pl, SIPP_RESIZE, 256,    256,    N_PL(1),  SZ(UInt8), 0,                  SVU_SYM(svuScl05BilinHV),     0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       256,    256,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->dmaOut1         =  sippCreateFilter(pPl->pl, 0x00,       512,    512,    N_PL(1),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->conv3x30,      pPl->dmaIn0,        3,3                 );
   sippLinkFilter(pPl->dilate5x50,    pPl->dmaIn1,        5,5                 );
   sippLinkFilter(pPl->absdiff0,      pPl->conv3x30,      1,1                 );
   sippLinkFilter(pPl->absdiff0,      pPl->dilate5x50,    1,1                 );
   sippLinkFilter(pPl->scale05BilinHV0, pPl->dilate5x50,    2,2                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->scale05BilinHV0, 1,1                 );
   sippLinkFilter(pPl->dmaOut1,       pPl->absdiff0,      1,1                 );
	
}

UInt16 conv3x30Cfg_cMat[9];
  
void configSippTutE0Model(SippTutE0Model *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   DmaParam            *dmaIn1Cfg          = (DmaParam         *)pPl->dmaIn1->params;
   Conv3x3Param        *conv3x30Cfg        = (Conv3x3Param     *)pPl->conv3x30->params;
   Dilate5x5Param      *dilate5x50Cfg      = (Dilate5x5Param   *)pPl->dilate5x50->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
   DmaParam            *dmaOut1Cfg         = (DmaParam         *)pPl->dmaOut1->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   conv3x30Cfg->cMat=       conv3x30Cfg_cMat;
   conv3x30Cfg->cMat[0]=    0x2C00;
   conv3x30Cfg->cMat[1]=    0x3000;
   conv3x30Cfg->cMat[2]=    0x2C00;
   conv3x30Cfg->cMat[3]=    0x3000;
   conv3x30Cfg->cMat[4]=    0x3400;
   conv3x30Cfg->cMat[5]=    0x3000;
   conv3x30Cfg->cMat[6]=    0x2C00;
   conv3x30Cfg->cMat[7]=    0x3000;
   conv3x30Cfg->cMat[8]=    0x2C00;
   dilate5x50Cfg->dMat[0]=  (UInt8*)&dMat[0];
   dilate5x50Cfg->dMat[1]=  (UInt8*)&dMat[2];
   dilate5x50Cfg->dMat[2]=  (UInt8*)&dMat[4];
   dilate5x50Cfg->dMat[3]=  (UInt8*)&dMat[6];
   dilate5x50Cfg->dMat[4]=  (UInt8*)&dMat[8];
   dmaIn0Cfg->ddrAddr   = (UInt32)&SippTutE0Model_dmaIn0_buffer;
   dmaIn1Cfg->ddrAddr   = (UInt32)&SippTutE0Model_dmaIn1_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&SippTutE0Model_dmaOut0_buffer;
   dmaOut1Cfg->ddrAddr  = (UInt32)&SippTutE0Model_dmaOut1_buffer;
  
  
}
