///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __BAYERISPMODEL_H__
#define __BAYERISPMODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "BayerPipelineParams.h"


//The full-frame buffers
extern UInt8 DDR_DATA BayerISPModel_dmaIn0_buffer[ 522 * 128 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA BayerISPModel_dmaOut1_buffer[ 522 * 128 * 1 ]ALIGNED(8);
	
///

typedef struct BayerISPModel
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut1;
	SippFilter *negative0;

} BayerISPModel;

void readBayerISPModelInput(BayerISPModel *pPl);
void writeBayerISPModelOutput(BayerISPModel *pPl);

void buildBayerISPModel(BayerISPModel *pPl);
void configBayerISPModel(BayerISPModel *pPl);


#endif