///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "testHwDbyr.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt16     DDR_DATA TestHwDbyr_dmaOut0_buffer[SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH* SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT* 3  ]ALIGNED(8);
UInt8      DDR_DATA TestHwDbyr_dmaOut1_buffer[SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH* SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT* SIPP_HW_DEBAYER_INPUT_BUFFER_NUM_PLANES]ALIGNED(8);
	
///
void readTestHwDbyrInput(TestHwDbyr *pPl)
{
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeTestHwDbyrOutput(TestHwDbyr *pPl)
{
   sippWrFileU8((UInt8*)TestHwDbyr_dmaOut0_buffer,SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH * SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT * 3 * sizeof(UInt16),"dbyrOutputRGB.raw");
   sippWrFileU8((UInt8*)TestHwDbyr_dmaOut1_buffer,SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH * SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT * SIPP_HW_DEBAYER_INPUT_BUFFER_NUM_PLANES* sizeof(UInt8),"dbyrOutputLuma.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildTestHwDbyr(TestHwDbyr *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 0, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH, SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT, N_PL(SIPP_HW_DEBAYER_INPUT_BUFFER_NUM_PLANES), SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->debayerMa2x5x0  =  sippCreateFilter(pPl->pl, 0x0,        SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH, SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT, N_PL(3),  SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_DBYR_ID,       0);
   sippFilterAddOBuf(pPl->debayerMa2x5x0, SIPP_HW_DEBAYER_INPUT_BUFFER_NUM_PLANES, sizeof(UInt8));
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH, SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT, N_PL(3),  SZ(UInt16), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->dmaOut1         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH, SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT, N_PL(SIPP_HW_DEBAYER_INPUT_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->debayerMa2x5x0, pPl->dmaIn0,        11,11               );
   sippLinkFilter(pPl->dmaOut0,       pPl->debayerMa2x5x0, 1,1                 );
   sippLinkFilter(pPl->dmaOut1,       pPl->debayerMa2x5x0, 1,1                 );
   sippLinkFilterSetOBuf(pPl->dmaOut1, pPl->debayerMa2x5x0, 1);
	
}

  
void configTestHwDbyr(TestHwDbyr *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   DbyrParam           *debayerMa2x5x0Cfg  = (DbyrParam        *)pPl->debayerMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
   DmaParam            *dmaOut1Cfg         = (DmaParam         *)pPl->dmaOut1->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   debayerMa2x5x0Cfg->cfg=  DEBAYER_CFG(GRBG,0,0,12,12,0,3,0);
   debayerMa2x5x0Cfg->thresh=DEBAYER_THRESH(0,0,1,1,1,0) ;
   debayerMa2x5x0Cfg->dewormCfg=DEBAYER_DEWORM(0,0);
   debayerMa2x5x0Cfg->lumaWeight=DEBAYER_LUMA_COEFS_CFG(96 , 128, 32);
   dmaIn0Cfg->ddrAddr   = (UInt32)iBuff12;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwDbyr_dmaOut0_buffer;
   dmaOut1Cfg->ddrAddr  = (UInt32)&TestHwDbyr_dmaOut1_buffer;
  
  
}
