#ifndef __TEST_DATA_DBYR_H__
#define __TEST_DATA_DBYR_H__

#define SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH      32
#define SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT     16
#define SIPP_HW_DEBAYER_INPUT_BUFFER_NUM_PLANES  1
#define SIPP_HW_DEBAYER_INPUT_BUFFER_SIZE  (SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH * SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT * SIPP_HW_DEBAYER_INPUT_BUFFER_NUM_PLANES)

//12bit bayer
extern uint16_t iBuff12[];

// O buffer (Excel GOLD data for bilinear debayer)
extern uint16_t   eBuff12[3][SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH * SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT];

#endif
