///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __TESTHWDBYR_H__
#define __TESTHWDBYR_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "testDataDbyr.h"


//The full-frame buffers
extern UInt16 DDR_DATA TestHwDbyr_dmaOut0_buffer[ SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH * SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT * 3 ]ALIGNED(8);
extern UInt8 DDR_DATA TestHwDbyr_dmaOut1_buffer[ SIPP_HW_DEBAYER_INPUT_BUFFER_WIDTH * SIPP_HW_DEBAYER_INPUT_BUFFER_HEIGHT * SIPP_HW_DEBAYER_INPUT_BUFFER_NUM_PLANES ]ALIGNED(8);
	
///

typedef struct TestHwDbyr
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut0;
	SippFilter *debayerMa2x5x0;
	SippFilter *dmaOut1;

} TestHwDbyr;

void readTestHwDbyrInput(TestHwDbyr *pPl);
void writeTestHwDbyrOutput(TestHwDbyr *pPl);

void buildTestHwDbyr(TestHwDbyr *pPl);
void configTestHwDbyr(TestHwDbyr *pPl);


#endif