///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "testHwGenChroma.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt8      DDR_DATA TestHwGenChroma_dmaIn0_buffer[1083     * 1289    * 3  ]ALIGNED(8);
UInt8      DDR_DATA TestHwGenChroma_dmaOut0_buffer[542      * 644     * 3  ]ALIGNED(8);
	
///
void readTestHwGenChromaInput(TestHwGenChroma *pPl)
{
   sippRdFileU8((UInt8*)TestHwGenChroma_dmaIn0_buffer,1083       * 1289    * 3 * sizeof(UInt8),"../../../../../../../resources/GenChromaIn1083x1289_3_1bpp.rgb");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeTestHwGenChromaOutput(TestHwGenChroma *pPl)
{
   sippWrFileU8((UInt8*)TestHwGenChroma_dmaOut0_buffer,542        * 644     * 3 * sizeof(UInt8),"genChromaOutput.rgb");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildTestHwGenChroma(TestHwGenChroma *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 7, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       1083,   1289,   N_PL(3),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->chromaGenMa2x5x0 =  sippCreateFilter(pPl->pl, SIPP_RESIZE, 542,    644,    N_PL(3),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_CGEN_ID,       0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       542,    644,    N_PL(3),  SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->chromaGenMa2x5x0, pPl->dmaIn0,        6,6                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->chromaGenMa2x5x0, 1,1                 );
	
}

  
void configTestHwGenChroma(TestHwGenChroma *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   GenChrParam         *chromaGenMa2x5x0Cfg= (GenChrParam      *)pPl->chromaGenMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   chromaGenMa2x5x0Cfg->cfg=CGEN_CFG_SET(0x50,DAD_OFFSET,DAD_SLOPE,RSZ_INPUT_DW,BYPASS_PF_DAD,DS_MODE);
   chromaGenMa2x5x0Cfg->yCoefs=CGEN_LUMA_COEFF_SET(LUMA_R_COEFF,LUMA_G_COEFF,LUMA_B_COEFF) ;
   chromaGenMa2x5x0Cfg->chrCoefs=CGEN_CHROMA_COEFF_SET(CHROMA_EPSILON,CHROMA_R_COEFF,CHROMA_G_COEFF,CHROMA_B_COEFF);
   dmaIn0Cfg->ddrAddr   = (UInt32)&TestHwGenChroma_dmaIn0_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwGenChroma_dmaOut0_buffer;
  
  
}
