///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __TESTHWGENCHROMA_H__
#define __TESTHWGENCHROMA_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "testHwGenChromaSetup.h"


//The full-frame buffers
extern UInt8 DDR_DATA TestHwGenChroma_dmaIn0_buffer[ 1083 * 1289 * 3 ]ALIGNED(8);
extern UInt8 DDR_DATA TestHwGenChroma_dmaOut0_buffer[ 542 * 644 * 3 ]ALIGNED(8);
	
///

typedef struct TestHwGenChroma
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut0;
	SippFilter *chromaGenMa2x5x0;

} TestHwGenChroma;

void readTestHwGenChromaInput(TestHwGenChroma *pPl);
void writeTestHwGenChromaOutput(TestHwGenChroma *pPl);

void buildTestHwGenChroma(TestHwGenChroma *pPl);
void configTestHwGenChroma(TestHwGenChroma *pPl);


#endif