/*
 * testHwGenChromaSetup.h
 *
 *  Created on: 1 Oct 2015
 */

#ifndef LEON_TESTHWGENCHROMASETUP_H_
#define LEON_TESTHWGENCHROMASETUP_H_

#define FLOAT_TO_FIXED5_3(A, B)     (uint8_t) (((A) << 3) + ((B) *   8))

#define DSMODE_CARRY        0x0
#define DSMODE_DOWN         0x1
#define DSMODE_UPDN         0x2

#define PFR_STRENGTH        10.f
#define DAD_OFFSET          1
#define DAD_SLOPE           255
#define RSZ_INPUT_DW        8
#define BYPASS_PF_DAD       DISABLED
#define DS_MODE             DSMODE_DOWN
#define INPUT_DATA_WIDTH    RSZ_INPUT_DW
#define ODD_IMAGE_WIDTH     ENABLED
#define ODD_IMAGE_HEIGHT    ENABLED

#define LUMA_R_COEFF        (uint8_t)(.299f * 255)
#define LUMA_G_COEFF        (uint8_t)(.587f * 255)
#define LUMA_B_COEFF        (uint8_t)(.114f * 255)
#define CHROMA_EPSILON      2
#define CHROMA_R_SCALE      1.25f
#define CHROMA_R_COEFF      (uint8_t)(255/3 * CHROMA_R_SCALE)
#define CHROMA_G_SCALE      2.25f
#define CHROMA_G_COEFF      (uint8_t)(255/3 * CHROMA_G_SCALE)
#define CHROMA_B_SCALE      1.75f
#define CHROMA_B_COEFF      (uint8_t)(255/3 * CHROMA_B_SCALE)

#define SIPP_HW_CHR_GEN_INPUT_BUFFER_WIDTH        1083
#define SIPP_HW_CHR_GEN_INPUT_BUFFER_HEIGHT       1289
#define SIPP_HW_CHR_GEN_INPUT_BUFFER_NUM_PLANES   3
#define SIPP_HW_CHR_GEN_INPUT_BUFFER_SIZE         (SIPP_HW_CHR_GEN_INPUT_BUFFER_WIDTH * SIPP_HW_CHR_GEN_INPUT_BUFFER_HEIGHT * SIPP_HW_CHR_GEN_INPUT_BUFFER_NUM_PLANES)
#define SIPP_HW_CHR_GEN_OUTPUT_BUFFER_WIDTH       ((SIPP_HW_CHR_GEN_INPUT_BUFFER_WIDTH + 1) >> 1)
#define SIPP_HW_CHR_GEN_OUTPUT_BUFFER_HEIGHT      (SIPP_HW_CHR_GEN_INPUT_BUFFER_HEIGHT >> 1)
#define SIPP_HW_CHR_GEN_OUTPUT_BUFFER_NUM_PLANES  3
#define SIPP_HW_CHR_GEN_OUTPUT_BUFFER_SIZE        (SIPP_HW_CHR_GEN_OUTPUT_BUFFER_WIDTH * SIPP_HW_CHR_GEN_OUTPUT_BUFFER_HEIGHT * SIPP_HW_CHR_GEN_OUTPUT_BUFFER_NUM_PLANES)

#endif /* LEON_TESTHWGENCHROMASETUP_H_ */
