///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTB1MODEL_H__
#define __SIPPTUTB1MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>



//The full-frame buffers
extern UInt8 DDR_DATA SippTutB1Model_dmaIn0_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutB1Model_dmaIn1_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutB1Model_dmaOut3_buffer[ 512 * 512 * 1 ]ALIGNED(8);
	
///

typedef struct SippTutB1Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *avg2;
	SippFilter *dmaOut3;
	SippFilter *negative4;
	SippFilter *dmaIn1;

} SippTutB1Model;

void readSippTutB1ModelInput(SippTutB1Model *pPl);
void writeSippTutB1ModelOutput(SippTutB1Model *pPl);

void buildSippTutB1Model(SippTutB1Model *pPl);
void configSippTutB1Model(SippTutB1Model *pPl);


#endif