
MEST_COMP_DIR = $(MV_COMMON_BASE)/components/MEST
MEST_COMP_API_DIR = $(MEST_COMP_DIR)/api
MEST_COMP_FLIC_DIR = $(MEST_COMP_DIR)/flic

MEST_COMP_API_SHARED_DIR = $(MEST_COMP_API_DIR)/shared

MEST_COMP_API_PC_DIR = $(MEST_COMP_API_DIR)/pc

MEST_COMP_API_LEON_DIR = $(MEST_COMP_API_DIR)/leon
MEST_COMP_FLIC_LEON_DIR = $(MEST_COMP_FLIC_DIR)/leon

MEST_COMP_API_SHAVE_DIR = $(MEST_COMP_API_DIR)/shave

MEST_DEFINES := 
MEST_INCLUDES := 

MEST_COMP_API := MEST/api
MEST_COMP_FLIC := $(MEST_COMP_API) MEST/flic flic/core flic/types visionBaseFlicPlg flic/plugins/plgRotationMat

