///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTC1MODEL_H__
#define __SIPPTUTC1MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "sippMat.h"


//The full-frame buffers
extern UInt8 DDR_DATA SippTutC1Model_dmaIn0_buffer[ 512 * 512 * 1 ]ALIGNED(8);
extern UInt8 DDR_DATA SippTutC1Model_dmaOut1_buffer[ 512 * 512 * 1 ]ALIGNED(8);
	
///

typedef struct SippTutC1Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut1;
	SippFilter *erode5x52;

} SippTutC1Model;

void readSippTutC1ModelInput(SippTutC1Model *pPl);
void writeSippTutC1ModelOutput(SippTutC1Model *pPl);

void buildSippTutC1Model(SippTutC1Model *pPl);
void configSippTutC1Model(SippTutC1Model *pPl);


#endif