/* ucallback.h	Sat Feb 02 2013 19:06:25 chwon */

/*

Module:  ucallback.h

Function:
	Structures and functions for posting callbacks.

Version:
	V3.11c	Sat Feb 02 2013 19:06:25 chwon	Edit level 4

Copyright notice:
	This file copyright (C) 2002-2004, 2013 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.
	
	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation
 
Author:
	Terry Moore, MCCI Corporation	June 2002

Revision history:
   1.79a  Thu Jun  6 2002 08:15:24  tmm
	Module created.

   1.87b  Fri Mar 12 2004 16:01:17  chwon
	Correct sane name define; don't need type cloaking.

   1.87b  Tue Mar 16 2004 13:16:53  chwon
	Bug 1228: Added initialization macro for CALLBACKCOMPLETION.

   3.11c  Sat Feb 02 2013 19:06:25  chwon
	16637: Remove typecasting for input parameter of
	USBPUMP_CALLBACKCOMPLETION_INIT().

*/

#ifndef _UCALLBACK_H_		/* prevent multiple includes */
#define _UCALLBACK_H_

#ifndef _USBPUMPENV_H_
# include "usbpumpenv.h"
#endif

/****************************************************************************\
|
|	Event declaration and handling
|
\****************************************************************************/

struct TTUSB_CALLBACKCOMPLETION_HDR
	{
	__TMS_PUCALLBACKFN	ucbh_callback_pfn;
	__TMS_VOID *		ucbh_callback_ctx;
	};

/* the macro to embed at the head of derived structures */
#define __TMS_UCALLBACKCOMPLETIONHDR  struct TTUSB_CALLBACKCOMPLETION_HDR ucbh_hh
#define __TMS_CALLBACKCOMPLETIONHDR  __TMS_UCALLBACKCOMPLETIONHDR

/* the generic version of the structure */
struct TTUSB_CALLBACKCOMPLETION
	{
	__TMS_UCALLBACKCOMPLETIONHDR;
	};

/* sane names */
#define callback_pfn	ucbh_hh.ucbh_callback_pfn
#define callback_ctx	ucbh_hh.ucbh_callback_ctx

/*

Name:	USBPUMP_CALLBACKCOMPLETION_INIT()

Function:
	Initialize a CALLBACKCOMPLETION object

Definition:
	VOID USBPUMP_CALLBACKCOMPLETION_INIT(
		CALLBACKCOMPLETION *	pCallback,
		PUCALLBACKFN		pFn,
		VOID *			pContext
		);

Description:
	Initialize a CALLBACKCOMPLETION object with specified callback function
	and context of callback function. To "post an event," the DataPump code
	initialize a CALLBACKCOMPLETION object and passes a pointer to PostEvent.
	Later, the DataPump main event loop dequeues that pointer, and alls the
	specified callback function with context.

Returns:
	No explicit result.

*/

#define	__TMS_USBPUMP_CALLBACKCOMPLETION_INIT(pCallback, pFn, pContext)	\
    do	{								\
	(pCallback)->callback_pfn = (pFn);				\
	(pCallback)->callback_ctx = (pContext);				\
	} while (0)


/****************************************************************************\
|
|	API functions
|
\****************************************************************************/

__TMS_BEGIN_DECLS

__TMS_VOID UHIL_PostCallback(
		__TMS_UPLATFORM *		/* pPlatform */,
		__TMS_UCALLBACKCOMPLETION *	/* pCallback */
		);

__TMS_END_DECLS


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define UCALLBACKCOMPLETIONHDR	\
   __TMS_UCALLBACKCOMPLETIONHDR
# define CALLBACKCOMPLETIONHDR	\
   __TMS_CALLBACKCOMPLETIONHDR
# define USBPUMP_CALLBACKCOMPLETION_INIT(pCallback, pFn, pContext)	\
   __TMS_USBPUMP_CALLBACKCOMPLETION_INIT(pCallback, pFn, pContext)
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of ucallback.h ****/
#endif /* _UCALLBACK_H_ */
