/* uhilswc.h	Sat May 30 2015 14:45:43  tmm */

/*

Module:  uhilswc.h

Function:
	Define the UHIL software check codes and functions.

Version:
	V3.15b	Sat May 30 2015 14:45:43  tmm	Edit level 9

Copyright notice:
	This file copyright (C) 2002-2006, 2015 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation.

Author:
	Terry Moore, MCCI Corporation	June 2002

Revision history:
   1.79a  Thu Jun  6 2002 11:06:33  tmm
	Module created.  Added UHILSWC_OBJECT_DEINIT_TWICE.

   1.83e  3/27/2003  tmm
	uhilswc.h and uhilerrvals.h both defined several error codes.
	Removed them from uhilswc.h.

   1.87a Thu Dec 11 2003 12:20:00 maw
	Add RTC code-range

   1.91g  2005-07-21  tmm
	Add UHILSWC_TASK_ROOT_ALLOC.

   1.91h  Wed Aug 24 2005 14:13:41  chwon
	Add USBPUMPSWC_IOCTL_NOT_CLAIMED.

   1.93e  Thu Jan 12 2006 10:18:40  chwon
	Add UHILSWC_UTASKBASE

   1.93e  Wed Feb 01 2006 11:46:57  chwon
	Add UHILSWC_OSBASE and UHILSWC_LIBBASE

   1.97b  Thu Apr 13 2006 11:51:05  chwon
	Add UHILSWC_MTPBASE
	
   3.15b  Sat May 30 2015 14:45:43  tmm
   	19210: add USBPUMPSWC_ASSERTION_FAILURE.

*/

#ifndef _UHILSWC_H_		/* prevent multiple includes */
#define _UHILSWC_H_

#ifndef _BASEHILTYPES_H_
# include "basehiltypes.h"
#endif

/****************************************************************************\
|
|	Software Check (SWC)
|
\****************************************************************************/

/* codes 0x0 to 0x7f are reserved for the generic HIL layer */
#define __TMS_UHILSWC_HILBASE		0x0

/* codes 0x80 to 0xff are reserved for the "device-specific" HIL layer */
#define __TMS_UHILSWC_DEVBASE		0x80

/* codes 0x100 to 0x1ff are reserved for the DataPump layer */
#define __TMS_UHILSWC_PUMPBASE		0x100

/* codes 0x200 to 0x2ff are for the VSP */
#define __TMS_UHILSWC_APPBASE		0x200

/* codes 0x300 to 0x3ff are for the DFU */
#define __TMS_UHILSWC_DFUBASE		0x300

/* codes 0x400 to 0x41f are for W32 */
#define __TMS_UHILSWC_W32BASE		0x400

/* codes 0x420 to 0x43f are for OSE */
#define __TMS_UHILSWC_OSEBASE		0x420

/* codes 0x440 to 0x45f are for RTK */
#define __TMS_UHILSWC_RTKBASE		0x440

/* codes 0x480 to 0x4ff are for the generic OS layer */
#define __TMS_UHILSWC_OSBASE		0x480

/* codes 0x500 to 0x57f are for the generic UTASK layer */
#define __TMS_UHILSWC_UTASKBASE		0x500

/* codes 0x580 to 0x5ff are for the MCCI library */
#define __TMS_UHILSWC_LIBBASE		0x580

/* codes 0x600 to 0x67f are for the MCCI library */
#define __TMS_UHILSWC_MTPBASE		0x600

/* codes 0x8000 and up are for the user apps */
#define __TMS_UHILSWC_USERBASE		0x8000

/*
|| The DataPump SWCs
*/
#define	__TMS_USBPUMPSWC_OBJECT_DEINIT_TWICE	(__TMS_UHILSWC_PUMPBASE | 1)
#define	__TMS_USBPUMPSWC_TASK_ROOT_INIT		(__TMS_UHILSWC_PUMPBASE | 2)
#define	__TMS_USBPUMPSWC_TASK_ROOT_NOMEM	(__TMS_UHILSWC_PUMPBASE | 3)
#define	__TMS_USBPUMPSWC_OBJECT_ADD_TWICE	(__TMS_UHILSWC_PUMPBASE | 4)
#define	__TMS_USBPUMPSWC_IOCTL_NOT_CLAIMED	(__TMS_UHILSWC_PUMPBASE | 5)
#define	__TMS_USBPUMPSWC_ASSERTION_FAILURE	(__TMS_UHILSWC_PUMPBASE | 6)


/**************************************************************************\
||
||	Function prototypes
||
\**************************************************************************/

/* UHIL_swc *must* be provided by the OS implementation layer */
__TMS_BEGIN_DECLS
__TMS_ONEWAY(__TMS_VOID		UHIL_swc __TMS_P((__TMS_UHIL_SWCCODE)));
__TMS_END_DECLS


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define UHILSWC_HILBASE	\
   __TMS_UHILSWC_HILBASE
# define UHILSWC_DEVBASE	\
   __TMS_UHILSWC_DEVBASE
# define UHILSWC_PUMPBASE	\
   __TMS_UHILSWC_PUMPBASE
# define UHILSWC_APPBASE	\
   __TMS_UHILSWC_APPBASE
# define UHILSWC_DFUBASE	\
   __TMS_UHILSWC_DFUBASE
# define UHILSWC_W32BASE	\
   __TMS_UHILSWC_W32BASE
# define UHILSWC_OSEBASE	\
   __TMS_UHILSWC_OSEBASE
# define UHILSWC_RTKBASE	\
   __TMS_UHILSWC_RTKBASE
# define UHILSWC_OSBASE	\
   __TMS_UHILSWC_OSBASE
# define UHILSWC_UTASKBASE	\
   __TMS_UHILSWC_UTASKBASE
# define UHILSWC_LIBBASE	\
   __TMS_UHILSWC_LIBBASE
# define UHILSWC_MTPBASE	\
   __TMS_UHILSWC_MTPBASE
# define UHILSWC_USERBASE	\
   __TMS_UHILSWC_USERBASE
# define USBPUMPSWC_OBJECT_DEINIT_TWICE	\
   __TMS_USBPUMPSWC_OBJECT_DEINIT_TWICE
# define USBPUMPSWC_TASK_ROOT_INIT	\
   __TMS_USBPUMPSWC_TASK_ROOT_INIT
# define USBPUMPSWC_TASK_ROOT_NOMEM	\
   __TMS_USBPUMPSWC_TASK_ROOT_NOMEM
# define USBPUMPSWC_OBJECT_ADD_TWICE	\
   __TMS_USBPUMPSWC_OBJECT_ADD_TWICE
# define USBPUMPSWC_IOCTL_NOT_CLAIMED	\
   __TMS_USBPUMPSWC_IOCTL_NOT_CLAIMED
# define USBPUMPSWC_ASSERTION_FAILURE \
  __TMS_USBPUMPSWC_ASSERTION_FAILURE
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of uhilswc.h ****/
#endif /* _UHILSWC_H_ */
