/* usbdesc_types.h	Thu Jun 17 2010 14:06:34 chwon */

/*

Module:  usbdesc_types.h

Function:
	Define the symbolic types for USB descriptors.

Version:
	V3.01c	Thu Jun 17 2010 14:06:34 chwon	Edit level 8

Copyright notice:
	This file copyright (C) 2002-2003, 2006, 2008-2010 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	Terry Moore, MCCI Corporation	May 2002

Revision history:
   1.64a  Mon May 27 2002 16:41:15  tmm
	Module created.

   1.85b  7/1/2003  tmm
	1095:  Add USB 2.0 descriptors.

   1.93e  Fri Feb 17 2006 13:16:12  tmm
	Add USBIF_STRINGDESC, USBIF_STRINGDESC_WIRE.

   1.97k  Wed Sep 24 2008 11:13:20  cccho
	6683: add USBIF_BOSDESC, USBIF_BOSDESC_WIRE, USBIF_DEVCAPDESC,
	USBIF_DEVCAPDESC_WIRE, USBIF_EXTENSION_DEVCAPDESC and
	USBIF_EXTENSION_DEVCAPDESC_WIRE.

   1.97j  Fri Nov 14 2008 11:19:32  sivaraj
	6288: Add USBIF_BOSDESC, USBIF_BOSDESC_WIRE, USBIF_SECURITYDESC and
	USBIF_SECURITYDESC_WIRE

   1.97j  Tue Nov 18 2008 13:00:11  sivaraj
	6288: Add USBIF_WEP_COMPANION_DESC, USBIF_WEP_COMPANION_DESC_WIRE,
	USBIF_WUSB_DEVCAPDESC and USBIF_WUSB_DEVCAPDESC_WIRE

   2.01a  Wed Mar 25 2009 19:03:47  djt
	7416: Added SUPERSPEED types.

   3.01c  Thu Jun 17 2010 14:06:34  chwon
	10596: Add USBIF_STRINGDESC_LANGID, USBIF_STRINGDESC_LANGID_WIRE,
	USBIF_ENCRYPYDESC, USBIF_ENCRYPYDESC_WIRE, USBIF_KEYDESC and
	USBIF_KEYDESC_WIRE.  Remove USBIF_IFPDESC, USBIF_IFPDESC_WIRE,
	USBIF_DEBUGDESC and USBIF_DEBUGDESC_WIRE.

*/

#ifndef _USBDESC_TYPES_H_		/* prevent multiple includes */
#define _USBDESC_TYPES_H_

#ifndef _DEF_CDEFS_H_
# include "def/cdefs.h"
#endif

/****************************************************************************\
|
|	We sometimes need to get these into the namespace without
|	pulling everything else in.  So we define them here.
|
\****************************************************************************/

__TMS_TYPE_DEF_STRUCT(USBIF_DEVDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_DEVDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_CFGDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_CFGDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_STRINGDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_STRINGDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_STRINGDESC_LANGID);
__TMS_TYPE_DEF_STRUCT(USBIF_STRINGDESC_LANGID_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_IFCDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_IFCDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_EPDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_EPDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_DEVQUALDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_DEVQUALDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_OSCFGDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_OSCFGDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_OTGDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_OTGDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_IADESC);
__TMS_TYPE_DEF_STRUCT(USBIF_IADESC_WIRE);

__TMS_TYPE_DEF_STRUCT(USBIF_DESC);
__TMS_TYPE_DEF_STRUCT(USBIF_DESC_WIRE);

__TMS_TYPE_DEF_STRUCT(USBIF_BOSDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_BOSDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_DEVCAPDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_DEVCAPDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_SECURITYDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_SECURITYDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_ENCRYPYDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_ENCRYPYDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_KEYDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_KEYDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_WEP_COMPANION_DESC);
__TMS_TYPE_DEF_STRUCT(USBIF_WEP_COMPANION_DESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_WUSB_DEVCAPDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_WUSB_DEVCAPDESC_WIRE);

__TMS_TYPE_DEF_STRUCT(USBIF_SUPERSPEED_EP_COMPANION_DESC);
__TMS_TYPE_DEF_STRUCT(USBIF_SUPERSPEED_EP_COMPANION_DESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_SUPERSPEED_DEVCAPDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_SUPERSPEED_DEVCAPDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_EXTENSION_DEVCAPDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_EXTENSION_DEVCAPDESC_WIRE);
__TMS_TYPE_DEF_STRUCT(USBIF_CONTAINER_ID_DEVCAPDESC);
__TMS_TYPE_DEF_STRUCT(USBIF_CONTAINER_ID_DEVCAPDESC_WIRE);

/**** end of usbdesc_types.h ****/
#endif /* _USBDESC_TYPES_H_ */
