/* usbpump_wusb_dev_defines.h	Fri Nov 14 2008 11:19:32 ssatish */

/*

Module:  usbpump_wusb_dev_defines.h

Function:
	WUSB device definitions.

Version:
	V1.97j	Fri Nov 14 2008 11:19:32 ssatish	Edit level 1

Copyright notice:
	This file copyright (C) 2008 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	Sathish Kumar, MCCI Corporation	November 2008

Revision history:
   1.97j  Fri Nov 14 2008 11:19:32  ssatish
	UDP-6287: Module created.

*/

#ifndef _USBPUMP_WUSB_DEV_DEFINES_H_		/* prevent multiple includes */
#define _USBPUMP_WUSB_DEV_DEFINES_H_

/* Necessary Includes */
#ifndef _USBPUMP_WUSB_DEV_TYPES_H_
# include "usbpump_wusb_dev_types.h"
#endif

/****************************************************************************\
|
|	Utility things for handling WUSB device operations
|
\****************************************************************************/
#define __TMS_USBPUMP_WUSB_DEV_CHID_SIZE		(16)
#define __TMS_USBPUMP_WUSB_DEV_CDID_SIZE		(16)
#define __TMS_USBPUMP_WUSB_DEV_CKEY_SIZE		(16)
#define __TMS_USBPUMP_WUSB_DEV_FRIENDLY_NAME_SIZE	(64)


/****************************************************************************\
|
|	Definition of USBPUMP_WUSB_DEV_CHID
|
\****************************************************************************/

struct __TMS_STRUCTNAME(USBPUMP_WUSB_DEV_CHID)
	{
	/*
	|| Connection Host ID
	*/
	__TMS_UINT8		Chid[__TMS_USBPUMP_WUSB_DEV_CHID_SIZE];
	};


/****************************************************************************\
|
|	Definition of USBPUMP_WUSB_DEV_CDID
|
\****************************************************************************/

struct __TMS_STRUCTNAME(USBPUMP_WUSB_DEV_CDID)
	{
	/*
	|| Connection Device ID
	*/
	__TMS_UINT8		Cdid[__TMS_USBPUMP_WUSB_DEV_CDID_SIZE];
	};


/****************************************************************************\
|
|	Definition of USBPUMP_WUSB_DEV_CKEY
|
\****************************************************************************/

struct __TMS_STRUCTNAME(USBPUMP_WUSB_DEV_CKEY)
	{
	/*
	|| Connection Key
	*/
	__TMS_UINT8		Ckey[__TMS_USBPUMP_WUSB_DEV_CKEY_SIZE];
	};


/****************************************************************************\
|
|	Definition of USBPUMP_WUSB_DEV_SCAN_HOST_INFO
|
\****************************************************************************/

struct __TMS_STRUCTNAME(USBPUMP_WUSB_DEV_SCAN_HOST_INFO)
	{
	/*
	|| Connection Host ID
	*/
	__TMS_USBPUMP_WUSB_DEV_CHID		CHID;
	/*
	|| Band Group Number
	*/
	__TMS_USBPUMP_WUSB_DEV_BAND_GRP_NUM	BandGroupNum;
	/*
	|| Channel Number
	*/
	__TMS_USBPUMP_WUSB_DEV_CHANNEL_NUM	ChannelNum;
	};


/****************************************************************************\
|
|	Definition of USBPUMP_WUSB_DEV_CONN_CONTEXT
|
\****************************************************************************/

struct __TMS_STRUCTNAME(USBPUMP_WUSB_DEV_CONN_CONTEXT)
	{
	/*
	|| Connection Host ID
	*/
	__TMS_USBPUMP_WUSB_DEV_CHID 		CHID;
	/*
	|| Connection Device ID
	*/
	__TMS_USBPUMP_WUSB_DEV_CDID 		CDID;
	/*
	|| Connection key.
	*/
	__TMS_USBPUMP_WUSB_DEV_CKEY 		CKEY;
	/*
	|| Band Group Number
	*/
	__TMS_USBPUMP_WUSB_DEV_BAND_GRP_NUM	BandGroupNum;
	/*
	|| Channel Number
	*/
	__TMS_USBPUMP_WUSB_DEV_CHANNEL_NUM	ChannelNum;
	};


/****************************************************************************\
|
|	Definition of USBPUMP_WUSB_DEV_NUMERIC_ASSOC_CC_INFO
|
\****************************************************************************/

struct __TMS_STRUCTNAME(USBPUMP_WUSB_DEV_NUMERIC_ASSOC_CC_INFO)
	{
	/*
	|| Connection Host ID
	*/
	__TMS_USBPUMP_WUSB_DEV_CHID 		CHID;
	/*
	|| Connection Device ID
	*/
	__TMS_USBPUMP_WUSB_DEV_CDID 		CDID;
	/*
	|| Connection Key
	*/
	__TMS_USBPUMP_WUSB_DEV_CKEY 		CKEY;
	/*
	|| Host Friendly Name
	*/
	__TMS_USBPUMP_UTF8_TEXT	*		pHostFriendlyName;
	/*
	|| Band Group Number
	*/
	__TMS_USBPUMP_WUSB_DEV_BAND_GRP_NUM	BandGroupNum;
	/*
	|| Channel Number
	*/
	__TMS_USBPUMP_WUSB_DEV_CHANNEL_NUM	ChannelNum;
	};


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_WUSB_DEV_CHID_SIZE	\
   __TMS_USBPUMP_WUSB_DEV_CHID_SIZE
# define USBPUMP_WUSB_DEV_CDID_SIZE	\
   __TMS_USBPUMP_WUSB_DEV_CDID_SIZE
# define USBPUMP_WUSB_DEV_CKEY_SIZE	\
   __TMS_USBPUMP_WUSB_DEV_CKEY_SIZE
# define USBPUMP_WUSB_DEV_FRIENDLY_NAME_SIZE	\
   __TMS_USBPUMP_WUSB_DEV_FRIENDLY_NAME_SIZE
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpump_wusb_dev_defines.h ****/
#endif /* _USBPUMP_WUSB_DEV_DEFINES_H_ */
