/* usbpumpenv.h	Thu Apr 21 2011 13:10:44 chwon */

/*

Module:  usbpumpenv.h

Function:
	Set up the compilation environment for the USB DataPump

Version:
	V3.01f	Thu Apr 21 2011 13:10:44 chwon	Edit level 4

Copyright notice:
	This file copyright (C) 2002, 2009, 2011 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.
	
	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation
 
Author:
	Terry Moore, MCCI Corporation	May 2002

Revision history:
   1.79a  Mon May 27 2002 22:45:53  tmm
	Module created.

   1.83d  Fri Feb 28 2003 16:15:00  maw
   	Defined USBPUMP_UNREFERENCED_PARAMETER

   1.83d  3/28/2003  tmm
	Fix definition of USBPUMP_UNREFERENCED_PARAMETER to take an argument.

   2.01a  Tue Mar 03 2009 13:25:49  chwon
	3527: add USBPUMP_API_PARAMETER() macro.

   3.01f  Thu Apr 21 2011 13:10:44  chwon
	13281: remove stddef.h inclusion.

*/

#ifndef _USBPUMPENV_H_		/* prevent multiple includes */
#define _USBPUMPENV_H_

/****************************************************************************\
|
|	Parameters for tuning declarations
|
\****************************************************************************/

#ifndef _USBPUMPPARAMS_H_
# include "usbpumpparams.h"
#endif

/****************************************************************************\
|
|	Required include files.
|
\****************************************************************************/

#ifndef _DEF_CDEFS_H_
# include "def/cdefs.h"
#endif

#ifndef _MCCIDEFS_H_
# include "mccidefs.h"
#endif

#ifndef	_DEF_KERNTYPES_H_
# if !__TMS_CLOAKED_NAMES_ONLY
#  include "def/kerntypes.h"
# endif
#endif /* _KERNTYPES_H_ */

#ifndef _BASEHILENV_H_
# include "basehilenv.h"
#endif

#ifndef _USBIF_H_
# include "usbif.h"
#endif


/****************************************************************************\
|
|	The structure tags and forward types
|
\****************************************************************************/

#ifndef _USBPUMP_TYPES_H_
# include "usbpump_types.h"
#endif

/*
|| Define usbpump-macros from libport versions
*/
#define __TMS_USBPUMP_UNREFERENCED_PARAMETER(x)	\
	__TMS_LIBPORT_UNREFERENCED_PARAMETER(x)

#define __TMS_USBPUMP_API_PARAMETER(x)	\
	__TMS_LIBPORT_API_PARAMETER(x)


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_UNREFERENCED_PARAMETER(x)	\
   __TMS_USBPUMP_UNREFERENCED_PARAMETER(x)
# define USBPUMP_API_PARAMETER(x)	\
   __TMS_USBPUMP_API_PARAMETER(x)
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpumpenv.h ****/
#endif /* _USBPUMPENV_H_ */
