/* usbpump_power_state.h	Fri Mar 30 2012 10:00:41 cccho */

/*

Module:  usbpump_power_state.h

Function:
	Definition of power state.

Version:
	V3.01f	Fri Mar 30 2012 10:00:41 cccho	Edit level 1

Copyright notice:
	This file copyright (C) 2012 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	ChiaChu Cho, MCCI Corporation	March 2012

Revision history:
   3.01f  Fri Mar 30 2012 10:00:41 cccho
	15053: Module created.

*/

#ifndef _USBPUMP_POWER_STATE_H_		/* prevent multiple includes */
#define _USBPUMP_POWER_STATE_H_

#ifndef _USBPUMP_TYPES_H_
# include "usbpump_types.h"
#endif

/****************************************************************************\
|
|	USBPUMP POWER STATE
|
\****************************************************************************/

#define	__TMS_USBPUMP_POWER_STATE_D0	0	/* working state */
#define	__TMS_USBPUMP_POWER_STATE_D1	1	/* intermediate sleep */
#define	__TMS_USBPUMP_POWER_STATE_D2	2	/* intermediate sleep */
#define	__TMS_USBPUMP_POWER_STATE_D3	3	/* deepest sleep */


/****************************************************************************\
|
|	USBPUMP POWER ACTION
|
\****************************************************************************/

#define	__TMS_USBPUMP_POWER_ACTION_NONE		0
#define	__TMS_USBPUMP_POWER_ACTION_SLEEP	1
#define	__TMS_USBPUMP_POWER_ACTION_HIBERNATE	2
#define	__TMS_USBPUMP_POWER_ACTION_SHUTDOWN	3
#define	__TMS_USBPUMP_POWER_ACTION_RESTART	4


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_POWER_STATE_D0	\
   __TMS_USBPUMP_POWER_STATE_D0
# define USBPUMP_POWER_STATE_D1	\
   __TMS_USBPUMP_POWER_STATE_D1
# define USBPUMP_POWER_STATE_D2	\
   __TMS_USBPUMP_POWER_STATE_D2
# define USBPUMP_POWER_STATE_D3	\
   __TMS_USBPUMP_POWER_STATE_D3
# define USBPUMP_POWER_ACTION_NONE	\
   __TMS_USBPUMP_POWER_ACTION_NONE
# define USBPUMP_POWER_ACTION_SLEEP	\
   __TMS_USBPUMP_POWER_ACTION_SLEEP
# define USBPUMP_POWER_ACTION_HIBERNATE	\
   __TMS_USBPUMP_POWER_ACTION_HIBERNATE
# define USBPUMP_POWER_ACTION_SHUTDOWN	\
   __TMS_USBPUMP_POWER_ACTION_SHUTDOWN
# define USBPUMP_POWER_ACTION_RESTART	\
   __TMS_USBPUMP_POWER_ACTION_RESTART
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpump_power_state.h ****/
#endif /* _USBPUMP_POWER_STATE_H_ */
