/* usbpumplib_bincode.h	Thu Apr 13 2006 08:36:52 tmm */

/*

Module:  usbpumplib_bincode.h

Function:
	Definitions for binary encoding for DataPump use.

Version:
	V1.97b	Thu Apr 13 2006 08:36:52 tmm	Edit level 4

Copyright notice:
	This file copyright (C) 2005-2006 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation.

Author:
	Terry Moore, MCCI Corporation	September 2005

Revision history:
   1.91i  Sat Sep 17 2005 16:12:03  tmm
	Module created.

   1.91i  Mon Sep 19 2005 19:28:44  tmm
	Add UsbPumpLib_BinaryDecode().

   1.97a  Fri Apr 07 2006 10:52:20  lin
	Added big and little for UINT128.

   1.97b  Thu Apr 13 2006 08:36:52  tmm
	Finish up the encoding for INT128_S/UINT128_S.

*/

#ifndef _USBPUMPLIB_BINCODE_H_		/* prevent multiple includes */
#define _USBPUMPLIB_BINCODE_H_

#ifndef _USBPUMP_TYPES_H_
# include "usbpump_types.h"
#endif

/* get a definition for va_list in scope */
#include <stdarg.h>
#include "usbvalst.h"

/****************************************************************************\
|
|	The definitions for the format values
|
\****************************************************************************/

__TMS_TYPE_DEF(USBPUMPLIB_BINFMT_T, int);
__TMS_TYPE_DEF(ARG_USBPUMPLIB_BINFMT_T, int);

#define	__TMS_USBPUMPLIB_BINFMT_END		0
#define	__TMS_USBPUMPLIB_BINFMT_INT8		1
#define	__TMS_USBPUMPLIB_BINFMT_UINT8		2
#define	__TMS_USBPUMPLIB_BINFMT_LE_INT16	3
#define	__TMS_USBPUMPLIB_BINFMT_LE_UINT16	4
#define	__TMS_USBPUMPLIB_BINFMT_BE_INT16	5
#define	__TMS_USBPUMPLIB_BINFMT_BE_UINT16	6
#define	__TMS_USBPUMPLIB_BINFMT_LE_INT32	7
#define	__TMS_USBPUMPLIB_BINFMT_LE_UINT32	8
#define	__TMS_USBPUMPLIB_BINFMT_BE_INT32	9
#define	__TMS_USBPUMPLIB_BINFMT_BE_UINT32	10
#define	__TMS_USBPUMPLIB_BINFMT_LE_INT64	11
#define	__TMS_USBPUMPLIB_BINFMT_LE_UINT64	12
#define	__TMS_USBPUMPLIB_BINFMT_BE_INT64	13
#define	__TMS_USBPUMPLIB_BINFMT_BE_UINT64	14
#define __TMS_USBPUMPLIB_BINFMT_LE_INT128_S	15
#define __TMS_USBPUMPLIB_BINFMT_LE_UINT128_S	16
#define __TMS_USBPUMPLIB_BINFMT_BE_INT128_S	17
#define __TMS_USBPUMPLIB_BINFMT_BE_UINT128_S	18
#define	__TMS_USBPUMPLIB_BINFMT__MAX		19

/* use this to initialize an array that maps from values to strings */
#define	__TMS_USBPUMPLIB_BINFMT__INIT		\
	"USBPUMPLIB_BINFMT_END",	\
	"USBPUMPLIB_BINFMT_INT8",	\
	"USBPUMPLIB_BINFMT_UINT8",	\
	"USBPUMPLIB_BINFMT_LE_INT16",	\
	"USBPUMPLIB_BINFMT_LE_UINT16",	\
	"USBPUMPLIB_BINFMT_BE_INT16",	\
	"USBPUMPLIB_BINFMT_BE_UINT16",	\
	"USBPUMPLIB_BINFMT_LE_INT32",	\
	"USBPUMPLIB_BINFMT_LE_UINT32",	\
	"USBPUMPLIB_BINFMT_BE_INT32",	\
	"USBPUMPLIB_BINFMT_BE_UINT32",	\
	"USBPUMPLIB_BINFMT_LE_INT64",	\
	"USBPUMPLIB_BINFMT_LE_UINT64",	\
	"USBPUMPLIB_BINFMT_BE_INT64",	\
	"USBPUMPLIB_BINFMT_BE_UINT64",	\
	"USBPUMPLIB_BINFMT_LE_INT128_S",	\
	"USBPUMPLIB_BINFMT_LE_UINT128_S",	\
	"USBPUMPLIB_BINFMT_BE_INT128_S",	\
	"USBPUMPLIB_BINFMT_BE_UINT128_S",	\
	"USBPUMPLIB_BINFMT__MAX"

/****************************************************************************\
|
|	The function prototypes
|
\****************************************************************************/

__TMS_BOOL
UsbPumpLib_BinaryDecode(
	__TMS_CONST __TMS_UINT8 *	/*pBuffer*/,
	__TMS_BYTES			/*nBuffer*/,
	__TMS_BYTES			/*iBuffer*/,
	__TMS_BYTES *			/*pNumWritten*/,
	...
	);

__TMS_BOOL
UsbPumpLib_VBinaryDecode(
	__TMS_CONST __TMS_UINT8 *	/*pBuffer*/,
	__TMS_BYTES			/*nBuffer*/,
	__TMS_BYTES			/*iBuffer*/,
	__TMS_BYTES *			/*pNumWritten*/,
	va_list				/*args*/
	);

__TMS_BOOL
UsbPumpLib_BinaryEncode(
	__TMS_UINT8 *	/*pBuffer*/,
	__TMS_BYTES	/*nBuffer*/,
	__TMS_BYTES	/*iBuffer*/,
	__TMS_BYTES *	/*pNumWritten*/,
	...
	);

__TMS_BOOL
UsbPumpLib_VBinaryEncode(
	__TMS_UINT8 *	/*pBuffer*/,
	__TMS_BYTES	/*nBuffer*/,
	__TMS_BYTES	/*iBuffer*/,
	__TMS_BYTES *	/*pNumWritten*/,
	va_list		/*args*/
	);

/****************************************************************************\
|
|	Uncloaked definitions
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMPLIB_BINFMT_END	__TMS_USBPUMPLIB_BINFMT_END
# define USBPUMPLIB_BINFMT_INT8	__TMS_USBPUMPLIB_BINFMT_INT8
# define USBPUMPLIB_BINFMT_UINT8	__TMS_USBPUMPLIB_BINFMT_UINT8
# define USBPUMPLIB_BINFMT_LE_INT16	__TMS_USBPUMPLIB_BINFMT_LE_INT16
# define USBPUMPLIB_BINFMT_LE_UINT16	__TMS_USBPUMPLIB_BINFMT_LE_UINT16
# define USBPUMPLIB_BINFMT_BE_INT16	__TMS_USBPUMPLIB_BINFMT_BE_INT16
# define USBPUMPLIB_BINFMT_BE_UINT16	__TMS_USBPUMPLIB_BINFMT_BE_UINT16
# define USBPUMPLIB_BINFMT_LE_INT32	__TMS_USBPUMPLIB_BINFMT_LE_INT32
# define USBPUMPLIB_BINFMT_LE_UINT32	__TMS_USBPUMPLIB_BINFMT_LE_UINT32
# define USBPUMPLIB_BINFMT_BE_INT32	__TMS_USBPUMPLIB_BINFMT_BE_INT32
# define USBPUMPLIB_BINFMT_BE_UINT32	__TMS_USBPUMPLIB_BINFMT_BE_UINT32
# define USBPUMPLIB_BINFMT_LE_INT64	__TMS_USBPUMPLIB_BINFMT_LE_INT64
# define USBPUMPLIB_BINFMT_LE_UINT64	__TMS_USBPUMPLIB_BINFMT_LE_UINT64
# define USBPUMPLIB_BINFMT_BE_INT64	__TMS_USBPUMPLIB_BINFMT_BE_INT64
# define USBPUMPLIB_BINFMT_BE_UINT64	__TMS_USBPUMPLIB_BINFMT_BE_UINT64
# define USBPUMPLIB_BINFMT_LE_INT128_S	__TMS_USBPUMPLIB_BINFMT_LE_INT128_S
# define USBPUMPLIB_BINFMT_LE_UINT128_S	__TMS_USBPUMPLIB_BINFMT_LE_UINT128_S
# define USBPUMPLIB_BINFMT_BE_INT128_S	__TMS_USBPUMPLIB_BINFMT_BE_INT128_S
# define USBPUMPLIB_BINFMT_BE_UINT128_S	__TMS_USBPUMPLIB_BINFMT_BE_UINT128_S
# define USBPUMPLIB_BINFMT__MAX	__TMS_USBPUMPLIB_BINFMT__MAX
# define USBPUMPLIB_BINFMT__INIT	__TMS_USBPUMPLIB_BINFMT__INIT
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpumplib_bincode.h ****/
#endif /* _USBPUMPLIB_BINCODE_H_ */
