/* usbpumplib_usbrc.h	Wed Apr 09 2014 12:54:44 chwon */

/*

Module:  usbpumplib_usbrc.h

Function:
	Definition of USBRC DataPump library functions.

Version:
	V3.13a	Wed Apr 09 2014 12:54:44 chwon	Edit level 2

Copyright notice:
	This file copyright (C) 2011, 2014 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	ChaeHee Won, MCCI Corporation	April 2011

Revision history:
   3.01f  Mon Apr 25 2011 14:13:42 chwon
	13269: Module created.

   3.13a  Wed Apr 09 2014 12:54:44  chwon
	18164: Add USBPUMP_DEVICE_GET_SIZE_INFO structure.

*/

#ifndef _USBPUMPLIB_USBRC_H_		/* prevent multiple includes */
#define _USBPUMPLIB_USBRC_H_

#ifndef _PUMPRCTB_H_
# include "pumprctb.h"
#endif

/****************************************************************************\
|
|	USBPUMP_DEVICE_SIZE_INFO structure
|
\****************************************************************************/

__TMS_TYPE_DEF_STRUCT(USBPUMP_DEVICE_SIZE_INFO);
struct __TMS_STRUCTNAME(USBPUMP_DEVICE_SIZE_INFO)
	{
	__TMS_UINT		nConfig;
	__TMS_UINT		nConfigHighSpeed;
	__TMS_UINT		nInterfaceSet;
	__TMS_UINT		nInterface;
	__TMS_UINT		nPipe;
	__TMS_UINT		nEndpoint;
	};


/****************************************************************************\
|
|	USBPUMP_DEVICE_GET_SIZE_INFO structure
|
\****************************************************************************/

__TMS_TYPE_DEF_STRUCT(USBPUMP_DEVICE_GET_SIZE_INFO);
struct __TMS_STRUCTNAME(USBPUMP_DEVICE_GET_SIZE_INFO)
	{
	__TMS_UINT32				Tag;
	__TMS_CONST __TMS_USBRC_ROOTTABLE *	pDescriptorTable;
	__TMS_CONST __TMS_UDEVICESWITCH *	pDeviceSwitch;
	__TMS_BYTES				SizeUdevice;	/* Output */
	};

/* Tag */
#define __TMS_USBPUMP_DEVICE_GET_SIZE_INFO_TAG			\
	__TMS_UHIL_MEMTAG('U', 'D', 'G', 'S')

#define	__TMS_USBPUMP_DEVICE_GET_SIZE_INFO_INIT_V1(		\
		a_pDescriptorTable,				\
		a_pDeviceSwitch					\
		)						\
	{							\
	__TMS_USBPUMP_DEVICE_GET_SIZE_INFO_TAG,			\
	(a_pDescriptorTable),					\
	(a_pDeviceSwitch),					\
	0							\
	}

#define	__TMS_USBPUMP_DEVICE_GET_SIZE_INFO_SETUP_V1(		\
		a_pInfo,					\
		a_pDescriptorTable,				\
		a_pDeviceSwitch					\
		)						\
    do	{							\
	(a_pInfo)->Tag = __TMS_USBPUMP_DEVICE_GET_SIZE_INFO_TAG;\
	(a_pInfo)->pDescriptorTable = (a_pDescriptorTable);	\
	(a_pInfo)->pDeviceSwitch = (a_pDeviceSwitch);		\
	(a_pInfo)->SizeUdevice = 0;				\
	} while (0)


/****************************************************************************\
|
|	API functions
|
\****************************************************************************/

__TMS_BEGIN_DECLS

__TMS_BYTES
UsbPumpLib_CalculateUdeviceSize(
	__TMS_CONST __TMS_USBRC_ROOTTABLE *	/* pRoot */,
	__TMS_CONST __TMS_UDEVICESWITCH *	/* pDeviceSwitch */
	);

__TMS_VOID
UsbPumpLib_FindAllSizeInfoFromRoot(
	__TMS_CONST __TMS_USBRC_ROOTTABLE *	/* pRoot */,
	__TMS_USBPUMP_DEVICE_SIZE_INFO *	/* pSizeInfo */
	);

__TMS_END_DECLS


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_DEVICE_GET_SIZE_INFO_TAG	\
   __TMS_USBPUMP_DEVICE_GET_SIZE_INFO_TAG
# define USBPUMP_DEVICE_GET_SIZE_INFO_INIT_V1(		\
		a_pDescriptorTable,				\
		a_pDeviceSwitch					\
		)	\
	__TMS_USBPUMP_DEVICE_GET_SIZE_INFO_INIT_V1(		\
		a_pDescriptorTable,				\
		a_pDeviceSwitch					\
		)
# define USBPUMP_DEVICE_GET_SIZE_INFO_SETUP_V1(		\
		a_pInfo,					\
		a_pDescriptorTable,				\
		a_pDeviceSwitch					\
		)	\
	__TMS_USBPUMP_DEVICE_GET_SIZE_INFO_SETUP_V1(		\
		a_pInfo,					\
		a_pDescriptorTable,				\
		a_pDeviceSwitch					\
		)
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpumplib_usbrc.h ****/
#endif /* _USBPUMPLIB_USBRC_H_ */
