/* usbpumplib_sha1.h	Wed Sep 28 2011 10:14:14 chwon */

/*

Module:  usbpumplib_sha1.h

Function:
	Definition of implementation of SHA-1 algorithm

Version:
	V3.01f	Wed Sep 28 2011 10:14:14 chwon	Edit level 1

Copyright notice:
	This file copyright (C) 2011 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	ChaeHee Won, MCCI Corporation	September 2011

Revision history:
   3.01f  Wed Sep 28 2011 10:14:14 chwon
	14300: Module created.

*/

#ifndef _USBPUMPLIB_SHA1_H_		/* prevent multiple includes */
#define _USBPUMPLIB_SHA1_H_

#ifndef _USBPUMP_TYPES_H_
# include "usbpump_types.h"
#endif

#ifndef _USBPUMPOBJECT_H_
# include "usbpumpobject.h"
#endif

/****************************************************************************\
|
|	Definition of USBPUMP_SHA1_CONTEXT
|
\****************************************************************************/

/* In all SHA Standards One Message Block contain 16 words */
#define __TMS_USBPUMP_SHA1_WORDS_IN_MSGBLOCK		16

/* Number of bytes in hash value */
#define __TMS_USBPUMP_SHA1_MESSAGE_DIGEST_LEN_IN_BYTES	20

__TMS_TYPE_DEF_STRUCT	(USBPUMP_SHA1_CONTEXT);
struct __TMS_STRUCTNAME	(USBPUMP_SHA1_CONTEXT)
	{
	/* To hold hash buffer values */
	unsigned long	HashBuffer32[5];

	/* To hold one message block */
	/* USBPUMP_SHA1_WORDS_IN_MSGBLOCK is 16 */
	unsigned long	MsgBuffer512[__TMS_USBPUMP_SHA1_WORDS_IN_MSGBLOCK];

	/*
	|| Residual message length, which is equal to number of message bytes
	|| in the last unprocessed block
	*/
	unsigned int	ResLength;

	/* To hold lower word of message length (in bits) */
	unsigned long	LowerWord32;

	/* To hold upper word of message length (in bits) */
	unsigned long	HigherWord32;

	/* object pointer for debug purpose */
	__TMS_USBPUMP_OBJECT_HEADER *	pObjectHeader;
	};


/****************************************************************************\
|
|	API functions
|
\****************************************************************************/

__TMS_USTAT
UsbPumpLib_SHA1_Init(
	__TMS_USBPUMP_SHA1_CONTEXT *	pSha1Ctx,
	__TMS_USBPUMP_OBJECT_HEADER *	pObjectHeader
	);

__TMS_USTAT
UsbPumpLib_SHA1_Update(
	__TMS_USBPUMP_SHA1_CONTEXT *	pSha1Ctx,
	__TMS_CONST __TMS_UCHAR *	pMsgBuff,
	unsigned long			MsgLength
	);

__TMS_USTAT
UsbPumpLib_SHA1_Final(
	__TMS_USBPUMP_SHA1_CONTEXT *	pSha1Ctx,
	__TMS_UCHAR *			pMsgDigest
	);


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define USBPUMP_SHA1_WORDS_IN_MSGBLOCK	\
   __TMS_USBPUMP_SHA1_WORDS_IN_MSGBLOCK
# define USBPUMP_SHA1_MESSAGE_DIGEST_LEN_IN_BYTES	\
   __TMS_USBPUMP_SHA1_MESSAGE_DIGEST_LEN_IN_BYTES
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of usbpumplib_sha1.h ****/
#endif /* _USBPUMPLIB_SHA1_H_ */
