/* utaskmsg_services.h	Thu May 22 2008 16:36:28 chwon */

/*

Module:  utaskmsg_services.h

Function:
	Central definitions for USB task message services

Version:
	V1.97k	Thu May 22 2008 16:36:28 chwon	Edit level 6

Copyright notice:
	This file copyright (C) 2005-2008 by

		MCCI Corporation
		3520 Krums Corners Road
		Ithaca, NY  14850

	An unpublished work.  All rights reserved.

	This file is proprietary information, and may not be disclosed or
	copied without the prior permission of MCCI Corporation

Author:
	Mats Webj?n, MCCI Corporation	March 2005

Revision history:
   1.91b  Tue Mar 22 2005 08:11:11 maw
	Module created.

   1.91c  Tue May 03 2005 07:56:00 maw
   	Added default task-names

   1.91d  Fri May 27 2005 16:08:40 maw
   	Added common service, updated names

   1.93e  Fri Feb 17 2006 4:14:30 skpark
   	Added names for PBCLI

   1.93e  Wed Feb 15 2006 13:46:18  chwon
	Added DPMSIC, MTP, MSS services.

   1.97f  Fri Nov 10 2006 16:41:46  chwon
	Add DPS task and process name

   1.97k  Thu May 22 2008 16:36:28  chwon
	4139: add comment for new service code and UTASK_MC_SERVICE_NAMES_INIT

*/

#ifndef _UTASKMSG_SERVICES_H_		/* prevent multiple includes */
#define _UTASKMSG_SERVICES_H_

/****************************************************************************\
|
|	These are the services
|
\****************************************************************************/

#define	__TMS_UTASK_MC_SERVICE_COMMON	0	/* Common service for all UTASK's */
#define	__TMS_UTASK_MC_SERVICE_DPCORE	1
#define	__TMS_UTASK_MC_SERVICE_DPMSC	2
#define	__TMS_UTASK_MC_SERVICE_DPSIC	3
#define	__TMS_UTASK_MC_SERVICE_DPWMC	4
#define	__TMS_UTASK_MC_SERVICE_PTP	5
#define	__TMS_UTASK_MC_SERVICE_PSS	6
#define	__TMS_UTASK_MC_SERVICE_DPS	7
#define	__TMS_UTASK_MC_SERVICE_PBCLI	8
#define	__TMS_UTASK_MC_SERVICE_DPMSIC	9
#define	__TMS_UTASK_MC_SERVICE_MTP	10
#define	__TMS_UTASK_MC_SERVICE_MSS	11

/*
|| Do not put new service code here!
|| Define new service code in the local header file and put comment here.
*/
/* __TMS_UTASK_MC_SERVICE_PLATFORM	12	-- defined uplatformmsg.h */
/* __TMS_UTASK_MC_SERVICE_DPCMDPARSER	13	-- defined usbpump_cmdpw_msg.h */

#define	__TMS_UTASK_MC_SERVICE_NAMES_INIT	\
	{					\
	"SERVICE_COMMON",			\
	"SERVICE_DPCORE",			\
	"SERVICE_DPMSC",			\
	"SERVICE_DPSIC",			\
	"SERVICE_DPWMC",			\
	"SERVICE_PTP",				\
	"SERVICE_PSS",				\
	"SERVICE_DPS",				\
	"SERVICE_PBCLI",			\
	"SERVICE_DPMSIC",			\
	"SERVICE_MTP",				\
	"SERVICE_MSS",				\
	"SERVICE_PLATFORM",			\
	"SERVICE_DPCMDPARSER"			\
	}


/****************************************************************************\
|
|	These are the names
|
\****************************************************************************/

#ifndef __TMS_UTASK_USB_DP_TASK_NAME
# define __TMS_UTASK_USB_DP_TASK_NAME	"MCCI USB DataPump Task"
#endif

#ifndef __TMS_UTASK_PBR_TASK_NAME
# define __TMS_UTASK_PBR_TASK_NAME	"MCCI PictBridge Task"
#endif

#ifndef __TMS_UTASK_PBR_PTP_TASK_NAME
# define __TMS_UTASK_PBR_PTP_TASK_NAME	"MCCI PictBridge PTP Task"
#endif

#ifndef __TMS_UTASK_PBR_PSS_TASK_NAME
# define __TMS_UTASK_PBR_PSS_TASK_NAME	"MCCI PictBridge PSS Task"
#endif

#ifndef __TMS_UTASK_PBR_DPS_TASK_NAME
# define __TMS_UTASK_PBR_DPS_TASK_NAME	"MCCI PictBridge DPS Task"
#endif

#ifndef __TMS_UTASK_PBR_PBCLI_TASK_NAME
# define __TMS_UTASK_PBR_PBCLI_TASK_NAME "MCCI PictBridge PBCLI Task"
#endif

#ifndef __TMS_UTASK_MTP_TASK_NAME
# define __TMS_UTASK_MTP_TASK_NAME	"MCCI MTP Task"
#endif

#ifndef __TMS_UTASK_MSS_TASK_NAME
# define __TMS_UTASK_MSS_TASK_NAME	"MCCI MSS Task"
#endif

#ifndef __TMS_UTASK_DPS_TASK_NAME
# define __TMS_UTASK_DPS_TASK_NAME	"MCCI DPS Task"
#endif

#ifndef __TMS_UTASK_USB_DP_PROC_NAME
# define __TMS_UTASK_USB_DP_PROC_NAME	"MCCI USB DataPump Proc"
#endif

#ifndef __TMS_UTASK_PBR_PTP_PROC_NAME
# define __TMS_UTASK_PBR_PTP_PROC_NAME	"MCCI PictBridge PTP Proc"
#endif

#ifndef __TMS_UTASK_PBR_PSS_PROC_NAME
# define __TMS_UTASK_PBR_PSS_PROC_NAME	"MCCI PictBridge PSS Proc"
#endif

#ifndef __TMS_UTASK_PBR_DPS_PROC_NAME
# define __TMS_UTASK_PBR_DPS_PROC_NAME	"MCCI PictBridge DPS Proc"
#endif

#ifndef __TMS_UTASK_PBR_PBCLI_PROC_NAME
# define __TMS_UTASK_PBR_PBCLI_PROC_NAME "MCCI PictBridge PBCLI Proc"
#endif

#ifndef __TMS_UTASK_MTP_PROC_NAME
# define __TMS_UTASK_MTP_PROC_NAME	"MCCI MTP Proc"
#endif

#ifndef __TMS_UTASK_MSS_PROC_NAME
# define __TMS_UTASK_MSS_PROC_NAME	"MCCI MSS Proc"
#endif

#ifndef __TMS_UTASK_DPS_PROC_NAME
# define __TMS_UTASK_DPS_PROC_NAME	"MCCI DPS Proc"
#endif


/****************************************************************************\
|
|	Uncloaked names
|
\****************************************************************************/

/**** uncloaked names generated by uncloak-defs.sh ****/
#if !__TMS_CLOAKED_NAMES_ONLY
# define UTASK_MC_SERVICE_COMMON	\
   __TMS_UTASK_MC_SERVICE_COMMON
# define UTASK_MC_SERVICE_DPCORE	\
   __TMS_UTASK_MC_SERVICE_DPCORE
# define UTASK_MC_SERVICE_DPMSC	\
   __TMS_UTASK_MC_SERVICE_DPMSC
# define UTASK_MC_SERVICE_DPSIC	\
   __TMS_UTASK_MC_SERVICE_DPSIC
# define UTASK_MC_SERVICE_DPWMC	\
   __TMS_UTASK_MC_SERVICE_DPWMC
# define UTASK_MC_SERVICE_PTP	\
   __TMS_UTASK_MC_SERVICE_PTP
# define UTASK_MC_SERVICE_PSS	\
   __TMS_UTASK_MC_SERVICE_PSS
# define UTASK_MC_SERVICE_DPS	\
   __TMS_UTASK_MC_SERVICE_DPS
# define UTASK_MC_SERVICE_PBCLI	\
   __TMS_UTASK_MC_SERVICE_PBCLI
# define UTASK_MC_SERVICE_DPMSIC	\
   __TMS_UTASK_MC_SERVICE_DPMSIC
# define UTASK_MC_SERVICE_MTP	\
   __TMS_UTASK_MC_SERVICE_MTP
# define UTASK_MC_SERVICE_MSS	\
   __TMS_UTASK_MC_SERVICE_MSS
# define UTASK_USB_DP_TASK_NAME	\
   __TMS_UTASK_USB_DP_TASK_NAME
# define UTASK_PBR_TASK_NAME	\
   __TMS_UTASK_PBR_TASK_NAME
# define UTASK_PBR_PTP_TASK_NAME	\
   __TMS_UTASK_PBR_PTP_TASK_NAME
# define UTASK_PBR_PSS_TASK_NAME	\
   __TMS_UTASK_PBR_PSS_TASK_NAME
# define UTASK_PBR_DPS_TASK_NAME	\
   __TMS_UTASK_PBR_DPS_TASK_NAME
# define UTASK_PBR_PBCLI_TASK_NAME	\
   __TMS_UTASK_PBR_PBCLI_TASK_NAME
# define UTASK_MTP_TASK_NAME	\
   __TMS_UTASK_MTP_TASK_NAME
# define UTASK_MSS_TASK_NAME	\
   __TMS_UTASK_MSS_TASK_NAME
# define UTASK_DPS_TASK_NAME	\
   __TMS_UTASK_DPS_TASK_NAME
# define UTASK_USB_DP_PROC_NAME	\
   __TMS_UTASK_USB_DP_PROC_NAME
# define UTASK_PBR_PTP_PROC_NAME	\
   __TMS_UTASK_PBR_PTP_PROC_NAME
# define UTASK_PBR_PSS_PROC_NAME	\
   __TMS_UTASK_PBR_PSS_PROC_NAME
# define UTASK_PBR_DPS_PROC_NAME	\
   __TMS_UTASK_PBR_DPS_PROC_NAME
# define UTASK_PBR_PBCLI_PROC_NAME	\
   __TMS_UTASK_PBR_PBCLI_PROC_NAME
# define UTASK_MTP_PROC_NAME	\
   __TMS_UTASK_MTP_PROC_NAME
# define UTASK_MSS_PROC_NAME	\
   __TMS_UTASK_MSS_PROC_NAME
# define UTASK_DPS_PROC_NAME	\
   __TMS_UTASK_DPS_PROC_NAME
#endif /* !__TMS_CLOAKED_NAMES_ONLY */

/**** end of utaskmsg_services.h ****/
#endif /* _UTASKMSG_SERVICES_H_ */
