///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "sippHwConv.h"

#include <include/sippHwDefs.h>


//The full-frame buffers
UInt8      DDR_DATA SippHwConv_dmaOut0_buffer[SIPP_HW_CONVOLUTION_BUFFER_WIDTH* SIPP_HW_CONVOLUTION_BUFFER_HEIGHT* SIPP_HW_CONVOLUTION_BUFFER_NUM_PLANES]ALIGNED(8);
	
///
void readSippHwConvInput(SippHwConv *pPl)
{
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeSippHwConvOutput(SippHwConv *pPl)
{
   sippWrFileU8((UInt8*)SippHwConv_dmaOut0_buffer,SIPP_HW_CONVOLUTION_BUFFER_WIDTH * SIPP_HW_CONVOLUTION_BUFFER_HEIGHT * SIPP_HW_CONVOLUTION_BUFFER_NUM_PLANES* sizeof(UInt8),"out_1280x4_HwConv.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildSippHwConv(SippHwConv *pPl)
{
   // create new pipeline in upper CMX slices
   pPl->pl               = sippCreatePipeline(13, 13, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_CONVOLUTION_BUFFER_WIDTH, SIPP_HW_CONVOLUTION_BUFFER_HEIGHT, N_PL(SIPP_HW_CONVOLUTION_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->convolution0    =  sippCreateFilter(pPl->pl, 0x0,        SIPP_HW_CONVOLUTION_BUFFER_WIDTH, SIPP_HW_CONVOLUTION_BUFFER_HEIGHT, N_PL(SIPP_HW_CONVOLUTION_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_CONV_ID,       0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_CONVOLUTION_BUFFER_WIDTH, SIPP_HW_CONVOLUTION_BUFFER_HEIGHT, N_PL(SIPP_HW_CONVOLUTION_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->convolution0,  pPl->dmaIn0,        3,3                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->convolution0,  1,1                 );
	
}

  
void configSippHwConv(SippHwConv *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   ConvParam           *convolution0Cfg    = (ConvParam        *)pPl->convolution0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   convolution0Cfg->cfg=    0;
   dmaIn0Cfg->ddrAddr   = (UInt32)iBuf;
   dmaOut0Cfg->ddrAddr  = (UInt32)&SippHwConv_dmaOut0_buffer;
  
  
}
