/*
 * sippHwConvolutionDefs.h
 *
 *  Created on: Apr 1, 2015
 */

#include "sippPlatform.h"

#ifndef _SIPPHWCONVOLUTIONDEFS_H_
#define _SIPPHWCONVOLUTIONDEFS_H_

/* MACROS */
/* Config macros */
#define SIPP_HW_CONVOLUTION_BUFFER_WIDTH       1280
#define SIPP_HW_CONVOLUTION_BUFFER_HEIGHT      4
#define SIPP_HW_CONVOLUTION_BUFFER_NUM_PLANES  1
#define SIPP_HW_CONVOLUTION_BUFFER_SIZE    (SIPP_HW_CONVOLUTION_BUFFER_WIDTH * SIPP_HW_CONVOLUTION_BUFFER_HEIGHT * SIPP_HW_CONVOLUTION_BUFFER_NUM_PLANES)


/* App globals */
extern UInt8 iBuf[SIPP_HW_CONVOLUTION_BUFFER_SIZE];

#endif /* _SIPPHWCONVOLUTIONDEFS_H_ */
