RUN_ON_PC = yes
ComponentList += kernelLib/MvCV
INT_DDR = no
USE_SHAVE_L2_CACHE = yes
# Include the common Makefile for the dummy application
include ../../../../shared/unittest/app_common.mk

TEST_TAGS := "MA2150"
