///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#include "testHwMedian.h"

#include <include/sippHwDefs.h>
#include <arch/ma2x5x/include/sippHwDefs_ma2x5x.h>


//The full-frame buffers
UInt8      DDR_DATA TestHwMedian_dmaIn0_buffer[SIPP_HW_MED_CHROMA_BUFFER_WIDTH* SIPP_HW_MED_CHROMA_BUFFER_HEIGHT* SIPP_HW_MED_CHROMA_BUFFER_NUM_PLANES]ALIGNED(8);
UInt8      DDR_DATA TestHwMedian_dmaIn1_buffer[SIPP_HW_MED_LUMA_BUFFER_WIDTH* SIPP_HW_MED_LUMA_BUFFER_HEIGHT* SIPP_HW_MED_LUMA_BUFFER_NUM_PLANES]ALIGNED(8);
UInt8      DDR_DATA TestHwMedian_dmaOut0_buffer[SIPP_HW_MED_CHROMA_BUFFER_WIDTH* SIPP_HW_MED_CHROMA_BUFFER_HEIGHT* SIPP_HW_MED_CHROMA_BUFFER_NUM_PLANES]ALIGNED(8);
	
///
void readTestHwMedianInput(TestHwMedian *pPl)
{
   sippRdFileU8((UInt8*)TestHwMedian_dmaIn0_buffer,SIPP_HW_MED_CHROMA_BUFFER_WIDTH * SIPP_HW_MED_CHROMA_BUFFER_HEIGHT * SIPP_HW_MED_CHROMA_BUFFER_NUM_PLANES* sizeof(UInt8),"../../../../../../../resources/OCT_192x145_I_median_chroma_8bpp.raw");
   sippRdFileU8((UInt8*)TestHwMedian_dmaIn1_buffer,SIPP_HW_MED_LUMA_BUFFER_WIDTH * SIPP_HW_MED_LUMA_BUFFER_HEIGHT * SIPP_HW_MED_LUMA_BUFFER_NUM_PLANES* sizeof(UInt8),"../../../../../../../resources/OCT_384x290_I_median_luma_8bpp.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);
	
}

void writeTestHwMedianOutput(TestHwMedian *pPl)
{
   sippWrFileU8((UInt8*)TestHwMedian_dmaOut0_buffer,SIPP_HW_MED_CHROMA_BUFFER_WIDTH * SIPP_HW_MED_CHROMA_BUFFER_HEIGHT * SIPP_HW_MED_CHROMA_BUFFER_NUM_PLANES* sizeof(UInt8),"output.raw");
   //Ensure parameter is used to avoid compiler warning
   (void)(pPl);

}
   
void buildTestHwMedian(TestHwMedian *pPl)
{
   // create new pipeline
   pPl->pl               = sippCreatePipeline(0, 0, SIPP_MBIN(mbinImgSipp));

   // create filters
   pPl->dmaIn0          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_MED_CHROMA_BUFFER_WIDTH, SIPP_HW_MED_CHROMA_BUFFER_HEIGHT, N_PL(SIPP_HW_MED_CHROMA_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->dmaIn1          =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_MED_LUMA_BUFFER_WIDTH, SIPP_HW_MED_LUMA_BUFFER_HEIGHT, N_PL(SIPP_HW_MED_LUMA_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
   pPl->medianMa2x5x0   =  sippCreateFilter(pPl->pl, 0x0,        SIPP_HW_MED_CHROMA_BUFFER_WIDTH, SIPP_HW_MED_CHROMA_BUFFER_HEIGHT, N_PL(SIPP_HW_MED_CHROMA_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_MED_ID,        0);
   pPl->dmaOut0         =  sippCreateFilter(pPl->pl, 0x00,       SIPP_HW_MED_CHROMA_BUFFER_WIDTH, SIPP_HW_MED_CHROMA_BUFFER_HEIGHT, N_PL(SIPP_HW_MED_CHROMA_BUFFER_NUM_PLANES), SZ(UInt8), SIPP_AUTO,          (FnSvuRun)SIPP_DMA_ID,        0);
	
   // link filters
   sippLinkFilter(pPl->medianMa2x5x0, pPl->dmaIn0,        7,7                 );
   sippLinkFilter(pPl->medianMa2x5x0, pPl->dmaIn1,        1,0                 );
   sippLinkFilter(pPl->dmaOut0,       pPl->medianMa2x5x0, 1,1                 );
	
}

  
void configTestHwMedian(TestHwMedian *pPl)
{
   DmaParam            *dmaIn0Cfg          = (DmaParam         *)pPl->dmaIn0->params;
   DmaParam            *dmaIn1Cfg          = (DmaParam         *)pPl->dmaIn1->params;
   MedParam            *medianMa2x5x0Cfg   = (MedParam         *)pPl->medianMa2x5x0->params;
   DmaParam            *dmaOut0Cfg         = (DmaParam         *)pPl->dmaOut0->params;
  
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // here go through all the filter instances and assign the value for all parameter
  // fields as defined in the filter property window
   medianMa2x5x0Cfg->cfg=   MED_CFG(KERNEL_SIZE,OUT_SEL,THRESHOLD,LUMA_ABLEND_EN,LUMA_SAMPLE_EN,0);
   medianMa2x5x0Cfg->lumaAlpha=( OFFSET | SLOPE << 8);
   dmaIn0Cfg->ddrAddr   = (UInt32)&TestHwMedian_dmaIn0_buffer;
   dmaIn1Cfg->ddrAddr   = (UInt32)&TestHwMedian_dmaIn1_buffer;
   dmaOut0Cfg->ddrAddr  = (UInt32)&TestHwMedian_dmaOut0_buffer;
  
  
}
