///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __TESTHWMEDIAN_H__
#define __TESTHWMEDIAN_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "testData.h"


//The full-frame buffers
extern UInt8 DDR_DATA TestHwMedian_dmaIn0_buffer[ SIPP_HW_MED_CHROMA_BUFFER_WIDTH * SIPP_HW_MED_CHROMA_BUFFER_HEIGHT * SIPP_HW_MED_CHROMA_BUFFER_NUM_PLANES ]ALIGNED(8);
extern UInt8 DDR_DATA TestHwMedian_dmaIn1_buffer[ SIPP_HW_MED_LUMA_BUFFER_WIDTH * SIPP_HW_MED_LUMA_BUFFER_HEIGHT * SIPP_HW_MED_LUMA_BUFFER_NUM_PLANES ]ALIGNED(8);
extern UInt8 DDR_DATA TestHwMedian_dmaOut0_buffer[ SIPP_HW_MED_CHROMA_BUFFER_WIDTH * SIPP_HW_MED_CHROMA_BUFFER_HEIGHT * SIPP_HW_MED_CHROMA_BUFFER_NUM_PLANES ]ALIGNED(8);
	
///

typedef struct TestHwMedian
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *medianMa2x5x0;
	SippFilter *dmaIn0;
	SippFilter *dmaOut0;
	SippFilter *dmaIn1;

} TestHwMedian;

void readTestHwMedianInput(TestHwMedian *pPl);
void writeTestHwMedianOutput(TestHwMedian *pPl);

void buildTestHwMedian(TestHwMedian *pPl);
void configTestHwMedian(TestHwMedian *pPl);


#endif